# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Executable classification of every ``ChangeKind`` for canonical identity.

Why this file exists
--------------------

``canonical_finding_id`` promises one thing: **the same finding gets the same
id whichever header backend produced it**, so a `finding_id:` suppression
written against a CastXML run still matches under `--ast-frontend clang`.
Delivering that for a kind whose ``old_value``/``new_value`` hold a C/C++ type
spelling requires the kind to be listed in
``finding_identity._TYPE_BEARING_DISCRIMINATOR_KINDS``.

That list is hand-maintained, and deliberately so — an automatic
classification was proposed and rejected (see the set's own comment), because
whether canonicalizing a kind's values is *safe* needs its emission call site
read: doing it to ``PUBLIC_MACRO_VALUE_CHANGED``'s raw macro text corrupts it,
and dropping ``description`` to compensate collides distinct findings that
differ only by a per-item identity the description embeds.

What was missing was not automation but **exhaustiveness**. PR #753 shipped the
feature with a list that silently omitted ``ATOMIC_QUALIFIER_CHANGED``,
``CHAR8T_MIGRATION`` and ``BIT_INT_WIDTH_CHANGED``; PR #759 added them hours
later after review caught it. Nothing failed in between — 12 targeted tests and
a 26k-test suite all passed, because a hand-written test can only cover the
kinds its author already thought of. A kind that is simply *absent* from the
list produces no failure anywhere.

The contract
------------

Every ``ChangeKind`` is in exactly one bucket below, and
``tests/test_canonical_finding_id_completeness.py`` enforces both the partition
and each bucket's observable behaviour. A newly added ``ChangeKind`` therefore
fails CI until someone puts it in a bucket — which is the forcing function that
was missing, without automating the judgement call.

Buckets are behavioural, not semantic, so no bucket asserts anything that has
not been observed:

``TYPE_BEARING``
    Values hold type spellings and *are* canonicalized. Mirrors
    ``_TYPE_BEARING_DISCRIMINATOR_KINDS`` — imported, never re-listed, so the
    two cannot drift.

``VALUE_INSENSITIVE``
    Identity does not vary with value spelling at all, because the kind
    resolves through ``_EQUIVALENT_CHANGE_CATEGORIES`` (which normalizes or
    drops values). Nothing to canonicalize; already backend-stable.

``UNVERIFIED``
    Identity *does* vary with value spelling, and the kind's call site has not
    been checked. This is a backlog, not a verdict: some entries are correct as
    they stand (a macro-text kind *should* be spelling-sensitive), others are
    the same latent gap #759 fixed. Entries leave only by being verified and
    moved — the test fails if one silently becomes stable, so the list can only
    shrink deliberately.
"""

from __future__ import annotations

from abicheck.finding_identity import _TYPE_BEARING_DISCRIMINATOR_KINDS

#: Values are type spellings and are canonicalized for identity.
#: Single source of truth: the runtime set itself.
TYPE_BEARING = frozenset(_TYPE_BEARING_DISCRIMINATOR_KINDS)

#: Identity is independent of value spelling (equivalent-category kinds).
VALUE_INSENSITIVE = frozenset(
    {
        "enum_last_member_value_changed",
        "enum_member_removed",
        "enum_member_value_changed",
        "enum_underlying_size_changed",
        "func_added",
        "func_deleted",
        "func_deleted_dwarf",
        "func_removed",
        "func_removed_elf_only",
        "header_binary_context_mismatch",
        "struct_alignment_changed",
        "struct_size_changed",
        "symbol_version_defined_removed",
        "symbol_version_node_removed",
        "type_alignment_changed",
        "type_size_changed",
        "var_added",
        "var_removed",
    }
)

#: Identity varies with value spelling; call site not yet verified.
#: See the module docstring — a backlog that may only shrink deliberately.
UNVERIFIED = frozenset(
    {
        "abi_relevant_build_flag_changed",
        "abi_surface_explosion",
        "abi_tag_changed",
        "allocator_replacement_added",
        "allocator_replacement_removed",
        "anon_field_changed",
        "api_depends_on_consumer_env",
        "base_class_offset_changed",
        "base_class_position_changed",
        "base_class_virtual_changed",
        "behavioural_default_changed",
        "bind_now_disabled",
        "branch_protection_improved",
        "branch_protection_weakened",
        "build_context_changed",
        "build_option_reaches_public_symbol",
        "bundle_intra_dep_removed",
        "bundle_intra_dep_resolved_to_different_version",
        "bundle_intra_dep_signature_changed",
        "bundle_intra_type_changed",
        "bundle_library_added",
        "bundle_library_removed",
        "bundle_manifest_instantiation_added",
        "bundle_manifest_instantiation_removed",
        "bundle_provider_changed",
        "bundle_intra_dep_signature_unverified",
        "bundle_soname_skew",
        "bundle_unresolved_intra_dependency",
        "bundle_variant_coverage_regressed",
        "call_graph_public_entry_reachability_changed",
        "calling_convention_changed",
        "cet_protection_improved",
        "cet_protection_weakened",
        "char_signedness_changed",
        "common_symbol_risk",
        "compat_version_changed",
        "compile_context_conflict",
        "concept_tightened",
        "constant_added",
        "constant_changed",
        "constant_removed",
        "constexpr_value_changed",
        "consumer_required_symbol_removed",
        "cpo_kind_changed",
        "cpu_dispatch_isa_dropped",
        "ctor_explicit_added",
        "ctor_explicit_removed",
        "ctor_overload_ambiguity_risk",
        "cxx_standard_floor_raised",
        "declaration_identity_reconciled",
        "declaration_moved",
        "declaration_renamed",
        "default_argument_changed",
        "default_template_arg_changed",
        "dt_relr_introduced",
        "dt_relr_removed",
        "dwarf_info_missing",
        "dynamic_loading_flags_changed",
        "elf_abi_flags_changed",
        "elf_class_changed",
        "elf_endianness_changed",
        "elf_init_fini_changed",
        "elf_machine_changed",
        "elf_osabi_changed",
        "enum_became_scoped",
        "enum_deprecated_added",
        "enum_deprecated_removed",
        "enum_lost_scoped",
        "enum_member_added",
        "enum_member_renamed",
        "enum_size_flag_changed",
        "evidence_required_missing",
        "exceptions_mode_changed",
        "executable_stack",
        "executable_stack_removed",
        "experimental_graduated",
        "experimental_removed_without_replacement",
        "exported_not_public",
        "exported_object_alignment_reduced",
        "exported_symbol_source_owner_changed",
        "field_access_changed",
        "field_became_const",
        "field_became_mutable",
        "field_became_volatile",
        "field_bitfield_changed",
        "field_default_initializer_changed",
        "field_default_initializer_removed",
        "field_deprecated_added",
        "field_deprecated_removed",
        "field_lost_const",
        "field_lost_mutable",
        "field_lost_volatile",
        "field_renamed",
        "flexible_array_member_changed",
        "float_abi_changed",
        "fortify_source_weakened",
        "frame_register_changed",
        "func_became_inline",
        "func_contract_attribute_added",
        "func_contract_attribute_removed",
        "func_cv_changed",
        "func_deleted_elf_fallback",
        "func_deprecated_added",
        "func_deprecated_removed",
        "func_exception_spec_changed",
        "func_language_linkage_changed",
        "func_likely_renamed",
        "func_lost_inline",
        "func_noexcept_added",
        "func_noexcept_removed",
        "func_override_specifier_added",
        "func_override_specifier_removed",
        "func_pure_virtual_added",
        "func_ref_qual_changed",
        "func_static_changed",
        "func_variadic_added",
        "func_variadic_removed",
        "func_virtual_added",
        "func_virtual_became_pure",
        "func_virtual_removed",
        "func_visibility_changed",
        "func_visibility_protected_changed",
        "generated_file_dependency_unstable",
        "generated_header_changed",
        "generated_header_reaches_public_api",
        "glibcxx_dual_abi_flip_detected",
        "handle_type_changed",
        "hash_style_removed",
        "header_build_context_mismatch",
        "header_parse_context_drift",
        "hidden_friend_added",
        "hidden_friend_removed",
        "identity_collision_detected",
        "ifunc_introduced",
        "ifunc_removed",
        "imported_symbol_added",
        "imported_symbol_removed",
        "include_graph_public_header_drift",
        "inline_body_changed",
        "inline_body_references_renamed_member",
        "inline_function_removed",
        "inline_namespace_moved",
        "inline_namespace_version_bumped",
        "instantiation_missing_from_binary",
        "integer_model_changed",
        "internal_symbol_required_by_public_api",
        "internal_template_leaks_via_public_api",
        "internal_type_leaks_via_public_api",
        "interpreter_changed",
        "kabi_crc_changed",
        "kabi_export_type_changed",
        "kabi_symbol_added",
        "kabi_symbol_namespace_changed",
        "kabi_symbol_removed",
        "layer_coverage_asymmetric",
        "layout_unverifiable",
        "libcpp_abi_version_changed",
        "library_version_downgraded",
        "link_export_policy_changed",
        "long_double_abi_changed",
        "lto_mode_changed",
        "macho_cpu_type_changed",
        "macho_filetype_changed",
        "macho_linkage_flags_changed",
        "macho_reexport_changed",
        "macos_deployment_target_raised",
        "mandatory_template_param_added",
        "method_access_changed",
        "musllinux_glibc_dependency_detected",
        "needed_added",
        "needed_order_changed",
        "needed_removed",
        "numpy_abi_major_incompatible",
        "numpy_capi_consumption_added",
        "numpy_capi_consumption_removed",
        "numpy_metadata_understates_required_version",
        "numpy_target_floor_raised",
        "odr_source_conflict",
        "odr_type_variant",
        "opaque_invariant_broken",
        "os_deployment_floor_raised",
        "overload_added",
        "overload_set_rerouted",
        "param_became_va_list",
        "param_default_value_changed",
        "param_default_value_removed",
        "param_lost_va_list",
        "param_pointer_level_changed",
        "param_renamed",
        "param_restrict_changed",
        "pe_forwarder_changed",
        "pe_hardening_improved",
        "pe_hardening_weakened",
        "pe_import_load_mode_changed",
        "pe_machine_changed",
        "pe_ordinal_retargeted",
        "pie_disabled",
        "platform_baseline_floor_raised",
        "polymorphic_type_non_virtual_dtor",
        "private_header_leak",
        "protected_visibility_changed",
        "public_api_exposes_stl_by_value",
        "public_api_internal_dependency_added",
        "public_macro_removed",
        "public_macro_value_changed",
        "public_not_exported",
        "public_reachability_changed",
        "public_surface_grew",
        "public_surface_shrank",
        "public_to_internal_dependency",
        "public_typedef_removed",
        "public_typedef_target_changed",
        "python_abi3_dropped",
        "python_abi3_floor_raised",
        "python_api_callable_kind_changed",
        "python_api_class_added",
        "python_api_class_removed",
        "python_api_default_removed",
        "python_api_function_added",
        "python_api_function_removed",
        "python_api_method_added",
        "python_api_method_removed",
        "python_api_overload_removed",
        "python_api_parameter_added",
        "python_api_parameter_kind_changed",
        "python_api_parameter_removed",
        "python_api_parameter_renamed",
        "python_api_parameter_type_changed",
        "python_api_return_type_changed",
        "python_api_stub_invalid",
        "python_gil_abi_changed",
        "python_stable_abi_violation",
        "relro_weakened",
        "removed_const_overload",
        "return_pointer_level_changed",
        "rpath_changed",
        "rpath_type_changed",
        "rtti_for_internal_type",
        "rtti_inheritance_changed",
        "rtti_mode_changed",
        "runpath_changed",
        "runtime_floor_raised",
        "runtime_symbol_provider_changed",
        "runtime_weak_resolution_changed",
        "sanitizer_mode_changed",
        "secondary_vtable_group_changed",
        "serialization_tag_changed",
        "soname_bump_recommended",
        "soname_bump_unnecessary",
        "soname_changed",
        "soname_missing",
        "source_binary_provenance_mismatch",
        "source_decl_binary_symbol_mismatch",
        "source_fact_coverage_incomplete",
        "source_level_kind_changed",
        "source_surface_dso_mismatch",
        "source_to_binary_mapping_changed",
        "stack_canary_removed",
        "standard_layout_lost",
        "static_tls_introduced",
        "static_tls_removed",
        "std_reexport_removed",
        "stdlib_debug_mode_changed",
        "stdlib_implementation_changed",
        "struct_field_offset_changed",
        "struct_field_removed",
        "struct_packing_changed",
        "struct_packing_mode_changed",
        "struct_return_convention_changed",
        "suppression_reachability_unknown",
        "suppression_would_hide_public_break",
        "sycl_backend_driver_req_changed",
        "sycl_implementation_changed",
        "sycl_overload_set_removed",
        "sycl_pi_entrypoint_added",
        "sycl_pi_entrypoint_removed",
        "sycl_pi_version_changed",
        "sycl_plugin_added",
        "sycl_plugin_removed",
        "sycl_plugin_search_path_changed",
        "sycl_runtime_version_changed",
        "symbol_binding_became_unique",
        "symbol_binding_changed",
        "symbol_binding_lost_unique",
        "symbol_binding_strengthened",
        "symbol_elf_visibility_changed",
        "symbol_leaked_from_dependency_changed",
        "symbol_moved_version_node",
        "symbol_renamed_batch",
        "symbol_size_changed",
        "symbol_size_changed_const_object",
        "symbol_size_changed_internal",
        "symbol_type_changed",
        "symbol_version_alias_changed",
        "symbol_version_defined_added",
        "symbol_version_required_added",
        "symbol_version_required_added_compat",
        "symbol_version_required_removed",
        "symbolic_binding_mode_changed",
        "tag_type_renamed",
        "tail_padding_reuse_changed",
        "target_dependency_added",
        "template_body_changed",
        "text_relocation_introduced",
        "text_relocation_removed",
        "threadsafe_statics_mode_changed",
        "time64_abi_changed",
        "tls_model_changed",
        "tls_var_size_changed",
        "toolchain_flag_drift",
        "toolchain_version_changed",
        "trivially_copyable_lost",
        "type_added",
        "type_base_changed",
        "type_became_abstract",
        "type_became_final",
        "type_became_opaque",
        "type_deprecated_added",
        "type_deprecated_removed",
        "type_field_added",
        "type_field_added_compatible",
        "type_field_offset_changed",
        "type_field_removed",
        "type_kind_changed",
        "type_lost_abstract",
        "type_lost_final",
        "type_removed",
        "type_visibility_changed",
        "type_vtable_changed",
        "typedef_removed",
        "typedef_version_sentinel",
        "undocumented_export_ratio_increased",
        "uninstantiated_template_removed",
        "union_field_added",
        "union_field_removed",
        "unnamed_type_in_public_abi",
        "unspecified_return_now_named",
        "unversioned_exported_symbol",
        "used_reserved_field",
        "value_abi_trait_changed",
        "var_access_changed",
        "var_access_widened",
        "var_alignment_changed",
        "var_became_const",
        "var_deprecated_added",
        "var_deprecated_removed",
        "var_lost_const",
        "var_value_changed",
        "vector_abi_changed",
        "version_script_missing",
        "versioned_symbol_scheme_detected",
        "virtual_base_offset_changed",
        "virtual_method_added",
        "visibility_leak",
        "vptr_introduced",
        "vtable_slot_count_changed",
        "vtable_symbol_identity_changed",
        "vtable_thunk_offset_changed",
        "vtable_thunk_set_changed",
        "vtt_slot_count_changed",
        "wchar_model_changed",
        "wheel_closure_dependency_violation",
        "wheel_rpath_not_portable",
        "wheel_tag_architecture_mismatch",
        "whole_program_vtables_mode_changed",
        "writable_executable_segment",
        "x86_isa_baseline_raised",
    }
)

#: The partition the completeness test enforces.
ALL_BUCKETS = {
    "TYPE_BEARING": TYPE_BEARING,
    "VALUE_INSENSITIVE": VALUE_INSENSITIVE,
    "UNVERIFIED": UNVERIFIED,
}
