# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated Python API reference stays in sync with
abicheck.service.__all__ -- mirrors scripts/gen_action_reference.py's own
test_action_reference.py pattern."""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_python_api_reference.py"
    spec = importlib.util.spec_from_file_location("gen_python_api_reference", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generated_reference_is_in_sync_with_service_all():
    gen = _load_gen()
    expected = gen.render()
    actual = gen.OUT_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/python-api-reference.md is stale -- regenerate with "
        "`python scripts/gen_python_api_reference.py`"
    )


def test_every_public_name_appears_in_generated_reference():
    from abicheck import service

    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    for name in service.__all__:
        assert f"`{name}`" in content, f"{name!r} missing from generated Python API reference"


def test_run_compare_return_annotation_appears_in_generated_reference():
    # A parameter table alone isn't a full signature reference -- a reader
    # still has to open the source to learn what a function returns without
    # this.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    section = content.split("## `run_compare`", 1)[1].split("## `run_compare_request`", 1)[0]
    assert "**Returns:** `CompareResult`" in section


def test_keyword_only_parameters_are_marked_in_generated_reference():
    # compare_snapshots only accepts old/new/suppression positionally --
    # `policy` and everything after it is keyword-only. A flat parameter
    # table with no marker makes `policy` look like the next positional
    # arg, and following that row order raises TypeError.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    section = content.split("## `compare_snapshots`", 1)[1].split("## `", 1)[0]
    before, after = section.split("*(keyword-only below)*", 1)
    assert "`suppression`" in before
    assert "`policy`" in after
    assert "`old`" in before
    assert "`old`" not in after


def test_private_underscore_parameters_are_excluded():
    # run_dump's `_skip_header_graph_attach` is documented in its own
    # docstring as a private, internal-only knob (not public API, not
    # CLI-reachable) used solely by run_dump's own hybrid-backend recursion
    # -- publishing it on the advertised public-API reference would invite
    # callers to depend on an implementation detail.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "_skip_header_graph_attach" not in content


def test_generated_reference_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_python_api_reference.py" in text.lower()
