# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The unrolled string/char-literal patterns match exactly what the
per-character alternation they replaced matched.

Oracle: the original spelling, compiled here -- never the production
pattern. Checked over generated byte strings drawn from the characters that
decide a literal's extent (both quotes, backslash, newline) plus ordinary
text, comparing every match span, and over the real ``sub`` each caller
performs.
"""

from __future__ import annotations

import re

import pytest
from hypothesis import given, settings, strategies as st

from abicheck import dumper_ast_config_cpp20
from abicheck.extract import cpp20_header_prep

_ORACLES = {
    "joined-string": (
        cpp20_header_prep._JOINED_STRING_LITERAL_PATTERN,
        re.compile(rb'"(?:\\.|[^"\\])*"', re.DOTALL),
    ),
    "joined-char": (
        cpp20_header_prep._JOINED_CHAR_LITERAL_PATTERN,
        re.compile(rb"'(?:\\.|[^'\\])*'", re.DOTALL),
    ),
    "line-string": (
        dumper_ast_config_cpp20._STRING_LITERAL_PATTERN,
        re.compile(rb'"(?:\\.|[^"\\\n])*"'),
    ),
    "line-char": (
        dumper_ast_config_cpp20._CHAR_LITERAL_PATTERN,
        re.compile(rb"'(?:\\.|[^'\\\n])*'"),
    ),
}

_text = st.lists(
    st.sampled_from([b'"', b"'", b"\\", b"\n", b"a", b" ", b"*", b"/", b"\\\n"]),
    max_size=40,
).map(b"".join)


@pytest.mark.parametrize("name", sorted(_ORACLES))
@settings(max_examples=400, deadline=None)
@given(text=_text)
def test_unrolled_pattern_matches_the_original_spans(name: str, text: bytes) -> None:
    new, old = _ORACLES[name]
    assert [m.span() for m in new.finditer(text)] == [
        m.span() for m in old.finditer(text)
    ]


def test_generator_reaches_escapes_and_multi_line_literals() -> None:
    """Vacuity guard: the domain above really contains the hard cases."""
    new, old = _ORACLES["joined-string"]
    for text in (b'"a\\"b"', b'"a\\\nb"', b'"\\\\"', b"'\\''"):
        assert [m.span() for m in new.finditer(text)] == [
            m.span() for m in old.finditer(text)
        ]
    assert new.fullmatch(b'"a\\\nb"') is not None  # crosses a continuation


def test_real_strip_is_unchanged_on_a_mixed_header() -> None:
    header = (
        b'const char* s = "a \\"quoted\\" // not a comment";\n'
        b"char c = '\\'';\n"
        b'const char* m = "line one \\\n line two";\n'
        b"struct concept {};\n"
    )
    new, old = _ORACLES["joined-string"]
    assert new.sub(b'""', header) == old.sub(b'""', header)
    stripped = cpp20_header_prep._strip_literals_crossing_continuations(header)
    assert b"struct concept {};" in stripped and b"quoted" not in stripped
    assert stripped.count(b"\n") == header.count(b"\n")
