# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated GitHub Action inputs/outputs reference stays in sync with
action.yml -- mirrors scripts/gen_detector_spec.py's own test_detector_spec.py
pattern so drift fails the ordinary fast pytest lane, not just a --check
someone has to remember to run."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import yaml

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_action_reference.py"
    spec = importlib.util.spec_from_file_location("gen_action_reference", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generated_reference_is_in_sync_with_action_yml():
    gen = _load_gen()
    action = yaml.safe_load(gen.ACTION_YML.read_text(encoding="utf-8"))
    expected = gen.render(action)
    actual = gen.OUT_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/github-action-inputs.md is stale -- regenerate with "
        "`python scripts/gen_action_reference.py`"
    )


def test_every_action_input_and_output_appears_in_generated_reference():
    gen = _load_gen()
    action = yaml.safe_load(gen.ACTION_YML.read_text(encoding="utf-8"))
    input_rows, output_rows = gen.build_rows(action)
    assert {r["name"] for r in input_rows} == set(action["inputs"])
    assert {r["name"] for r in output_rows} == set(action["outputs"])


def test_clean_collapses_folded_scalar_and_escapes_pipes():
    gen = _load_gen()
    assert gen._clean("a\nb   c") == "a b c"
    assert gen._clean("has | a pipe") == "has \\| a pipe"
    assert gen._clean(None) == ""


def test_generated_reference_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_action_reference.py" in text.lower()
