# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated CLI reference stays in sync with the live Click command
tree -- mirrors scripts/gen_action_reference.py's own test_action_reference.py
pattern so drift fails the ordinary fast pytest lane."""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_cli_reference.py"
    spec = importlib.util.spec_from_file_location("gen_cli_reference", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generated_reference_is_in_sync_with_cli():
    gen = _load_gen()
    expected = gen.render()
    actual = gen.OUT_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/cli-reference.md is stale -- regenerate with "
        "`python scripts/gen_cli_reference.py`"
    )


def test_every_top_level_command_appears_in_generated_reference():
    from abicheck.cli import main

    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    for name in main.commands:
        assert f"`{name}`" in content, f"{name!r} missing from generated CLI reference"


def test_generated_reference_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_cli_reference.py" in text.lower()


def test_root_group_options_appear_in_generated_reference():
    # main (the root abicheck Click group) has its own --version option,
    # separate from any subcommand -- iterating only main.commands would
    # silently drop it from an "exhaustive" reference.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "## Root options" in content
    assert "`--version`" in content.split("## Root options", 1)[1].split("##", 1)[0]


def test_default_str_renders_a_path_default_platform_independently():
    gen = _load_gen()
    from pathlib import PurePosixPath, PureWindowsPath

    # str(Path("/")) renders "/" on POSIX but "\\" on Windows -- a generated
    # reference must not change depending on which OS regenerated it, so any
    # Path-typed default is rendered via as_posix() regardless of host OS.
    assert gen._default_str(PurePosixPath("/")) == "/"
    assert gen._default_str(PureWindowsPath("/")) == "/"
    assert gen._default_str("plain-string") == "plain-string"


def test_option_row_includes_secondary_opts_for_a_boolean_flag_pair():
    gen = _load_gen()

    class _FakeParam:
        opts = ["--demangle"]
        secondary_opts = ["--no-demangle"]
        default = None
        required = False
        help = "Demangle names."
        type = None

    row = gen._option_row(_FakeParam())
    assert "`--demangle`" in row
    assert "`--no-demangle`" in row
    assert row.startswith("| `--demangle`, `--no-demangle` |")


def test_option_row_hides_click_internal_unset_sentinel():
    gen = _load_gen()

    class _FakeSentinel:
        pass

    _FakeSentinel.__name__ = "Sentinel"

    class _FakeParam:
        opts = ["--expect"]
        default = _FakeSentinel()
        required = False
        help = "Some help text."
        type = None

    row = gen._option_row(_FakeParam())
    assert "Sentinel" not in row
    assert "| `--expect` | no | — | Some help text. |" == row
