# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""docs/contribute/catalog-coverage.md (Phase 6 of the examples/catalog
split, docs/contribute/plans/examples-catalog-split.md) stays in sync with
scripts/gen_catalog_coverage_report.py -- mirrors test_detector_spec.py's
own drift-gate pattern so staleness fails the ordinary fast pytest lane,
not just a --check someone has to remember to run."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_catalog_coverage_report.py"
    spec = importlib.util.spec_from_file_location("gen_catalog_coverage_report", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(REPO_DIR / "scripts"))
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.path.remove(str(REPO_DIR / "scripts"))
    return mod


def test_generated_page_is_in_sync():
    gen = _load_gen()
    current = gen.OUT_PATH.read_text(encoding="utf-8")
    assert current == gen.render(), (
        "docs/contribute/catalog-coverage.md is stale -- regenerate with "
        "`python scripts/gen_catalog_coverage_report.py`"
    )


def test_rule_count_matches_taxonomy_directly():
    """Re-derive the headline rule/variant counts independently of the
    generator's own rendering, so a bug in `render()`'s prose can't hide a
    wrong count from the sync check above."""
    gen = _load_gen()
    gt = gen.example_catalog.load_ground_truth()
    taxonomy = gt["taxonomy"]

    rules = {k: v for k, v in taxonomy.items() if v["entity"] == "rule"}
    scenarios = {k: v for k, v in taxonomy.items() if v["entity"] == "scenario"}
    assert len(rules) + len(scenarios) == len(taxonomy)

    slugs = {v["rule_slug"] for v in rules.values()}
    assert None not in slugs, "every rule-entity case must carry a rule_slug"

    # A distinct rule also includes a scenario-only conceptual slug named in
    # related_rules with no rule-entity case of its own (e.g.
    # "overload-set-removed") -- counting only rule-entity slugs would
    # undercount the catalog's real rule vocabulary.
    scenario_only_slugs = {
        slug
        for entry in scenarios.values()
        for slug in (entry.get("related_rules") or [])
        if slug not in slugs
    }
    distinct_rule_count = len(slugs) + len(scenario_only_slugs)

    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert f"**{len(rules)} rule-entity cases**" in content
    assert f"**{distinct_rule_count} distinct compatibility rules**" in content
    assert f"**{len(scenarios)} scenario-entity cases**" in content


def test_every_taxonomy_entity_is_rule_or_scenario():
    gen = _load_gen()
    gt = gen.example_catalog.load_ground_truth()
    for case_id, entry in gt["taxonomy"].items():
        assert entry["entity"] in ("rule", "scenario"), (
            f"{case_id}: unexpected entity {entry['entity']!r} -- "
            "gen_catalog_coverage_report.py's dimension split assumes only "
            "these two entity kinds exist"
        )


def test_generated_marker_present():
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "GENERATED by scripts/gen_catalog_coverage_report.py" in content
