# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A streamed baseline is byte-identical to the eager one it replaced.

``save_bundle_facts``'s JSON path used to be
``json.dumps(bundle_facts_to_dict(facts), indent=2)``, which held every
member's snapshot dict, the whole string and its UTF-8 encoding at once. It
now streams. The published document is a persisted artifact other tools
read, and a digest is reported for it, so "smaller peak" is only acceptable
alongside "identical bytes" -- which is what these tests state, against the
eager spelling as the oracle rather than against a golden file that would
have been generated by the new code.
"""

from __future__ import annotations

import gzip
import json
from pathlib import Path

import pytest

from abicheck.model import AbiSnapshot, Function, Variable, Visibility
from abicheck.model.bundle_facts import BundleFacts
from abicheck.serialization import load_bundle_facts, save_bundle_facts
from abicheck.storage.bundle_facts_codec import (
    bundle_facts_document_stream,
    bundle_facts_to_dict,
)
from abicheck.storage.json_stream import join_json_indented


def _snapshot(name: str, functions: int) -> AbiSnapshot:
    return AbiSnapshot(
        library=name,
        version="1.0",
        functions=[
            Function(
                name=f"fn_{i}",
                mangled=f"_Z4fn_{i}v",
                return_type="int",
                params=[],
                visibility=Visibility.PUBLIC,
            )
            for i in range(functions)
        ],
        variables=[
            Variable(name=f"var_{i}", mangled=f"var_{i}", type="double")
            for i in range(functions // 4)
        ],
    )


def _facts(members: int, functions: int = 40) -> BundleFacts:
    return BundleFacts(
        per_library_snapshots={
            f"libmember{i}.so": _snapshot(f"libmember{i}.so", functions)
            for i in range(members)
        },
        library_filenames={
            f"libmember{i}.so": f"libmember{i}.so.1" for i in range(members)
        },
        degraded_members={"libmember0.so": "no debug info"} if members else {},
        inventory_complete=True,
    )


class TestByteIdentity:
    @pytest.mark.parametrize("members", [0, 1, 2, 6])
    def test_the_streamed_document_equals_the_eager_one(self, members: int) -> None:
        facts = _facts(members)
        eager = json.dumps(bundle_facts_to_dict(facts), indent=2)
        streamed = join_json_indented(bundle_facts_document_stream(facts))
        assert streamed == eager

    def test_the_written_file_equals_an_eager_write(self, tmp_path: Path) -> None:
        facts = _facts(3)
        written = tmp_path / "baseline.json"
        result = save_bundle_facts(facts, written)
        expected = json.dumps(bundle_facts_to_dict(facts), indent=2)
        assert written.read_text(encoding="utf-8") == expected
        # And the reported envelope figures describe those exact bytes.
        assert result.decoded_size_bytes == len(expected.encode("utf-8"))
        assert result.stored_size_bytes == written.stat().st_size
        import hashlib

        assert result.stored_sha256 == hashlib.sha256(written.read_bytes()).hexdigest()

    def test_member_order_is_the_captures_order_not_sorted(self) -> None:
        """Order is part of the document; streaming must not re-sort it."""
        facts = BundleFacts(
            per_library_snapshots={
                "zlib.so": _snapshot("zlib.so", 2),
                "alib.so": _snapshot("alib.so", 2),
            }
        )
        streamed = join_json_indented(bundle_facts_document_stream(facts))
        assert streamed.index('"zlib.so"') < streamed.index('"alib.so"')
        assert streamed == json.dumps(bundle_facts_to_dict(facts), indent=2)


class TestContractsPreserved:
    def test_it_round_trips(self, tmp_path: Path) -> None:
        facts = _facts(3)
        path = tmp_path / "baseline.json"
        save_bundle_facts(facts, path)
        reloaded = load_bundle_facts(path)
        assert set(reloaded.per_library_snapshots) == set(facts.per_library_snapshots)
        assert reloaded.inventory_complete is True
        assert reloaded.degraded_members == {"libmember0.so": "no debug info"}
        assert reloaded.library_filenames == facts.library_filenames

    def test_the_declared_schema_version_is_unchanged(self, tmp_path: Path) -> None:
        """Streaming must not change what the document claims to be.

        The version is derived from the blocks actually present, and the
        streamed builder reuses the eager builder for every field except
        the member map -- this pins that it did not accidentally derive the
        version from a members-less view.
        """
        facts = _facts(2)
        path = tmp_path / "baseline.json"
        save_bundle_facts(facts, path)
        doc = json.loads(path.read_text(encoding="utf-8"))
        assert doc["schema_version"] == bundle_facts_to_dict(facts)["schema_version"]
        assert doc["artifact_type"] == bundle_facts_to_dict(facts)["artifact_type"]

    def test_a_compressed_write_still_works_and_round_trips(
        self, tmp_path: Path
    ) -> None:
        """The delegating branch, exercised rather than assumed.

        A compressed write joins and hands off to the one-shot codec (see
        ``write_snapshot_text_stream``); that branch is the one a test is
        most likely to skip, and it is the one that would silently write a
        corrupt envelope if the join were wrong.
        """
        facts = _facts(2)
        path = tmp_path / "baseline.json.gz"
        save_bundle_facts(facts, path)
        assert gzip.decompress(path.read_bytes()).decode("utf-8") == json.dumps(
            bundle_facts_to_dict(facts), indent=2
        )
        assert set(load_bundle_facts(path).per_library_snapshots) == set(
            facts.per_library_snapshots
        )

    def test_an_atomic_write_leaves_no_temp_file_behind(self, tmp_path: Path) -> None:
        save_bundle_facts(_facts(2), tmp_path / "baseline.json")
        assert sorted(p.name for p in tmp_path.iterdir()) == ["baseline.json"]


class TestRetentionWhileEncoding:
    def test_one_member_document_is_built_at_a_time(self) -> None:
        """The saving itself, observed rather than inferred.

        ``snapshot_to_dict`` is wrapped to record, at each call, how many
        previously-produced member documents are still reachable. Under the
        eager builder every earlier member is retained; under the streamed
        one none is.
        """
        import gc
        import weakref

        import abicheck.storage.bundle_facts_codec as codec

        facts = _facts(5)
        alive: list[int] = []
        refs: list[weakref.ref] = []
        real = codec.bundle_facts_document_stream

        from abicheck import serialization

        original = serialization.snapshot_to_dict

        class _Doc(dict):
            """A weak-referenceable dict, so the produced value can be probed."""

        def _wrapped(snap: AbiSnapshot) -> dict:
            gc.collect()
            alive.append(sum(1 for r in refs if r() is not None))
            doc = _Doc(original(snap))
            refs.append(weakref.ref(doc))
            return doc

        serialization.snapshot_to_dict = _wrapped  # type: ignore[assignment]
        try:
            list(
                __import__(
                    "abicheck.storage.json_stream", fromlist=["iter_json_indented"]
                ).iter_json_indented(real(facts))
            )
        finally:
            serialization.snapshot_to_dict = original  # type: ignore[assignment]
        assert len(alive) == 5, "the probe never ran; the test proves nothing"
        assert alive == [0, 0, 0, 0, 0]
