# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated platform-capability matrix stays in sync with
scripts/platform_capabilities.py -- mirrors gen_action_reference.py's own
test_action_reference.py pattern so drift fails the ordinary fast pytest
lane, not just a --check someone has to remember to run."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_DIR = Path(__file__).resolve().parent.parent


def _load(name: str):
    path = REPO_DIR / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_gen():
    return _load("gen_platform_matrix")


def test_generated_matrix_is_in_sync_with_platform_capabilities():
    gen = _load_gen()
    current = gen.OUT_PATH.read_text(encoding="utf-8")
    expected = gen._splice(current, gen.render())
    assert current == expected, (
        "docs/reference/platforms.md's platform-matrix section is stale -- "
        "regenerate with `python scripts/gen_platform_matrix.py`"
    )


def test_generated_section_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_platform_matrix.py" in text.lower()


def test_every_binary_format_covers_all_three_hosts():
    caps = _load("platform_capabilities")
    for fmt in caps.PLATFORM_CAPABILITY_MATRIX:
        hosts = {h.host for h in fmt.hosts}
        assert hosts == {"linux", "macos", "windows"}, fmt.format_key


def test_every_binary_format_has_exactly_one_native_host():
    caps = _load("platform_capabilities")
    for fmt in caps.PLATFORM_CAPABILITY_MATRIX:
        natives = [h.host for h in fmt.hosts if h.native]
        assert len(natives) == 1, f"{fmt.format_key}: {natives}"


def test_native_host_is_a_real_platform_for_its_format():
    """Sanity: ELF's native host is Linux, PE's is Windows, Mach-O's is macOS."""
    caps = _load("platform_capabilities")
    expected_native = {"elf": "linux", "pe": "windows", "macho": "macos"}
    for fmt in caps.PLATFORM_CAPABILITY_MATRIX:
        native = next(h.host for h in fmt.hosts if h.native)
        assert native == expected_native[fmt.format_key]


def test_type_param_diff_implies_symbol_diff():
    caps = _load("platform_capabilities")
    for fmt in caps.PLATFORM_CAPABILITY_MATRIX:
        for h in fmt.hosts:
            if h.type_param_diff:
                assert h.symbol_diff, f"{fmt.format_key}/{h.host}"


def test_bad_host_capability_rejected():
    caps = _load("platform_capabilities")
    with pytest.raises(ValueError):
        caps.HostCapability("solaris", True, True, True, "—")


def test_format_matrix_requires_all_three_hosts():
    caps = _load("platform_capabilities")
    with pytest.raises(ValueError):
        caps.FormatMatrix(
            format_key="bogus",
            section_heading="x",
            hosts=(caps.HostCapability("linux", True, True, True, "—"),),
        )


def test_format_matrix_requires_exactly_one_native_host():
    caps = _load("platform_capabilities")
    with pytest.raises(ValueError):
        caps.FormatMatrix(
            format_key="bogus",
            section_heading="x",
            hosts=(
                caps.HostCapability("linux", True, True, True, "—"),
                caps.HostCapability("macos", True, True, True, "—"),
                caps.HostCapability("windows", False, True, False, "—"),
            ),
        )
