# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for scripts/gen_learning_ladder.py — render-and-drift only.

The committed hub must round-trip (`--check` clean), an edit inside a
generated block is drift (`--check` exits 1), a hub without its sentinels
is a hard error, and the rendered tables link every ladder page by the
hub-relative path.
"""

from __future__ import annotations

import importlib.util
import shutil
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
_SCRIPTS = _ROOT / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

_spec = importlib.util.spec_from_file_location(
    "gen_learning_ladder", _SCRIPTS / "gen_learning_ladder.py"
)
assert _spec and _spec.loader
gen = importlib.util.module_from_spec(_spec)
sys.modules["gen_learning_ladder"] = gen
_spec.loader.exec_module(gen)


def test_committed_hub_is_in_sync() -> None:
    assert gen.main(["--check"]) == 0


def _copy_docs(tmp_path: Path) -> Path:
    docs = tmp_path / "docs"
    shutil.copytree(_ROOT / "docs" / "learn", docs / "learn")
    shutil.copytree(_ROOT / "docs" / "_meta", docs / "_meta")
    for extra in ("use", "start"):
        shutil.copytree(_ROOT / "docs" / extra, docs / extra)
    return docs


def test_edit_inside_a_generated_block_is_drift(tmp_path: Path) -> None:
    docs = _copy_docs(tmp_path)
    hub = docs / "learn" / "abi-api-handling.md"
    text = hub.read_text(encoding="utf-8")
    marker = "<!-- BEGIN GENERATED: learning-ladder -->\n"
    hub.write_text(text.replace(marker, marker + "hand edit\n", 1), encoding="utf-8")
    ladder = docs / "_meta" / "learning-ladder.yaml"
    assert gen.main(["--check", "--docs", str(docs), "--ladder", str(ladder)]) == 1
    assert gen.main(["--docs", str(docs), "--ladder", str(ladder)]) == 0
    assert gen.main(["--check", "--docs", str(docs), "--ladder", str(ladder)]) == 0


def test_missing_sentinels_is_a_hard_error(tmp_path: Path) -> None:
    docs = _copy_docs(tmp_path)
    hub = docs / "learn" / "abi-api-handling.md"
    hub.write_text("# Hub without sentinels\n", encoding="utf-8")
    ladder = docs / "_meta" / "learning-ladder.yaml"
    with pytest.raises(ValueError, match="sentinels"):
        gen.main(["--check", "--docs", str(docs), "--ladder", str(ladder)])


def test_rendered_tables_link_every_ladder_page_and_every_path_role() -> None:
    ladder = gen.load_ladder(gen.LADDER_PATH)
    ladder_block = gen.render_ladder(ladder, gen.DOCS)
    paths_block = gen.render_paths(ladder, gen.DOCS)
    for page in ladder.index:
        assert f"]({gen.relative_href(ladder.hub, page)})" in ladder_block, page
    for rp in ladder.paths:
        assert f"| {rp.role} |" in paths_block
        for page in rp.pages:
            assert f"]({gen.relative_href(ladder.hub, page)})" in paths_block, page
    assert gen.GENERATED_NOTE in ladder_block and gen.GENERATED_NOTE in paths_block
    # the note must not read as a whole-page "generated by scripts/" marker,
    # which would exempt the hub from the docs contract's prose scans
    assert "generated by scripts/" not in gen.GENERATED_NOTE.lower()
