# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated CLI reference stays in sync with the live Click command
tree -- mirrors scripts/gen_action_reference.py's own test_action_reference.py
pattern so drift fails the ordinary fast pytest lane."""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_cli_reference.py"
    spec = importlib.util.spec_from_file_location("gen_cli_reference", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generated_reference_is_in_sync_with_cli():
    gen = _load_gen()
    expected = gen.render()
    actual = gen.OUT_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/cli-reference.md is stale -- regenerate with "
        "`python scripts/gen_cli_reference.py`"
    )


def test_every_top_level_command_appears_in_generated_reference():
    from abicheck.cli import main

    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    for name in main.commands:
        assert f"`{name}`" in content, f"{name!r} missing from generated CLI reference"


def test_generated_reference_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_cli_reference.py" in text.lower()


def test_optional_argument_is_marked_not_required():
    # dump's SO_PATH argument is optional (a source-only invocation needs no
    # binary) -- the Arguments table must distinguish it from a required
    # positional, not render every argument identically.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    section = content.split("## `dump`", 1)[1].split("## `project`", 1)[0]
    assert "| `so_path` | no |" in section


def test_root_group_options_appear_in_generated_reference():
    # main (the root abicheck Click group) has its own --version option,
    # separate from any subcommand -- iterating only main.commands would
    # silently drop it from an "exhaustive" reference.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "## Root options" in content
    assert "`--version`" in content.split("## Root options", 1)[1].split("##", 1)[0]


def test_default_str_renders_a_path_default_platform_independently():
    gen = _load_gen()
    from pathlib import PurePosixPath, PureWindowsPath

    # str(Path("/")) renders "/" on POSIX but "\\" on Windows -- a generated
    # reference must not change depending on which OS regenerated it, so any
    # Path-typed default is rendered via as_posix() regardless of host OS.
    assert gen._default_str(PurePosixPath("/")) == "/"
    assert gen._default_str(PureWindowsPath("/")) == "/"
    assert gen._default_str("plain-string") == "plain-string"


def test_option_row_includes_secondary_opts_for_a_boolean_flag_pair():
    gen = _load_gen()

    class _FakeParam:
        opts = ("--demangle",)
        secondary_opts = ("--no-demangle",)
        default = None
        required = False
        help = "Demangle names."
        type = None

    row = gen._option_row(_FakeParam())
    assert "`--demangle`" in row
    assert "`--no-demangle`" in row
    assert row.startswith("| `--demangle`, `--no-demangle` |")


def test_hidden_options_are_excluded_from_generated_reference():
    # --header-graph/--no-header-graph are deprecated, hidden, inert no-op
    # shims (abicheck/cli_options.py) -- Click itself omits them from
    # --help, so a reference that claims to mirror --help must omit them
    # too rather than publishing dead flags no user can discover.
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "--header-graph" not in content


def test_option_row_shows_a_real_false_default_not_a_blank():
    # A solo boolean flag defaulting to False has a real, meaningful default,
    # not "no default given". Rendering it as "—" (the same marker used for a
    # genuinely absent default) makes a disabled-by-default flag
    # indistinguishable from one with no default.
    gen = _load_gen()

    class _FakeParam:
        opts = ("--show-impact",)
        secondary_opts = ()
        default = False
        required = False
        help = "Show impact analysis."
        type = None

    row = gen._option_row(_FakeParam())
    assert "| `--show-impact` | no | `False` | Show impact analysis. |" == row


def test_option_row_hides_click_internal_unset_sentinel():
    gen = _load_gen()

    class _FakeSentinel:
        pass

    _FakeSentinel.__name__ = "Sentinel"

    class _FakeParam:
        opts = ("--manifest",)
        default = _FakeSentinel()
        required = False
        help = "Some help text."
        type = None

    row = gen._option_row(_FakeParam())
    assert "Sentinel" not in row
    assert "| `--manifest` | no | — | Some help text. |" == row


def test_option_row_resolves_a_bool_flags_unset_default_to_false():
    # Click >= 8.5 stores a boolean flag's *implicit* default as its UNSET
    # sentinel where earlier versions stored a literal False. Both mean the
    # same thing to a user -- the flag is off unless passed -- so the
    # rendered reference must not differ by which Click generated it, or the
    # committed file goes stale the moment CI resolves a newer Click.
    gen = _load_gen()

    class _FakeSentinel:
        pass

    _FakeSentinel.__name__ = "Sentinel"

    class _FakeParam:
        opts = ("--show-impact",)
        secondary_opts = ()
        default = _FakeSentinel()
        is_bool_flag = True
        required = False
        help = "Show impact analysis."
        type = None

    row = gen._option_row(_FakeParam())
    assert "| `--show-impact` | no | `False` | Show impact analysis. |" == row


def test_option_row_keeps_a_non_boolean_flags_unset_default_blank():
    # The sibling of the test above, and the reason `is_bool_flag` rather
    # than `is_flag` is the discriminator: Click sets `is_flag` for a
    # `flag_value=` option too, but that one really does resolve to None,
    # so rendering `False` for it would state a default the command never
    # sees.
    gen = _load_gen()

    class _FakeSentinel:
        pass

    _FakeSentinel.__name__ = "Sentinel"

    class _FakeParam:
        opts = ("--mode",)
        secondary_opts = ()
        default = _FakeSentinel()
        is_flag = True
        is_bool_flag = False
        required = False
        help = "Pick a mode."
        type = None

    row = gen._option_row(_FakeParam())
    assert "| `--mode` | no | — | Pick a mode. |" == row


def test_real_click_bool_flags_render_false_under_the_installed_click():
    # The two tests above pin the rule against a hand-built parameter; this
    # one asks the *installed* Click for its own representation, so the
    # invariant is checked against whatever version CI resolves rather than
    # against this file's idea of what Click stores.
    import click

    gen = _load_gen()

    @click.command()
    @click.option("--solo", is_flag=True, help="Solo flag.")
    @click.option("--pair/--no-pair", help="Flag pair.")
    @click.option("--valued", flag_value="x", help="Valued flag.")
    def _cmd() -> None:  # pragma: no cover - never invoked
        """Doc."""

    rows = {p.name: gen._option_row(p) for p in _cmd.params}
    assert rows["solo"].endswith("| no | `False` | Solo flag. |")
    assert rows["pair"].endswith("| no | `False` | Flag pair. |")
    assert rows["valued"].endswith("| no | — | Valued flag. |")


def test_a_repeatable_boolean_flag_keeps_its_empty_default():
    # Click 8.5 accepts `multiple=True` on a boolean flag and marks it
    # `is_bool_flag`, but it resolves to `()` rather than `False` -- so the
    # rule above has to exclude it, or the reference states a default the
    # command never receives. `()` is already rendered "—", the same as
    # `--many`'s (CodeRabbit review).
    import click

    gen = _load_gen()

    @click.command()
    @click.option("--rep", is_flag=True, multiple=True, help="Repeatable flag.")
    def _cmd() -> None:  # pragma: no cover - never invoked
        """Doc."""

    (param,) = _cmd.params
    assert gen._option_row(param).endswith("| no | — | Repeatable flag. |")
