# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The generated .abicheck.yml config-keys reference stays in sync with
BuildConfig's strict-schema registries -- mirrors
scripts/gen_action_reference.py's own test_action_reference.py pattern."""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent


def _load_gen():
    path = REPO_DIR / "scripts" / "gen_config_reference.py"
    spec = importlib.util.spec_from_file_location("gen_config_reference", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generated_reference_is_in_sync_with_build_config():
    gen = _load_gen()
    expected = gen.render()
    actual = gen.OUT_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/reference/config-keys-reference.md is stale -- regenerate with "
        "`python scripts/gen_config_reference.py`"
    )


def test_every_known_top_key_appears_in_generated_reference():
    from abicheck.buildsource.build_config import BuildConfig

    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    for key in BuildConfig._KNOWN_TOP_KEYS:
        # Blocks render as `key:` (a heading); scalar/other keys render bare.
        assert f"`{key}`" in content or f"`{key}:`" in content, (
            f"{key!r} missing from generated config reference"
        )


def test_every_block_subkey_has_a_resolved_type_or_is_flagged_unspecified():
    from abicheck.buildsource.build_config import (
        _BOOL_SUBKEYS,
        _LIST_SUBKEYS,
        _STR_SUBKEYS,
        BuildConfig,
    )

    gen = _load_gen()
    for block, subkeys in BuildConfig._KNOWN_BLOCK_KEYS.items():
        for subkey in subkeys:
            type_str = gen._subkey_type(block, subkey, _BOOL_SUBKEYS, _STR_SUBKEYS, _LIST_SUBKEYS)
            assert type_str in {"bool", "str", "list[str] (or a single str)", "unspecified"}


def test_other_recognized_keys_section_has_no_absolute_github_link():
    # abicheck/buildsource/CLAUDE.md lives outside docs/ and isn't part of
    # the published mkdocs site, so there's no relative site path to point
    # at -- a github.com/.../blob/main link would send a reader of an older
    # release or a fork to the current main branch instead of the version
    # they're reading (docs/AGENTS.md's relative-links convention).
    gen = _load_gen()
    content = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "github.com" not in content
    assert "abicheck/buildsource/CLAUDE.md" in content


def test_generated_reference_has_marker_comment():
    gen = _load_gen()
    text = gen.OUT_PATH.read_text(encoding="utf-8")
    assert "generated by scripts/gen_config_reference.py" in text.lower()
