# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""`action/cli-surface.txt` is a real derivation, and the shell really reads it.

ADR-070 D3 / plan Phase 3b. `action/validate-inputs.sh` runs before abicheck
is installed (deliberately -- it exists to fail fast), so it is the one Action
shell that cannot query the CLI and is permitted a committed generated
artifact. That makes it the one place where a snapshot still exists, so it gets
the checks a snapshot needs:

1. The committed file equals what the generator produces from the live
   ``click.Choice`` sets (this is also `scripts/verify.py`'s
   ``action-cli-surface`` step; asserted here too so a test run alone catches
   it).
2. The generator's ``--check`` mode actually fails on drift -- a ``--check``
   that cannot fail is the failure mode `AGENTS.md` warns about for gates.
3. **The shell's accept/reject behaviour matches the file**, which is the part
   a generator check cannot prove: a correct artifact nothing reads is worth
   nothing. Exercised by running the real script.
4. The error message lists the same set the check used, so a message cannot
   drift from the logic beside it -- the defect that produced this plan.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import click
import pytest
from _workflow_exec import bash_executable, require_bash

REPO_ROOT = Path(__file__).resolve().parents[1]
SURFACE = REPO_ROOT / "action" / "cli-surface.txt"
VALIDATE = REPO_ROOT / "action" / "validate-inputs.sh"
GENERATOR = REPO_ROOT / "scripts" / "gen_action_cli_surface.py"


def _surface_lines() -> set[str]:
    return {
        line
        for line in SURFACE.read_text(encoding="utf-8").splitlines()
        if line.startswith("CHOICE ")
    }


def _click_choices(path: tuple[str, ...], spelling: str) -> tuple[str, ...]:
    """The declared value set behind *spelling*, read off the real command.

    Two shapes, because the CLI has two: an ordinary ``click.Choice`` type
    (``dump --compression``), and -- since plan slice 7m -- the renderable
    format set published on the ``-o FORMAT=DESTINATION`` parameter, whose
    *value* is the whole operand rather than a bare choice. Both are real,
    declared facts; the generator derives from whichever the option has, so
    this oracle reads whichever the option has too (ADR-070 D3: the artifact
    is derived, never a hand-maintained mirror).
    """
    from abicheck.cli import main

    node: click.Command = main
    for segment in path:
        node = node.commands[segment]  # type: ignore[attr-defined]
    for param in node.params:
        if isinstance(param, click.Option) and spelling in param.opts:
            choices = getattr(param.type, "choices", None)
            if choices:
                return tuple(choices)
            export_formats = getattr(param, "export_formats", None)
            if export_formats:
                return tuple(export_formats)
            raise AssertionError(
                f"{' '.join(path)} {spelling} declares no value set"
            )
    raise AssertionError(f"{' '.join(path)} has no {spelling}")


def _run_validate(env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    """Run the real validate-inputs.sh with a minimal environment."""
    require_bash()
    base = {"PATH": os.environ["PATH"]}
    base.update(env)
    return subprocess.run(
        [bash_executable(), str(VALIDATE)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=base,
        cwd=REPO_ROOT,
    )


@pytest.mark.skipif(not SURFACE.is_file(), reason="cli-surface.txt not generated")
class TestTheArtifactIsDerived:
    def test_it_carries_its_generated_marker(self) -> None:
        """The `generated-file-ownership` gate enforces this too; asserted
        here so the file cannot lose its "don't hand-edit" notice quietly."""
        head = SURFACE.read_text(encoding="utf-8").splitlines()[0]
        assert "generated by scripts/gen_action_cli_surface.py" in head

    @pytest.mark.parametrize(
        ("label", "path", "spelling"),
        [
            ("compare", ("compare",), "-o"),
            ("deps-tree", ("deps", "tree"), "-o"),
            ("deps-compare", ("deps", "compare"), "-o"),
            ("dump", ("dump",), "--compression"),
        ],
    )
    def test_each_emitted_set_equals_clicks_own(
        self, label: str, path: tuple[str, ...], spelling: str
    ) -> None:
        expected = {
            f"CHOICE {label} {spelling} {v}" for v in _click_choices(path, spelling)
        }
        actual = {
            line
            for line in _surface_lines()
            if line.startswith(f"CHOICE {label} {spelling} ")
        }
        assert actual == expected

    def test_check_mode_passes_on_the_committed_file(self) -> None:
        result = subprocess.run(
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        assert result.returncode == 0, result.stderr

    def test_check_mode_fails_on_drift(self, tmp_path: Path) -> None:
        """A `--check` that cannot fail gates nothing. Proven by corrupting a
        copy of the artifact and restoring it, rather than by trusting the
        code path."""
        original = SURFACE.read_text(encoding="utf-8")
        SURFACE.write_text(
            original + "CHOICE compare --format invented\n", encoding="utf-8"
        )
        try:
            result = subprocess.run(
                [sys.executable, str(GENERATOR), "--check"],
                capture_output=True,
                text=True,
                cwd=REPO_ROOT,
            )
            assert result.returncode == 1
            assert "stale" in result.stderr
            assert "- CHOICE compare --format invented" in result.stderr
        finally:
            SURFACE.write_text(original, encoding="utf-8")

    def test_no_per_shape_subset_is_emitted(self) -> None:
        """Scope guard. `validate-inputs.sh` also enforces narrower format sets
        for a directory/package compare and for `--no-baseline`. Those are
        claims about which renderer a comparison *shape* supports -- ADR-070
        D1/D2 restriction mirrors, not choice sets -- and emitting them here
        would dress a mirror up as a derived fact. If a future change wants
        them derived, that is Phase 2 and needs the mirrors resolved first."""
        labels = {line.split()[1] for line in _surface_lines()}
        assert labels == {"compare", "deps-tree", "deps-compare", "dump"}


@pytest.mark.skipif(not VALIDATE.is_file(), reason="validate-inputs.sh not found")
class TestTheShellActuallyReadsIt:
    """A correct artifact nothing consults is worth nothing, so these drive the
    real script rather than inspecting its source."""

    def test_every_emitted_compare_format_is_accepted(self) -> None:
        for value in _click_choices(("compare",), "-o"):
            result = _run_validate(
                {
                    "INPUT_MODE": "compare",
                    "INPUT_OLD_LIBRARY": "old.so",
                    "INPUT_NEW_LIBRARY": "new.so",
                    "INPUT_FORMAT": value,
                }
            )
            assert "does not support format" not in result.stdout, (
                f"compare rejected its own --format choice {value!r}: {result.stdout}"
            )

    def test_an_unknown_format_is_rejected(self) -> None:
        result = _run_validate(
            {
                "INPUT_MODE": "compare",
                "INPUT_OLD_LIBRARY": "old.so",
                "INPUT_NEW_LIBRARY": "new.so",
                "INPUT_FORMAT": "not-a-format",
            }
        )
        assert result.returncode != 0
        assert "does not support format: not-a-format" in result.stdout

    def test_a_format_valid_elsewhere_is_rejected_for_deps(self) -> None:
        """`sarif` is a real `compare` choice and not a `deps` one -- so this
        also proves the lookup is keyed per mode, not a flat union."""
        result = _run_validate(
            {
                "INPUT_MODE": "deps-tree",
                "INPUT_NEW_LIBRARY": "x.so",
                "INPUT_FORMAT": "sarif",
            }
        )
        assert result.returncode != 0
        assert "does not support format: sarif" in result.stdout

    def test_the_message_lists_the_same_set_the_check_used(self) -> None:
        """The original defect in this whole area was a message naming a
        different set than the code enforced. Both now come from one file."""
        result = _run_validate(
            {
                "INPUT_MODE": "deps-tree",
                "INPUT_NEW_LIBRARY": "x.so",
                "INPUT_FORMAT": "nope",
            }
        )
        for value in _click_choices(("deps", "tree"), "-o"):
            assert value in result.stdout
        assert "sarif" not in result.stdout

    def test_compression_choices_are_read_from_the_artifact(self) -> None:
        for value in _click_choices(("dump",), "--compression"):
            result = _run_validate(
                {
                    "INPUT_MODE": "dump",
                    "INPUT_NEW_LIBRARY": "x.so",
                    "INPUT_SNAPSHOT_COMPRESSION": value,
                }
            )
            assert "is not recognized" not in result.stdout, result.stdout
        bad = _run_validate(
            {
                "INPUT_MODE": "dump",
                "INPUT_NEW_LIBRARY": "x.so",
                "INPUT_SNAPSHOT_COMPRESSION": "brotli",
            }
        )
        assert bad.returncode != 0
        assert "is not recognized" in bad.stdout

    def test_a_missing_artifact_fails_loudly_rather_than_accepting_anything(
        self, tmp_path: Path
    ) -> None:
        """The packaging-mistake case. Treating an unreadable surface file as
        "accept everything" would turn a broken Action into silently skipped
        validation -- the exact class this ADR exists to remove."""
        require_bash()
        staged = tmp_path / "validate-inputs.sh"
        staged.write_text(VALIDATE.read_text(encoding="utf-8"), encoding="utf-8")
        result = subprocess.run(
            [bash_executable(), str(staged)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            env={
                "PATH": os.environ["PATH"],
                "INPUT_MODE": "compare",
                "INPUT_OLD_LIBRARY": "old.so",
                "INPUT_NEW_LIBRARY": "new.so",
                "INPUT_FORMAT": "json",
            },
            cwd=REPO_ROOT,
        )
        assert result.returncode != 0
        assert "cli-surface.txt" in result.stdout
