cc_library(
    name = "kv_headers",
    hdrs = glob(["include/kv/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "libkv.so",
    srcs = ["src/kv.cc"],
    deps = [":kv_headers"],
    linkshared = True,
    visibility = ["//visibility:public"],
)
