# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""ADR-068 D5 per-option rulings for ``aggregate``, ``project`` and ``deps``.

One-comparison-product Phase 7 slice 7s. The same three guards as
``rulings.py``'s ``compare``/``dump`` tables apply -- these are advanced,
opt-in commands (ADR-054), not exempt ones. Kept in a sibling module only for
file size; ``rulings.RULINGS_BY_COMMAND`` is still the one registry, keyed by
the command's path below the root (``"project plan"``).
"""

from __future__ import annotations

from .ruling_model import OptionRuling, _keep

_EXPORT_RULING = (
    "Plan slice 7m's one export request (`-o FORMAT=DESTINATION`, "
    "repeatable, `-` for stdout) -- the same grammar every report-rendering "
    "command shares, so it is not a second spelling of anything. Where this "
    "invocation's report goes is per-run by construction."
)
_VERBOSE_RULING = (
    "Same ruling as `compare --verbose`: per-run diagnostic verbosity on "
    "stderr, changing no recorded fact or exit code."
)
_TOOLCHAIN_BINDINGS_RULING = (
    "A trust-boundary operand, which is exactly why it cannot become a "
    "config key: the bindings file maps declared compiler bindings to "
    "executables this run will probe, and `ProfileCompileSpec.binding` "
    "documents that it is loaded ONLY from an explicit path, never "
    "auto-discovered. A `.abicheck.yml` key would let the (untrusted, "
    "possibly PR-controlled) project config this command reads choose which "
    "executables get run. Not an analysis-disabling hatch: supplying it adds "
    "checks, omitting it runs none of them."
)

AGGREGATE_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--manifest": _keep(
        "The expected-target set this matrix was supposed to produce -- the "
        "per-run inventory the coverage gate is judged against, generated by "
        "the same plan job that fanned out the matrix. Phase 7q folded "
        "--run-plan into it (both shapes classified by content, never by "
        "filename), so it is the one spelling of that operand."
    ),
    "--discovered-only": _keep(
        "Phase 7q ruled this stays explicit, and it is not an "
        "analysis-disabling hatch: without a declared target set the "
        "coverage gate has nothing to judge a missing report against, so "
        "there is no gate to disable. What the flag does is make that "
        "absence a stated choice rather than something inferred from an "
        "absent or empty manifest (ADR-065: absent is not removed, and a run "
        "never reads as complete by default). No document can say 'I have no "
        "expected inventory' on the operator's behalf."
    ),
    "--analysis-context": _keep(
        "ADR-073. Names WHICH revision this run analysed -- on a pull-request "
        "build an ephemeral merge commit no API endpoint names -- so a "
        "trusted publisher can verify it. Differs on every run by "
        "construction, which is guard 1 exactly; and it is a claim that is "
        "shape-validated and later verified, so a project-config home would "
        "be both stale and the wrong trust domain."
    ),
    "--output": _keep(_EXPORT_RULING),
    "--verbose": _keep(_VERBOSE_RULING),
}

PROJECT_VALIDATE_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--toolchain-bindings": _keep(_TOOLCHAIN_BINDINGS_RULING),
    "--output": _keep(_EXPORT_RULING),
    "--verbose": _keep(_VERBOSE_RULING),
}

PROJECT_PLAN_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--build-output": _keep(
        "Where each contract profile's abicheck-build/ directory landed in "
        "*this* CI run (`PROFILE=DIR`, repeatable) -- build output locations "
        "are produced per run, so the config names the profiles and this "
        "operand says where their outputs are. Not a second spelling of the "
        "config's `checks:`, which declares what to check, not where a "
        "particular run's artifacts sit."
    ),
    "--project": _keep(
        "Run provenance stamped into run-plan.json beside --head-sha: the "
        "repository identity the CI runtime reports for this run "
        "(`github.repository` in check-project.yml/check-target). Supplied by "
        "the runner rather than the project config because a config is "
        "copied with the repository -- into forks and mirrors -- and would "
        "then stamp the wrong identity; the runtime's value is the one "
        "describing where this plan was generated."
    ),
    "--head-sha": _keep(
        "The candidate commit this plan was generated for -- differs on "
        "every run by construction (guard 1), and recorded verbatim in "
        "run-plan.json so every matrix cell and the aggregate gate agree on "
        "which revision they describe."
    ),
    "--toolchain-bindings": _keep(_TOOLCHAIN_BINDINGS_RULING),
    "--output": _keep(_EXPORT_RULING),
    "--verbose": _keep(_VERBOSE_RULING),
}

PROJECT_HISTORY_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--version": _keep(
        "Same ruling as `dump --version`: labels *these* operands. Repeatable "
        "one-per-SNAPSHOT, because a history chain's release labels are a "
        "property of the snapshots this invocation was handed, not of the "
        "project; omitting it falls back to each snapshot's own recorded "
        "version rather than to any config value."
    ),
    "--policy": _keep(
        "Same ruling as `compare --policy` -- a document operand naming the "
        "policy every pairwise step of this chain is judged under, so that "
        "`project history` and `compare` judge a pair identically."
    ),
    "--output": _keep(_EXPORT_RULING),
    "--verbose": _keep(_VERBOSE_RULING),
}

PROJECT_CAPTURE_VARIANTS_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--variant": _keep(
        "Where this run's build of declared variant NAME is (`NAME=PATH`, "
        "repeatable). The variant *declarations* already live in config "
        "(`bundle_variants:`) and are not restated here -- this operand only "
        "binds a declared name to the artifacts one build produced, which "
        "differ on every capture."
    ),
    "--package": _keep(
        "The ProjectSnapshot package this capture writes -- the command's "
        "output artifact, per-run by construction (the same class as "
        "`dump --output`), and not an export format: a package is a "
        "directory of stored evidence, not a rendering of a report."
    ),
    "--config": _keep(
        "Same ruling as `compare --config`: names which project config "
        "declares the variants, defaulting to the nearest one. A config "
        "cannot name itself, so this cannot be demoted into one."
    ),
    "--variant-header": _keep(
        "Variant NAME's header evidence for this capture -- the "
        "`compare --header old=|new=` ruling with variant names in place of "
        "sides. Header locations follow the build tree each variant was "
        "produced in, so they are per-run paths, not project properties."
    ),
    "--variant-include": _keep(
        "The include-directory companion to --variant-header, per-run for "
        "the same reason: it locates variant NAME's build-tree includes for "
        "this capture's header parse."
    ),
    "--dry-run": _keep(
        "Same ruling as `compare --dry-run` (ADR-043 D9): resolve and check "
        "the capture plan -- every required variant reachable, every input "
        "discoverable -- without capturing or writing."
    ),
    "--output": _keep(_EXPORT_RULING),
}


_ENVIRONMENT_OPERAND = (
    "§4.3's ruling for `deps`: the environment *is* the operand here -- "
    "this command's whole question is whether a binary loads and links in "
    "a given filesystem/loader environment, so which environment is the "
    "per-run input, not a toolchain or project property. "
)

DEPS_TREE_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--search-path": _keep(
        _ENVIRONMENT_OPERAND + "Distinct from --ld-library-path for the "
        "loader-step reason 7k measured on `compare --search-path`."
    ),
    "--sysroot": _keep(
        _ENVIRONMENT_OPERAND + "The root the walk resolves every path "
        "against; unlike the retired `compile.sysroot` CLI twin (7b) it "
        "selects the analysed environment rather than a header-parse setting."
    ),
    "--ld-library-path": _keep(
        _ENVIRONMENT_OPERAND + "Simulates the loader variable for this run; "
        "see --search-path for why the two stay distinct."
    ),
    "--output": _keep(_EXPORT_RULING),
    "--dry-run": _keep(
        "Same ruling as `compare --dry-run` (ADR-043 D9): show the resolved "
        "binary, sysroot, search order and loader inputs without walking."
    ),
    "--verbose": _keep(_VERBOSE_RULING),
}

DEPS_COMPARE_OPTION_RULINGS: dict[str, OptionRuling] = {
    "--old-root": _keep(
        _ENVIRONMENT_OPERAND + "The baseline environment of the two this "
        "invocation compares."
    ),
    "--new-root": _keep(
        _ENVIRONMENT_OPERAND + "The candidate environment of the two this "
        "invocation compares."
    ),
    "--search-path": DEPS_TREE_OPTION_RULINGS["--search-path"],
    "--ld-library-path": DEPS_TREE_OPTION_RULINGS["--ld-library-path"],
    "--output": _keep(_EXPORT_RULING),
    "--dry-run": _keep(
        "Same ruling as `compare --dry-run` (ADR-043 D9): show both roots, "
        "resolved binary paths and search order without running the "
        "per-library ABI diffs."
    ),
    "--verbose": _keep(_VERBOSE_RULING),
}
