#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_fact_capability_matrix.py — the fact/capability registry doc
(ADR-063 D7, Phase 5, docs/contribute/plans/one-semantic-pipeline.md).

Renders `abicheck/model/fact_registry.py`'s `FACT_REGISTRY` (every
converted `Fact[T]`-typed model field, its producing backends, and its
persisted/identity/comparable/suppressible/reportable flags) plus the
case-(a)/case-(b) eligible-but-unconverted inventory into
`docs/reference/fact-registry.md`, mirroring `gen_detector_spec.py`'s
fully-generated-page pattern (not `gen_backend_capability_matrix.py`'s
splice-into-hand-authored-page one — this page has no hand-authored
narrative of its own to preserve).

Usage:
    python scripts/gen_fact_capability_matrix.py            # write the file
    python scripts/gen_fact_capability_matrix.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_DIR))

from abicheck.model.fact_registry import (  # noqa: E402
    FACT_REGISTRY,
    KNOWN_UNCONVERTED_ELIGIBLE_FACTS,
    REFERENCE_FLAG_COVERAGE,
)

OUT_PATH = REPO_DIR / "docs" / "reference" / "fact-registry.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_fact_capability_matrix.py — do not edit "
    "by hand. Run `python scripts/gen_fact_capability_matrix.py` to "
    "regenerate. The data lives in abicheck/model/fact_registry.py. -->"
)


def _bool_cell(value: bool) -> str:
    return "✅" if value else "—"


def _render_registry_table() -> str:
    lines = [
        "| Fact | Value type | Producing backends | Lifecycle | Persisted | Identity | Comparable | Suppressible | Reportable |",
        "|------|------------|---------------------|-----------|:---------:|:--------:|:----------:|:------------:|:----------:|",
    ]
    for entry in sorted(FACT_REGISTRY.entries.values(), key=lambda e: e.id):
        backends = ", ".join(sorted(entry.producing_backends))
        lines.append(
            f"| `{entry.id}` | `{entry.value_type}` | {backends} | "
            f"{entry.lifecycle.value} | {_bool_cell(entry.persisted)} | "
            f"{_bool_cell(entry.identity_relevant)} | "
            f"{_bool_cell(entry.comparable)} | "
            f"{_bool_cell(entry.suppressible)} | {_bool_cell(entry.reportable)} |"
        )
    return "\n".join(lines)


def _render_flag_coverage_table() -> str:
    lines = [
        "| Reliability flag (`AbiSnapshot`) | Fields it gates |",
        "|-----------------------------------|------------------|",
    ]
    for flag in sorted(REFERENCE_FLAG_COVERAGE):
        fields = ", ".join(
            f"`{owner}.{field}`" for owner, field in REFERENCE_FLAG_COVERAGE[flag]
        )
        lines.append(f"| `{flag}` | {fields} |")
    return "\n".join(lines)


def _render_unconverted_table() -> str:
    lines = [
        "| Field | Converted? |",
        "|-------|------------|",
    ]
    for owner, field in sorted(KNOWN_UNCONVERTED_ELIGIBLE_FACTS):
        lines.append(f"| `{owner}.{field}` | not yet — tracked gap |")
    return "\n".join(lines)


def render() -> str:
    return f"""---
doc_type: reference
audience:
  - contributor
level: advanced
lifecycle: active
generated: true
---

# Fact/Capability Registry

{GENERATED_NOTE}

Every model field converted to `Fact[T]` (ADR-063 D2) is declared exactly
once in `abicheck/model/fact_registry.py`'s `FACT_REGISTRY` — its value
type, producing backends, persistence, and whether it participates in
identity/comparison/suppression/reporting. See
[ADR-063](../contribute/adr/063-one-semantic-pipeline.md) D7 and the
[implementation plan](../contribute/plans/one-semantic-pipeline.md)'s
Phase 5 section for the design this page's data comes from.

## Converted facts

{_render_registry_table()}

## Reliability-flag coverage (case (a))

Fields whose availability is governed by a snapshot-level
`*_facts_reliable` flag on `AbiSnapshot` rather than the field's own
resting value — the flag's own docstring in `abicheck/model/snapshot.py`
is the authoritative source for each row.

{_render_flag_coverage_table()}

## Eligible but not yet converted

An allowlist-and-shrink baseline (`fact_registry.
KNOWN_UNCONVERTED_ELIGIBLE_FACTS`) of fields the `fact-registry-
completeness` AI-readiness check (`scripts/fact_registry_completeness.py`)
has confirmed are availability-ambiguous — either flag-backed (case (a))
or a documented tri-state annotation (case (b)) — but have no `Fact[T]`
sibling yet. Each is a real, tracked gap, not a silently-accepted one; the
check fails if a new eligible field appears that isn't named here.

{_render_unconverted_table()}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Verify the file is in sync (CI)."
    )
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != content:
            print(f"{OUT_PATH} is out of date — run gen_fact_capability_matrix.py")
            return 1
        print(f"{OUT_PATH} is in sync.")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
