#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_platform_matrix.py — the host-OS x binary-format capability matrix,
generated from `scripts/platform_capabilities.py` instead of hand-typed.

Splices the "Quick Reference: What Works Where" section of
`docs/reference/platforms.md` between `<!-- BEGIN GENERATED: platform-matrix
-->` / `<!-- END GENERATED: platform-matrix -->` sentinels (the same
splice-into-hand-authored-file pattern `gen_examples_docs.py` uses for
`examples/README.md`) — the rest of that page (validation status, dependency
summary, Windows toolchain matrix, macOS ARM64 differences, known
limitations) stays hand-authored narrative.

Usage:
    python scripts/gen_platform_matrix.py            # write the file
    python scripts/gen_platform_matrix.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_DIR / "scripts"))
sys.path.insert(0, str(REPO_DIR))

from platform_capabilities import (  # type: ignore[import-not-found]  # noqa: E402
    PLATFORM_CAPABILITY_MATRIX,
    FormatMatrix,
    host_label,
)

OUT_PATH = REPO_DIR / "docs" / "reference" / "platforms.md"
_MARKER = "platform-matrix"

GENERATED_NOTE = (
    "<!-- The tables in this section are GENERATED by "
    "scripts/gen_platform_matrix.py — do not edit by hand. Run "
    "`python scripts/gen_platform_matrix.py` to regenerate. -->"
)


def _cell(supported: bool, full: bool) -> str:
    if not supported:
        return "❌ No"
    return "✅ Full" if full else "✅ Yes"


def _render_format(fmt: FormatMatrix) -> str:
    lines = [
        f"### {fmt.section_heading}",
        "",
        "| Host OS | Symbol diff | Type/param diff | Requires |",
        "|---------|------------|----------------|---------|",
    ]
    for h in fmt.hosts:
        host_cell = host_label(h.host) + (" ✅" if h.native else "")
        lines.append(
            f"| {host_cell} | {_cell(h.symbol_diff, h.native)} "
            f"| {_cell(h.type_param_diff, h.native)} | {h.requires} |"
        )
    if fmt.best_results_note:
        lines += ["", f"**Best results:** {fmt.best_results_note}"]
    return "\n".join(lines)


def render() -> str:
    sections = [_render_format(fmt) for fmt in PLATFORM_CAPABILITY_MATRIX]
    return GENERATED_NOTE + "\n\n" + "\n\n".join(sections) + "\n"


def _splice(text: str, inner: str) -> str:
    begin = re.search(rf"<!-- BEGIN GENERATED: {_MARKER} -->\n", text)
    end = re.search(rf"\n<!-- END GENERATED: {_MARKER} -->", text)
    if not begin or not end or begin.end() > end.start():
        raise ValueError(
            f"{OUT_PATH.relative_to(REPO_DIR)}: missing/misordered sentinels "
            f"for {_MARKER!r}"
        )
    return text[: begin.end()] + inner + text[end.start() :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    current = OUT_PATH.read_text(encoding="utf-8")
    rendered = _splice(current, render())

    if args.check:
        if rendered != current:
            print(
                f"{OUT_PATH.relative_to(REPO_DIR)}'s generated platform-matrix "
                "section is stale — regenerate with:",
                file=sys.stderr,
            )
            print("  python scripts/gen_platform_matrix.py", file=sys.stderr)
            return 1
        print(
            f"{OUT_PATH.relative_to(REPO_DIR)}'s platform-matrix section is "
            f"in sync ({len(PLATFORM_CAPABILITY_MATRIX)} formats)"
        )
        return 0

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(
        f"wrote {OUT_PATH.relative_to(REPO_DIR)}'s platform-matrix section "
        f"({len(PLATFORM_CAPABILITY_MATRIX)} formats)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
