#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerate ``abicheck/model/change_catalog/kinds.pyi`` from the three
``kind_names_*.py`` data files that assemble ``ChangeKind`` at runtime.

``kinds.py`` builds ``ChangeKind`` via the functional ``Enum()`` API (see
that module's own docstring for why -- a single ~950-line class body
exceeds this repository's 800-line production file-size cap once
physically placed under ``model/``), which mypy cannot statically resolve:
``Enum(name, [(n, v) for n, v, _ in some_runtime_list], ...)`` gives mypy no
way to know any member exists, so every ``ChangeKind.FOO`` access anywhere
in the codebase (~220 call sites) would report ``attr-defined``.

The fix is the standard PEP 484 mechanism for exactly this situation: a
stub file. When ``kinds.pyi`` sits next to ``kinds.py``, mypy type-checks
against the stub *only* (Python itself, at runtime, never reads it) -- so
the stub can declare ``ChangeKind`` the ordinary, fully-static class-body
way while the real module keeps its functional-API construction. This
generator is the mechanical link between the two: the stub is *derived*
from the same three data files ``kinds.py`` itself assembles at runtime, so
the two can never independently drift out of sync (verified by
``check_ai_readiness.py``'s ``generated-file-ownership``/regeneration-drift
checks, the same mechanism every other ``scripts/gen_*.py`` output uses).

Usage::

    python scripts/gen_changekind_stub.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_CATALOG = _ROOT / "abicheck" / "model" / "change_catalog"
_OUT = _CATALOG / "kinds.pyi"
_DATA_MODULES = ("kind_names_1", "kind_names_2", "kind_names_3")

_HEADER = """# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE IS GENERATED by scripts/gen_changekind_stub.py -- do not hand-edit.
#
# mypy-only stub (PEP 484): declares ChangeKind as an ordinary class-body
# enum so every `ChangeKind.FOO` access statically resolves, while kinds.py
# itself builds the real runtime Enum via the functional API to stay under
# the 800-line production file-size cap. See kinds.py's own docstring.
# Not scanned by scripts/check_architecture.py (*.py only), so it carries
# the full 397-member declaration in one file rather than being split.

from enum import Enum
from typing import Protocol

class ChangeKind(str, Enum):
"""

_FOOTER = """
    @classmethod
    def _missing_(cls, value: object) -> ChangeKind | None: ...

class HasKind(Protocol):
    kind: ChangeKind
"""


def _load_kind_names(module_name: str) -> list[tuple[str, str]]:
    """Extract ``(name, value)`` pairs from a ``kind_names_N.py`` data file.

    Reads the source directly (regex over the tuple literals) rather than
    importing the module -- this script must work from a clean checkout
    with nothing installed, matching every other ``gen_*.py`` script's
    convention here, and the tuple shape is simple/stable enough that a
    regex is both correct and far cheaper than a full AST walk for this.
    """
    path = _CATALOG / f"{module_name}.py"
    text = path.read_text(encoding="utf-8")
    # Matches ("NAME", "value", ...) -- the third element (comment or None)
    # is deliberately not captured; the stub only needs identity.
    pattern = re.compile(r'\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*,\s*"([^"]*)"\s*,')
    pairs = pattern.findall(text)
    if not pairs:
        raise ValueError(f"{path}: found no (name, value) tuples -- format changed?")
    return pairs


def render() -> str:
    lines = [_HEADER]
    seen_names: set[str] = set()
    seen_values: set[str] = set()
    for module_name in _DATA_MODULES:
        for name, value in _load_kind_names(module_name):
            if name in seen_names:
                raise ValueError(f"duplicate ChangeKind member name: {name!r}")
            if value in seen_values:
                raise ValueError(f"duplicate ChangeKind value: {value!r}")
            seen_names.add(name)
            seen_values.add(value)
            lines.append(f"    {name} = {value!r}\n")
    lines.append(_FOOTER)
    return "".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="Verify kinds.pyi is in sync with the kind_names_*.py data files; do not write.",
    )
    args = ap.parse_args(argv)

    content = render()

    if args.check:
        got = _OUT.read_text(encoding="utf-8") if _OUT.is_file() else None
        if got != content:
            print(f"ERROR: {_OUT.relative_to(_ROOT)} is out of date.", file=sys.stderr)
            print("Run: python scripts/gen_changekind_stub.py", file=sys.stderr)
            return 1
        print(f"{_OUT.relative_to(_ROOT)} in sync")
        return 0

    _OUT.write_text(content, encoding="utf-8")
    member_count = content.count("\n    ") - 1  # crude but good enough for the log line
    print(f"wrote {_OUT} (~{member_count} members)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
