#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate `action/cli-surface.txt` — the CLI choice sets the composite
Action needs **before** abicheck is installed (ADR-070 D3, plan Phase 3b).

**Why this file exists at all, when Phase 3a deleted the other snapshot.**
`action/run.sh` and `actions/check-target/action.yml` run *after*
`action.yml`'s own `pip install`, so their `extra-args` tokenizers query the
installed CLI directly and keep no list (Phase 3a). `action/validate-inputs.sh`
is different by design: it runs *before* Python setup so an unsupported input
combination fails in seconds instead of after a multi-minute toolchain
install (`action/AGENTS.md`). It therefore cannot ask, and ADR-070 D3 permits
a committed generated artifact for exactly that one shell — and nothing else.

**Scope, deliberately narrow.** Only genuine `click.Choice` sets are emitted:
the set of values the CLI itself will accept for an option. That is three
facts today (`compare --format`, `deps tree`/`deps compare --format`,
`dump --compression`).

`validate-inputs.sh` also enforces two *subsets* — `json|markdown|junit` for a
directory/package compare, and `json|markdown|sarif|junit|oneline` for
`compare --no-baseline` — and those are **not** emitted here on purpose. They
are not choice sets; they are claims about which renderer a particular
comparison shape supports, i.e. restriction mirrors in ADR-070 D1/D2's sense.
Deriving them would require modelling renderer capability per shape, which is
exactly the kind of CLI semantics the Action is supposed to stop
re-implementing. They are Phase 2 material, and generating them here would
dress a mirror up as a derived fact — worse than leaving them visible.

Usage:
    python scripts/gen_action_cli_surface.py            # write the file
    python scripts/gen_action_cli_surface.py --check     # fail on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "action" / "cli-surface.txt"

MARKER = "generated by scripts/gen_action_cli_surface.py"

#: (Action-facing label, command path, option spelling). The label is what
#: `validate-inputs.sh` keys on, so it names the Action's own `mode:` value
#: rather than the CLI command, and stays stable if the CLI is regrouped.
EMITTED_CHOICES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("compare", ("compare",), "--format"),
    ("deps-tree", ("deps", "tree"), "--format"),
    ("deps-compare", ("deps", "compare"), "--format"),
    ("dump", ("dump",), "--compression"),
)


def _resolve(path: tuple[str, ...]) -> click.Command:
    from abicheck.cli import main

    node: click.Command = main
    for segment in path:
        commands = getattr(node, "commands", None)
        if not commands or segment not in commands:
            raise SystemExit(f"no such command: {' '.join(path)}")
        node = commands[segment]
    return node


def _choices(path: tuple[str, ...], spelling: str) -> tuple[str, ...]:
    for param in _resolve(path).params:
        if isinstance(param, click.Option) and spelling in param.opts:
            choices = getattr(param.type, "choices", None)
            if not choices:
                raise SystemExit(
                    f"{' '.join(path)} {spelling} is not a click.Choice; "
                    "this generator only emits genuine choice sets"
                )
            return tuple(choices)
    raise SystemExit(f"{' '.join(path)} has no option {spelling}")


def render() -> str:
    lines = [
        f"# {MARKER} -- do not hand-edit.",
        "#",
        "# CLI choice sets `action/validate-inputs.sh` needs before abicheck is",
        "# installed. Read with `grep -qxF`. See the generator's docstring for",
        "# why only genuine click.Choice sets appear here (ADR-070 D3).",
    ]
    for label, path, spelling in EMITTED_CHOICES:
        for value in _choices(path, spelling):
            lines.append(f"CHOICE {label} {spelling} {value}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed file differs from freshly generated output",
    )
    args = parser.parse_args(argv)

    generated = render()
    if not args.check:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
        return 0

    if not OUTPUT.is_file():
        print(
            f"ERROR: {OUTPUT.relative_to(REPO_ROOT)} is missing -- run "
            "`python scripts/gen_action_cli_surface.py`",
            file=sys.stderr,
        )
        return 1
    committed = OUTPUT.read_text(encoding="utf-8")
    if committed != generated:
        print(
            f"ERROR: {OUTPUT.relative_to(REPO_ROOT)} is stale. The CLI's own "
            "choice sets have changed; regenerate with "
            "`python scripts/gen_action_cli_surface.py`.",
            file=sys.stderr,
        )
        committed_lines = set(committed.splitlines())
        generated_lines = set(generated.splitlines())
        for line in sorted(generated_lines - committed_lines):
            print(f"  + {line}", file=sys.stderr)
        for line in sorted(committed_lines - generated_lines):
            print(f"  - {line}", file=sys.stderr)
        return 1
    print(f"{OUTPUT.relative_to(REPO_ROOT)} is in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
