#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_cli_reference.py — exhaustive CLI command/option reference, generated
from the live Click command tree instead of hand-copied.

`abicheck/cli.py` (plus the `cli_<name>.py` sibling modules it registers) is
the fact owner for every command, argument, and option — `docs/user-guide/
cli-usage.md` and `docs/user-guide/dump-compare-flags.md` document the primary
workflows in prose, but neither one is (or should be) an exhaustive option
table. This generator makes `docs/reference/cli-reference.md` that exhaustive,
generated view: every top-level command/group, every subcommand, every
argument/option with its exact `help=` text, default, and choices — pulled
live from the `click.Command`/`click.Option` objects, the same way
`scripts/dump_cli_surface.py` does for the CI interface-diff check (that
script's JSON contract is deliberately not reused here — it exists for a
different consumer and shouldn't gain a second, unrelated stability
requirement just because both happen to walk the same Click tree).

Usage:
    python scripts/gen_cli_reference.py            # write the file
    python scripts/gen_cli_reference.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path, PurePath
from typing import Any

REPO_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_DIR / "docs" / "reference" / "cli-reference.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_cli_reference.py — do not edit by hand. "
    "Run `python scripts/gen_cli_reference.py` to regenerate. -->"
)


def _first_paragraph(text: str | None) -> str:
    """The short description Click shows on ``--help`` before the first
    blank line, dedented and collapsed to one line."""
    if not text:
        return ""
    import inspect

    dedented = inspect.cleandoc(text)
    first = dedented.split("\n\n", 1)[0]
    return " ".join(first.split())


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def _help_with_choices(param: Any) -> str:
    choices = getattr(getattr(param, "type", None), "choices", None)
    help_text = _escape(getattr(param, "help", None) or "")
    if choices:
        help_text = f"{help_text} Choices: {', '.join(f'`{c}`' for c in choices)}.".strip()
    return help_text


def _argument_row(param: Any) -> str:
    return f"| `{param.name}` | {_help_with_choices(param)} |"


def _default_str(default: Any) -> str:
    # pathlib renders its root separator per-platform (str(Path("/")) is "/"
    # on POSIX but "\\" on Windows) -- without this, regenerating on Windows
    # vs. Linux/macOS would produce a genuinely different committed file for
    # any option defaulting to a Path, which is exactly the kind of
    # platform-dependent drift a generated reference must not have.
    if isinstance(default, PurePath):
        return default.as_posix()
    return str(default)


def _option_row(param: Any) -> str:
    # A boolean flag pair (e.g. --demangle/--no-demangle) is one Click Option
    # with opts=["--demangle"] and secondary_opts=["--no-demangle"] -- listing
    # only opts drops the disable flag from the reference even though --help
    # shows both. Primary flags sort before secondary ones (rather than
    # merging then sorting all together) so a "--no-X"/"--X" pair reads in
    # its natural enable/disable order instead of alphabetically reversing
    # whenever "no-" sorts ahead of the rest of the primary flag's name.
    all_opts = sorted(param.opts) + sorted(getattr(param, "secondary_opts", []))
    opts = ", ".join(f"`{o}`" for o in all_opts)
    default = param.default
    # Click represents "no default was explicitly given" (relying on its own
    # implicit default — `()` for a `multiple=True` option, `None` otherwise)
    # as an internal sentinel enum rather than the resolved value; surfacing
    # its repr (`Sentinel.UNSET`) would be a Click implementation detail
    # leaking into a user-facing reference, not a real default.
    is_unset = type(default).__name__ == "Sentinel"
    default_str = "—"
    if not is_unset and default is not None and default != () and default is not False:
        default_str = f"`{_default_str(default)}`"
    required = "yes" if param.required else "no"
    return f"| {opts} | {required} | {default_str} | {_help_with_choices(param)} |"


def _render_command(name: str, cmd: Any, heading_level: int) -> list[str]:
    import click

    lines = [f"{'#' * heading_level} `{name}`", ""]
    summary = _first_paragraph(cmd.help)
    if summary:
        lines += [summary, ""]

    arguments = [p for p in cmd.params if isinstance(p, click.Argument)]
    options = [p for p in cmd.params if isinstance(p, click.Option)]

    if arguments:
        lines += ["**Arguments**", "", "| Name | Description |", "|---|---|"]
        lines += [_argument_row(p) for p in arguments]
        lines.append("")
    if options:
        lines += ["**Options**", "", "| Option | Required | Default | Description |", "|---|:--:|---|---|"]
        lines += [_option_row(p) for p in options]
        lines.append("")

    if isinstance(cmd, click.Group):
        for sub_name, sub_cmd in sorted(cmd.commands.items()):
            lines += _render_command(f"{name} {sub_name}", sub_cmd, heading_level + 1)
    return lines


def render() -> str:
    from abicheck.cli import main

    lines = [
        GENERATED_NOTE,
        "",
        "# CLI Reference",
        "",
        "Every `abicheck` command, subcommand, argument, and option, generated "
        "directly from the live Click command tree (the same `help=` text "
        "`--help` shows). See [CLI Usage](../user-guide/cli-usage.md) and "
        "[Dump & Compare Flags](../user-guide/dump-compare-flags.md) for the "
        "narrative walkthroughs of the primary workflows; this page is the "
        "exhaustive field list only.",
        "",
    ]
    for name, cmd in sorted(main.commands.items()):
        lines += _render_command(name, cmd, heading_level=2)
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    content = render()

    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != content:
            print(f"{OUT_PATH.relative_to(REPO_DIR)} is stale — regenerate with:")
            print("  python scripts/gen_cli_reference.py")
            return 1
        print(f"{OUT_PATH.relative_to(REPO_DIR)} is in sync")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
