#!/usr/bin/env python3
"""Generate docs/contribute/catalog-coverage.md -- Phase 6 of the
examples/catalog split (docs/contribute/plans/examples-catalog-split.md).

Phases 1-2 gave every case in `examples/ground_truth.json["taxonomy"]` an
`entity` (rule/scenario), a `rule_slug`/`variant_of`/`relation_type`/
`relation_axis` set, a `scenario_kind`, and an `ecosystem`. Before this
generator, every consumer that reported on catalog size
(examples/README.md's headline, the various coverage gates) still collapsed
all 197 cases into one flat count -- which is exactly the "three
demonstrations of one rule count as three ABI concepts" problem the plan's
"stop reporting all cases as semantically equal" section names. This script
reports the same 197 cases along five *independent* dimensions instead:

    rule coverage       -- how many distinct, ecosystem-neutral compatibility
                            rules the catalog demonstrates (by `rule_slug`,
                            deduplicated -- a rule and its variant(s)/
                            duplicate(s) count once)
    variant coverage     -- how many of those rules have a demonstrated
                            *variant* beyond their canonical case (a genuine
                            robustness demonstration under a different
                            condition -- language, evidence, public-surface,
                            ... -- see `relation_axis`), reported separately
                            from a plain *duplicate* (the same demonstration
                            restated with no distinguishing condition, per
                            `relation_type`): counting a duplicate as a
                            variant would inflate the catalog's demonstrated-
                            robustness claim (canonical, variant, and
                            duplicate cases reported separately -- a 2-case
                            family has exactly 1 variant or 1 duplicate, not
                            "more than one")
    scenario coverage    -- scenario-entity cases broken down by
                            `scenario_kind` (case-study / project-topology /
                            capability)
    ecosystem coverage   -- every case (rule or scenario) broken down by
                            `ecosystem`
    workflow coverage    -- user-facing task-oriented workflow examples;
                            derived from `examples/workflows/`'s real
                            subdirectory count (see the plan doc's Phase 5
                            row for the target set and progress against it)
                            rather than a static placeholder, so this
                            dimension can't go stale against Phase 5

This is a report, not a gate: it doesn't change what any existing check
counts, and it doesn't touch `examples/README.md`'s own headline/verdict
tables (`gen_examples_docs.py` owns those). `--check` fails (exit 1) if
regeneration would change the committed page, mirroring every other
`gen_*.py` generator in this repo.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "docs" / "contribute" / "catalog-coverage.md"

# Phase 3 resolver (scripts/CLAUDE.md). This script's own directory is
# already on sys.path when run directly, but not when imported as
# `scripts.gen_catalog_coverage_report` -- guard mirrors
# fact_detector_misuse.py's identical sibling-import guard for the
# identical reason.
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
import example_catalog  # noqa: E402

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_catalog_coverage_report.py -- do not edit "
    "by hand. Run `python scripts/gen_catalog_coverage_report.py` to "
    "regenerate. -->"
)

# Phase 5's target workflow set (docs/contribute/plans/examples-catalog-split.md's
# own Phase 5 row) -- the single source both the target count and the target
# list below are derived from, so they can't independently drift from each
# other. Update this tuple (and the plan doc's Phase 5 row) together if the
# target set itself ever changes.
PHASE5_TARGET_WORKFLOWS: tuple[str, ...] = (
    "compare one library",
    "audit a release",
    "multi-library project",
    "evidence depth",
    "build/source evidence",
    "Python API",
    "suppressions",
    "GitHub Actions",
)


def _rule_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    rules = {k: v for k, v in taxonomy.items() if v["entity"] == "rule"}
    scenarios = {k: v for k, v in taxonomy.items() if v["entity"] == "scenario"}
    slug_cases: dict[str, list[str]] = {}
    for case_id, entry in rules.items():
        slug_cases.setdefault(entry["rule_slug"], []).append(case_id)  # type: ignore[arg-type]

    # A distinct rule is any rule_slug a rule-entity case demonstrates,
    # *plus* any conceptual slug a scenario names in its own related_rules
    # with no rule-entity case of its own (e.g. "overload-set-removed" --
    # the design doc's own worked examples deliberately name a generic
    # mechanism no single-library case demonstrates alone yet). Counting
    # only rule-entity slugs would undercount the catalog's real rule
    # vocabulary by exactly that many.
    scenario_only_slugs: set[str] = set()
    for entry in scenarios.values():
        for slug in entry.get("related_rules") or []:  # type: ignore[union-attr]
            if slug not in slug_cases:
                scenario_only_slugs.add(slug)
    distinct_rule_count = len(slug_cases) + len(scenario_only_slugs)

    # A family's canonical case(s) are those with variant_of=None; everything
    # else in the family is either a genuine variant (relation_type ==
    # "variant", a robustness demonstration under a named relation_axis) or
    # a plain duplicate (relation_type == "duplicate", the same
    # demonstration restated with no distinguishing condition). Reported
    # separately -- collapsing the two is exactly what let three duplicate
    # restatements count as three robustness variants before this split. A
    # family with 2 cases has exactly 1 variant or 1 duplicate, not "more
    # than one". Case counts are filtered by each case's own relation_type
    # directly (never by which bucket its whole family fell into) so a
    # hypothetical mixed family -- one variant case plus one duplicate case
    # sharing the same rule_slug, not present in today's data but not ruled
    # out by the schema either -- can't have its duplicate silently
    # miscounted as a variant or vice versa; a family that mixes the two
    # legitimately appears in both family sets below, not just one.
    multi_case_families = {
        slug: cases for slug, cases in slug_cases.items() if len(cases) > 1
    }
    variant_families = {
        slug: cases
        for slug, cases in multi_case_families.items()
        if any(rules[c]["relation_type"] == "variant" for c in cases)
    }
    duplicate_families = {
        slug: cases
        for slug, cases in multi_case_families.items()
        if any(rules[c]["relation_type"] == "duplicate" for c in cases)
    }
    multi_case_ids = [c for cases in multi_case_families.values() for c in cases]
    variant_case_ids = [
        c for c in multi_case_ids if rules[c]["relation_type"] == "variant"
    ]
    duplicate_case_ids = [
        c for c in multi_case_ids if rules[c]["relation_type"] == "duplicate"
    ]

    lines = [
        "## Rule coverage",
        "",
        f"- **{distinct_rule_count} distinct compatibility rules** in total "
        f"-- **{len(slug_cases)}** demonstrated by at least one rule-entity "
        f"case (across **{len(rules)} rule-entity cases**), plus "
        f"**{len(scenario_only_slugs)}** named only in a scenario's own "
        "`related_rules` (a generic mechanism no single-library case "
        "demonstrates alone yet).",
        f"- **{len(variant_families)} of the rule-entity-backed rules** have "
        f"a demonstrated *variant* beyond their canonical case -- a genuine "
        f"robustness demonstration under a different condition "
        f"({len(variant_case_ids)} variant cases total -- see the per-family "
        "breakdown below); these are robustness demonstrations of an "
        "already-counted rule, not additional rules.",
        f"- **{len(duplicate_families)} of the rule-entity-backed rules** "
        f"also have a *duplicate* -- the same demonstration restated "
        f"with no distinguishing condition ({len(duplicate_case_ids)} "
        "duplicate cases total); these don't add robustness coverage and "
        "are candidates for eventual removal, not a variant to keep. (A "
        "family can appear in both this count and the variant count above "
        "if it has one of each.)",
        f"- **{len(slug_cases) - len(multi_case_families)} rule-entity-backed "
        "rules** have exactly one demonstrated case so far, with no "
        "variant or duplicate yet.",
        "",
        "| Rule | Canonical case | Variant case(s) | Duplicate case(s) |",
        "|---|---|---|---|",
    ]
    for slug in sorted(multi_case_families):
        cases = sorted(multi_case_families[slug])
        canonical = [c for c in cases if rules[c]["variant_of"] is None]
        variants = [c for c in cases if rules[c]["relation_type"] == "variant"]
        duplicates = [c for c in cases if rules[c]["relation_type"] == "duplicate"]
        lines.append(
            f"| `{slug}` | {', '.join(f'`{c}`' for c in canonical)} | "
            f"{', '.join(f'`{c}`' for c in variants)} | "
            f"{', '.join(f'`{c}`' for c in duplicates)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _scenario_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    scenarios = {k: v for k, v in taxonomy.items() if v["entity"] == "scenario"}
    by_kind: Counter[str] = Counter(
        entry["scenario_kind"]
        for entry in scenarios.values()  # type: ignore[misc]
    )
    lines = [
        "## Scenario coverage",
        "",
        f"**{len(scenarios)} scenario-entity cases** composing one or more "
        "rules into a realistic problem (an ecosystem case study, a "
        "multi-library project topology, or a capability/evidence "
        "demonstration) -- see each case's own `related_rules`.",
        "",
        "| Scenario kind | Cases |",
        "|---|---|",
    ]
    for kind in sorted(by_kind):
        lines.append(f"| `{kind}` | {by_kind[kind]} |")
    lines.append("")
    return "\n".join(lines)


def _ecosystem_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    by_eco: Counter[str] = Counter(
        entry["ecosystem"]
        for entry in taxonomy.values()  # type: ignore[misc]
    )
    lines = [
        "## Ecosystem coverage",
        "",
        "Every case, rule or scenario, tagged with the real-world ecosystem "
        "it models (`generic` for a language/platform-level mechanism with "
        "no particular project behind it).",
        "",
        "| Ecosystem | Cases |",
        "|---|---|",
    ]
    for eco in sorted(by_eco):
        lines.append(f"| `{eco}` | {by_eco[eco]} |")
    lines.append("")
    return "\n".join(lines)


def _workflow_coverage() -> str:
    workflows_dir = example_catalog.EXAMPLES_DIR / "workflows"
    workflows = (
        sorted(p.name for p in workflows_dir.iterdir() if p.is_dir())
        if workflows_dir.is_dir()
        else []
    )
    header = (
        f"**{len(workflows)} workflow example{'' if len(workflows) == 1 else 's'}** "
        f"so far, out of the {len(PHASE5_TARGET_WORKFLOWS)} task-oriented "
        "workflows Phase 5 of the examples/catalog split "
        "(`docs/contribute/plans/examples-catalog-split.md`) targets: "
        f"{', '.join(PHASE5_TARGET_WORKFLOWS)}."
    )
    rows = [f"| `{name}` |" for name in workflows] or ["| _(none yet)_ |"]
    return "\n".join(
        [
            "## Workflow coverage",
            "",
            header,
            "",
            "| Workflow |",
            "|---|",
            *rows,
            "",
            "Reported here as its real, current count (derived from "
            "`examples/workflows/`'s own subdirectories) rather than a "
            "static placeholder, so this page states all five dimensions "
            "the plan tracks, not just the ones already implemented.",
            "",
        ]
    )


def render() -> str:
    gt = example_catalog.load_ground_truth()
    taxonomy: dict[str, dict[str, object]] = gt["taxonomy"]  # type: ignore[assignment]

    parts = [
        GENERATED_NOTE,
        "",
        "# Catalog coverage by dimension",
        "",
        f"Phase 6 of the [examples/catalog split]"
        f"(plans/examples-catalog-split.md): the calibration "
        f"catalog under `examples/` is {len(taxonomy)} `caseNN_*` fixtures, "
        f"but not {len(taxonomy)} independent ABI/API concepts -- several "
        "are variants of the same rule, or scenarios composing rules "
        "already counted elsewhere. This page reports the catalog along "
        "five independent dimensions instead of one flat case count, so "
        '"three demonstrations of one rule" reads as "1 rule, 3 cases (1 '
        'canonical + 2 variants)" rather than "3 ABI concepts". Regenerate with '
        "`python scripts/gen_catalog_coverage_report.py` after any "
        "`ground_truth.json` change.",
        "",
        _rule_coverage(taxonomy),
        _scenario_coverage(taxonomy),
        _ecosystem_coverage(taxonomy),
        _workflow_coverage(),
    ]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if regeneration would change the committed page",
    )
    args = parser.parse_args()

    new_content = render()

    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else None
        if current != new_content:
            print(
                f"{OUT_PATH.relative_to(ROOT)} is stale -- run "
                "`python scripts/gen_catalog_coverage_report.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT_PATH.relative_to(ROOT)} is up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(new_content, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
