#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_config_reference.py — exhaustive `.abicheck.yml` key/type reference,
generated from `abicheck.buildsource.build_config.BuildConfig`'s own
strict-schema registries instead of hand-copied.

`BuildConfig._KNOWN_TOP_KEYS`/`_KNOWN_BLOCK_KEYS` (which top-level/block keys
are recognized) and the module-level `_BOOL_SUBKEYS`/`_STR_SUBKEYS`/
`_LIST_SUBKEYS` (each block sub-key's required YAML type, enforced by
`BuildConfig.from_dict`'s strict-schema validation, ADR-043) are already the
fact owner for the config file's exact shape. `docs/reference/config-file.md`
documents *effective defaults*, CLI-override precedence, and a worked example
— richer than a mechanical field dump, and deliberately kept hand-written;
this generator produces the exhaustive "every key, every sub-key, its exact
required type" table that page links out to instead of restating by hand.

Usage:
    python scripts/gen_config_reference.py            # write the file
    python scripts/gen_config_reference.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_DIR / "docs" / "reference" / "config-keys-reference.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_config_reference.py — do not edit by hand. "
    "Run `python scripts/gen_config_reference.py` to regenerate. -->"
)


def _subkey_type(
    block: str, subkey: str, bool_map: dict, str_map: dict, list_map: dict
) -> str:
    if subkey in bool_map.get(block, frozenset()):
        return "bool"
    if subkey in str_map.get(block, frozenset()):
        return "str"
    if subkey in list_map.get(block, frozenset()):
        return "list[str] (or a single str)"
    return "unspecified"


def render() -> str:
    # Make the command work from a clean checkout (no install / no PYTHONPATH):
    # sys.path[0] is scripts/, not the repo root, so the abicheck import below
    # fails there without this.
    if str(REPO_DIR) not in sys.path:
        sys.path.insert(0, str(REPO_DIR))
    from abicheck.buildsource.build_config import (
        _BOOL_SUBKEYS,
        _LIST_SUBKEYS,
        _STR_SUBKEYS,
        _TOP_LEVEL_INT_KEYS,
        _TOP_LEVEL_STR_KEYS,
        BuildConfig,
    )

    known_top = BuildConfig._KNOWN_TOP_KEYS
    known_blocks = BuildConfig._KNOWN_BLOCK_KEYS
    scalar_keys = _TOP_LEVEL_STR_KEYS | _TOP_LEVEL_INT_KEYS
    other_keys = sorted(known_top - set(known_blocks) - scalar_keys)

    lines = [
        GENERATED_NOTE,
        "",
        "# Config Keys Reference",
        "",
        "Every `.abicheck.yml` top-level key and block sub-key that "
        "`abicheck.buildsource.build_config.BuildConfig` itself validates, with "
        "its exact required YAML type — generated directly from "
        "`BuildConfig`'s strict-schema registries (an unknown key or a "
        'wrong-typed value is a hard error, ADR-043). "Other recognized '
        'top-level keys" below are also accepted but parsed by a sibling '
        "module instead, so no type is claimed for them here. See [Config "
        "File Reference](../reference/config-file.md) for effective "
        "defaults, CLI-override precedence, and a worked example; this "
        "page is the exhaustive key/type list for `BuildConfig`'s own "
        "schema only.",
        "",
        "## Blocks",
        "",
    ]
    for block in sorted(known_blocks):
        lines += [f"### `{block}:`", "", "| Sub-key | Type |", "|---|---|"]
        for subkey in sorted(known_blocks[block]):
            type_str = _subkey_type(
                block, subkey, _BOOL_SUBKEYS, _STR_SUBKEYS, _LIST_SUBKEYS
            )
            lines.append(f"| `{subkey}` | {type_str} |")
        lines.append("")

    lines += ["## Top-level scalar keys", "", "| Key | Type |", "|---|---|"]
    for key in sorted(scalar_keys):
        type_str = "int" if key in _TOP_LEVEL_INT_KEYS else "str"
        lines.append(f"| `{key}` | {type_str} |")
    lines.append("")

    if other_keys:
        lines += [
            "## Other recognized top-level keys",
            "",
            "Recognized (so they don't trigger the unknown-key warning) but "
            "parsed by a sibling module rather than `BuildConfig` itself — "
            # abicheck/buildsource/CLAUDE.md lives outside docs/ and isn't
            # built by mkdocs, so there's no relative site path to resolve
            # this to (an absolute github.com/.../blob/main link would send
            # readers of an older release or a fork to the current main
            # branch instead of the version they're reading) -- leave it as
            # an unlinked code path instead.
            "see `abicheck/buildsource/CLAUDE.md`'s module map for which one:",
            "",
        ]
        lines += [f"- `{key}`" for key in other_keys]
        lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    content = render()

    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != content:
            print(f"{OUT_PATH.relative_to(REPO_DIR)} is stale — regenerate with:")
            print("  python scripts/gen_config_reference.py")
            return 1
        print(f"{OUT_PATH.relative_to(REPO_DIR)} is in sync")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
