#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_python_api_reference.py — exhaustive Python API reference, generated
from `abicheck.service.__all__` instead of hand-copied.

`abicheck/service.py`'s `__all__` (re-exporting names from `service_scan.py`,
`service_render.py`, and `api_types.py`) is the Tier-2 public surface — the
same one the CLI and MCP server call through (ADR-037). `docs/user-guide/
python-api.md` deliberately documents only `run_compare`'s "common subset" of
keyword arguments and explicitly punts to the docstrings for the rest; this
generator produces the full signature/dataclass-field reference `python-
api.md` already points readers at, so that pointer resolves to a real page
instead of "go read the source".

Usage:
    python scripts/gen_python_api_reference.py            # write the file
    python scripts/gen_python_api_reference.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import dataclasses
import inspect
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_DIR / "docs" / "reference" / "python-api-reference.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_python_api_reference.py — do not edit by "
    "hand. Run `python scripts/gen_python_api_reference.py` to regenerate. -->"
)


def _summary(obj: object) -> str:
    doc = inspect.getdoc(obj)
    if not doc:
        return ""
    return doc.split("\n\n", 1)[0].strip().replace("\n", " ")


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def _type_str(annotation: object) -> str:
    if annotation is inspect.Parameter.empty or annotation is dataclasses.MISSING:
        return ""
    return _escape(str(annotation).replace("'", ""))


def _dataclass_section(name: str, cls: type) -> list[str]:
    lines = [f"## `{name}`", "", _summary(cls), "", "*Dataclass.*", ""]
    lines += ["| Field | Type | Default |", "|---|---|---|"]
    for f in dataclasses.fields(cls):
        if f.default is not dataclasses.MISSING:
            default = f"`{f.default!r}`"
        elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            default = f"`{f.default_factory()!r}`"
        else:
            default = "*(required)*"
        lines.append(f"| `{f.name}` | `{_type_str(f.type)}` | {default} |")
    lines.append("")
    return lines


def _function_section(name: str, fn: object) -> list[str]:
    sig = inspect.signature(fn)  # type: ignore[arg-type]
    lines = [f"## `{name}`", "", _summary(fn), "", "| Parameter | Type | Default |", "|---|---|---|"]
    seen_keyword_only = False
    for param_name, param in sig.parameters.items():
        if param.kind in (
            inspect.Parameter.VAR_POSITIONAL,
            inspect.Parameter.VAR_KEYWORD,
        ):
            continue
        # A leading underscore (e.g. run_dump's `_skip_header_graph_attach`)
        # is this codebase's convention for "private, internal-only knob,
        # not public API" (see that parameter's own docstring) -- publishing
        # it on the advertised public-API reference invites callers to
        # depend on an implementation detail we'd otherwise be free to
        # change or remove.
        if param_name.startswith("_"):
            continue
        # Mirror Python's own `*` separator: everything below can only be
        # passed by keyword, so a caller who follows the table's row order
        # as positional args (e.g. compare_snapshots(old, new, suppression,
        # policy)) would hit a TypeError the table gave no hint of.
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not seen_keyword_only:
            lines.append("| *(keyword-only below)* | | |")
            seen_keyword_only = True
        default = "*(required)*" if param.default is inspect.Parameter.empty else f"`{param.default!r}`"
        lines.append(f"| `{param_name}` | `{_type_str(param.annotation)}` | {default} |")
    return_type = _type_str(sig.return_annotation)
    if return_type:
        lines += ["", f"**Returns:** `{return_type}`"]
    lines.append("")
    return lines


def render() -> str:
    # Make the command work from a clean checkout (no install / no PYTHONPATH):
    # sys.path[0] is scripts/, not the repo root, so the abicheck import below
    # fails there without this.
    if str(REPO_DIR) not in sys.path:
        sys.path.insert(0, str(REPO_DIR))
    from abicheck import service

    lines = [
        GENERATED_NOTE,
        "",
        "# Python API Reference",
        "",
        "Every name in `abicheck.service.__all__` — the supported Tier-2 "
        "public entry point — with its full signature or dataclass field "
        "list, generated directly from the live objects. See "
        "[Python API](../user-guide/python-api.md) for the narrative "
        "walkthrough (comparing libraries, working with snapshots, "
        "rendering results); this page is the exhaustive signature list "
        "only.",
        "",
    ]
    for name in sorted(service.__all__):
        obj = getattr(service, name)
        if dataclasses.is_dataclass(obj):
            lines += _dataclass_section(name, obj)
        else:
            lines += _function_section(name, obj)
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    content = render()

    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != content:
            print(f"{OUT_PATH.relative_to(REPO_DIR)} is stale — regenerate with:")
            print("  python scripts/gen_python_api_reference.py")
            return 1
        print(f"{OUT_PATH.relative_to(REPO_DIR)} is in sync")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
