#!/usr/bin/env python3
"""Generate docs/development/adr/index.md from the ADR markdown files.

The ADR index is a single shared table that every ADR-adding PR used to edit
by hand, which made it a recurring merge-conflict hot spot (and it silently
drifted out of sync — ADRs were added without an index row). This generator
makes the table a *derived artifact*: contributors add their `NNN-title.md`
file and run this script; the table is rebuilt from the files themselves.

Source of truth for each row:
  - number  — the `NNN` filename prefix
  - title   — the first-line H1 (`# ADR-NNN: <title>`)
  - status  — the `**Status:** <status>` line

Run before `mkdocs build`. Idempotent. Pass --check to fail (exit 1) if
regeneration would change index.md (used by CI as a drift gate), mirroring
scripts/gen_examples_docs.py.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = ROOT / "docs" / "development" / "adr"
INDEX = ADR_DIR / "index.md"

# ADR files are `NNN-slug.md`; everything else in the directory (index.md,
# adr-gap-analysis.md, …) is not a numbered decision record.
ADR_FILE_RE = re.compile(r"^(\d{3})-.*\.md$")
HEADING_RE = re.compile(r"^#\s*ADR-0*\d+\s*[:.\-—]?\s*(.*\S)\s*$", re.MULTILINE)
STATUS_RE = re.compile(r"^\*\*Status:\*\*\s*(.+?)\s*$", re.MULTILINE)

WARNING = (
    "<!-- DO NOT EDIT — generated by scripts/gen_adr_index.py. "
    "Source: the ADR markdown files in this directory. "
    "Run `python scripts/gen_adr_index.py` after adding an ADR. -->\n"
)


@dataclass(frozen=True)
class Adr:
    number: str  # zero-padded 3-digit prefix, e.g. "001"
    filename: str
    title: str
    status: str


def _parse_adr(path: Path) -> Adr:
    m = ADR_FILE_RE.match(path.name)
    if not m:  # pragma: no cover - guarded by caller
        raise ValueError(f"not an ADR filename: {path.name}")
    text = path.read_text(encoding="utf-8")

    h = HEADING_RE.search(text)
    if not h:
        raise ValueError(
            f"{path.name}: first heading must look like `# ADR-NNN: <title>`"
        )
    title = h.group(1).strip()

    s = STATUS_RE.search(text)
    if not s:
        raise ValueError(f"{path.name}: missing a `**Status:** <status>` line")
    status = s.group(1).strip()

    return Adr(number=m.group(1), filename=path.name, title=title, status=status)


def _collect_adrs() -> list[Adr]:
    adrs = [
        _parse_adr(p)
        for p in ADR_DIR.iterdir()
        if p.is_file() and ADR_FILE_RE.match(p.name)
    ]
    # Sort by (number, filename) so duplicate-numbered ADRs render in a stable,
    # deterministic order rather than relying on directory iteration order.
    return sorted(adrs, key=lambda a: (a.number, a.filename))


def _render(adrs: list[Adr]) -> str:
    lines = [
        WARNING,
        "# Architecture Decision Records\n",
        "\n",
        "| # | Title | Status |\n",
        "|---|-------|--------|\n",
    ]
    for a in adrs:
        lines.append(f"| [{a.number}]({a.filename}) | {a.title} | {a.status} |\n")
    return "".join(lines)


def _normalize(data: bytes) -> bytes:
    if data.startswith(b"\xef\xbb\xbf"):
        data = data[3:]
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if index.md differs from what would be generated.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    adrs = _collect_adrs()
    rendered = _render(adrs)

    if args.check:
        current = _normalize(INDEX.read_bytes()) if INDEX.exists() else b""
        if current != rendered.encode("utf-8"):
            print(
                "docs/development/adr/index.md is out of date. "
                "Run: python scripts/gen_adr_index.py",
                file=sys.stderr,
            )
            return 1
        print(f"ADR index is up to date ({len(adrs)} ADRs).")
        return 0

    INDEX.write_bytes(rendered.encode("utf-8"))
    print(f"Generated {INDEX.relative_to(ROOT)} ({len(adrs)} ADRs).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
