#!/usr/bin/env python3
"""Generate `docs/contribute/abi-taxonomy-coverage.md` -- Phases 2 and 3 of
`docs/contribute/plans/abi-api-knowledge-and-corpus.md`.

Mirrors `gen_catalog_coverage_report.py`'s contract (render, `--check` gates
drift), but reports a different denominator. That page counts what the
calibration corpus *contains* along five dimensions; this one counts what the
corpus and the educational track *cover* out of the 88 leaf mechanisms Phase 1
enumerated in `docs/contribute/abi-api-failure-taxonomy.md` -- the plan's own
"completeness against the taxonomy, not the raw case count" headline.

Everything substantive is read, never inferred: the leaf set from Phase 1's
frozen Markdown taxonomy, the three Phase 2 columns and the Phase 3 status
from the hand-maintained `docs/_meta/abi-taxonomy-coverage.json`, and each
`ChangeKind`'s owning module and minimum evidence tier from
`abicheck/model/change_catalog/` and `scripts/evidence_tiers.py`. See
`abi_taxonomy_coverage.py` for the parser, the loader, and the gate.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "docs" / "contribute" / "abi-taxonomy-coverage.md"

if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
import abi_taxonomy_coverage as atc  # noqa: E402

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_abi_taxonomy_coverage.py -- do not edit "
    "by hand. Run `python scripts/gen_abi_taxonomy_coverage.py` to "
    "regenerate. The mapping it renders is hand-maintained in "
    "docs/_meta/abi-taxonomy-coverage.json. -->"
)

FRONT_MATTER = (
    "---\n"
    "doc_type: contributor\n"
    "audience:\n"
    "  - maintainer\n"
    "level: advanced\n"
    "lifecycle: active\n"
    "generated: true\n"
    "---"
)


def _learn_cell(mapping: atc.Mapping) -> str:
    if not mapping.learn_pages:
        return "_none_"
    return "<br>".join(f"[{Path(p).stem}](../{p})" for p in sorted(mapping.learn_pages))


def _cases_cell(mapping: atc.Mapping) -> str:
    if not mapping.catalog_cases:
        return "_none_"
    rendered = "<br>".join(f"`{c}`" for c in sorted(mapping.catalog_cases))
    if not mapping.cases_demonstrate:
        rendered += "<br>_(control only)_"
    return rendered


def _detector_cell(
    mapping: atc.Mapping, modules: dict[str, str], tiers: dict[str, str]
) -> str:
    if not mapping.detector_kinds:
        return "_none_"
    parts = []
    for kind in sorted(mapping.detector_kinds):
        module = modules.get(kind, "?")
        tier = tiers.get(kind, "--")
        parts.append(f"`{kind}` ({module}, {tier})")
    return "<br>".join(parts)


def _headline(counts: dict[str, int], total: int) -> list[str]:
    covered = counts["COVERED"]
    tail = ", ".join(
        f"{counts[s]} {s}" for s in atc.STATUS_ORDER if s != "COVERED" and counts[s]
    )
    return [
        "## Headline",
        "",
        f"**{covered} of {total} known ABI/API failure mechanisms are "
        f"`COVERED`** -- explained by a `docs/learn/` page, demonstrated by a "
        f"`catalog/cases/` case, and detected by at least one `ChangeKind`. "
        f"The remaining {total - covered}: {tail}.",
        "",
        "This is the plan's intended metric: completeness against the *domain*, "
        "not a case count. A corpus can grow indefinitely without moving this "
        "number, and can look complete while a whole mechanism class has no "
        "case at all.",
        "",
        "| Status | Leaves | Meaning |",
        "|---|--:|---|",
        *[
            f"| `{s}` | {counts[s]} | {atc.STATUS_MEANING[s]} |"
            for s in atc.STATUS_ORDER
        ],
        f"| **Total** | **{total}** | |",
        "",
        "The six statuses are evaluated in the order listed (first match wins) "
        "-- see the plan's own Phase 3 table in [ABI/API knowledge and corpus]"
        "(plans/abi-api-knowledge-and-corpus.md) for each definition. The "
        "order, not the "
        "prose, is what keeps them mutually exclusive: a mechanism with a "
        'detector but no case satisfies both "detection is real" and "no case '
        'exists".',
        "",
    ]


def _backlog(mapping: dict[str, atc.Mapping]) -> list[str]:
    missing = sorted(leaf for leaf, m in mapping.items() if m.status == "MISSING_CASE")
    not_impl = sorted(
        leaf for leaf, m in mapping.items() if m.status == "NOT_IMPLEMENTED"
    )
    undetectable = sorted(
        leaf for leaf, m in mapping.items() if m.status == "KNOWN_UNDETECTABLE"
    )
    lines = [
        "## Phase 4 backlog",
        "",
        f"The **{len(missing)} `MISSING_CASE` leaves** below are Phase 4's "
        "concrete work list: a detector already claims each one, so the gap is "
        "a corpus gap. Phase 4 closes each with a paired positive/negative "
        "control through the ordinary case-authoring path (`catalog/CLAUDE.md`) "
        "-- it is not started, and this page does not require the list to reach "
        "zero (a tracked, visible gap is preferred to a manufactured closure).",
        "",
        "| Leaf | Why it is open |",
        "|---|---|",
    ]
    for leaf in missing:
        lines.append(f"| `{leaf}` | {mapping[leaf].reason} |")
    lines += [
        "",
        f"Separately, **{_leaves(len(not_impl))} {_is_are(len(not_impl))} "
        "`NOT_IMPLEMENTED`** -- a product gap rather than a corpus gap, "
        "tracked in [known gaps](known-gaps.md): "
        + ", ".join(f"`{leaf}`" for leaf in not_impl)
        + f". And **{_leaves(len(undetectable))} {_is_are(len(undetectable))} "
        "`KNOWN_UNDETECTABLE`** -- accepted limitations, cross-referenced from "
        "[Limitations](../learn/limitations.md): "
        + ", ".join(f"`{leaf}`" for leaf in undetectable)
        + ".",
        "",
    ]
    return lines


def _leaves(n: int) -> str:
    return f"{n} leaf" if n == 1 else f"{n} leaves"


def _is_are(n: int) -> str:
    return "is" if n == 1 else "are"


def _branch_sections(
    leaves: list[atc.Leaf],
    mapping: dict[str, atc.Mapping],
    modules: dict[str, str],
    tiers: dict[str, str],
) -> list[str]:
    lines: list[str] = [
        "## Per-leaf mapping",
        "",
        "One row per taxonomy leaf, in the taxonomy's own branch and row order. "
        "Each detector cell names the `ChangeKind`, the "
        "`abicheck/model/change_catalog/` module that owns its registry entry, "
        "and its minimum evidence tier; `--` there means the kind carries no "
        "entry in `scripts/evidence_tiers.py`'s `EVIDENCE_TIER_BY_KIND` (that "
        "table covers the kinds the example catalog exercises, not every kind "
        "in the registry). A case cell marked _(control only)_ maps a case "
        "that exercises the mechanism's *non*-breaking sibling -- a negative or "
        "false-positive control -- without demonstrating the mechanism itself.",
        "",
    ]
    seen: set[str] = set()
    for index, leaf in enumerate(leaves):
        if leaf.branch.slug not in seen:
            seen.add(leaf.branch.slug)
            lines += [
                f"### {leaf.branch.number}. {leaf.branch.title} (`{leaf.branch.slug}`)",
                "",
                "| Leaf | `learn_pages` | `catalog_cases` | "
                "`detector` (kind, module, min evidence) | Status |",
                "|---|---|---|---|---|",
            ]
        m = mapping[leaf.leaf_id]
        lines.append(
            f"| `{leaf.leaf_id}`<br>{leaf.mechanism} | {_learn_cell(m)} | "
            f"{_cases_cell(m)} | {_detector_cell(m, modules, tiers)} | "
            f"`{m.status}` |"
        )
        # Close each branch's table before the notes that follow it.
        next_index = index + 1
        last_of_branch = (
            next_index == len(leaves)
            or leaves[next_index].branch.slug != leaf.branch.slug
        )
        if last_of_branch:
            notes = [
                f"- `{ln.leaf_id}` ({mapping[ln.leaf_id].status}) — "
                f"{mapping[ln.leaf_id].reason}"
                for ln in leaves
                if ln.branch.slug == leaf.branch.slug and mapping[ln.leaf_id].reason
            ]
            lines.append("")
            if notes:
                lines += [*notes, ""]
    return lines


def render() -> str:
    leaves = atc.parse_taxonomy()
    mapping = atc.load_mapping()
    errors = atc.validate(leaves, mapping)
    if errors:
        raise SystemExit(
            "refusing to render an inconsistent coverage matrix:\n  "
            + "\n  ".join(errors)
        )
    modules = atc.kind_modules()
    tiers = atc.kind_tiers()
    counts = atc.status_counts(mapping)

    parts = [
        FRONT_MATTER,
        "",
        GENERATED_NOTE,
        "",
        "# ABI/API taxonomy coverage",
        "",
        "Phases 2 and 3 of [ABI/API knowledge and corpus]"
        "(plans/abi-api-knowledge-and-corpus.md): every leaf mechanism in the "
        "[ABI/API failure taxonomy](abi-api-failure-taxonomy.md) resolved "
        "against the three things this repository already has -- the "
        "`docs/learn/` page(s) that explain it, the `catalog/cases/` case(s) "
        "that demonstrate it, and the `ChangeKind`(s) that would produce a "
        "finding for it -- and then classified with exactly one coverage "
        "status.",
        "",
        "The taxonomy is deliberately independent of abicheck's own "
        "vocabulary, which is what lets this page find a gap on either side "
        "rather than defining the domain in abicheck's image and then "
        "trivially covering it. A column may legitimately be empty; an empty "
        "one is recorded, not filled in with the nearest plausible match.",
        "",
        "The mapping itself is hand-maintained in "
        "`docs/_meta/abi-taxonomy-coverage.json` (the single source of truth "
        "this page renders and `scripts/check_ai_readiness.py`'s "
        "`abi-taxonomy-coverage` check gates). Only two facts on this page are "
        "derived: each `ChangeKind`'s owning "
        "`abicheck/model/change_catalog/` module and its minimum evidence "
        "tier (`scripts/evidence_tiers.py`), read from those sources so they "
        "cannot go stale here.",
        "",
        *_headline(counts, len(leaves)),
        *_backlog(mapping),
        *_branch_sections(leaves, mapping, modules, tiers),
    ]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if regeneration would change the committed page",
    )
    args = parser.parse_args()

    new_content = render()

    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else None
        if current != new_content:
            print(
                f"{OUT_PATH.relative_to(ROOT)} is stale -- run "
                "`python scripts/gen_abi_taxonomy_coverage.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT_PATH.relative_to(ROOT)} is up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(new_content, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
