#!/usr/bin/env python3
"""Generate the docs/reference/examples/ tree from examples/ + ground_truth.json.

Run before `mkdocs build`. Idempotent. Pass --check to fail if regeneration
would change the tree (used by CI as a drift gate).
"""

from __future__ import annotations

import argparse
import filecmp
import json
import posixpath
import re
import shutil
import sys
import tempfile
from collections import Counter, defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Phase 3 resolver (scripts/CLAUDE.md). This script's own directory is
# already on sys.path when run directly, but not when imported as
# `scripts.gen_examples_docs` -- guard mirrors fact_detector_misuse.py's
# identical sibling-import guard for the identical reason.
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
import example_catalog  # noqa: E402

EXAMPLES_DIR = example_catalog.EXAMPLES_DIR
DOCS_EXAMPLES_DIR = ROOT / "docs" / "reference" / "examples"
#: DOCS_EXAMPLES_DIR's location relative to docs/ root -- drives how many
#: "../" segments a link from a generated case page needs to reach another
#: docs/-relative path (see _rewrite_links).
DOCS_EXAMPLES_DIR_FROM_DOCS_ROOT = "reference/examples"
GROUND_TRUTH = example_catalog.GROUND_TRUTH_PATH
EXAMPLES_README = EXAMPLES_DIR / "README.md"
REPO_ROOT_FROM_DOCS_EXAMPLES = "../../.."

# Short category labels used in the examples/README.md catalog index. These are
# the exact strings the `examples-readme-sync` AI-readiness check asserts each
# row against — keep the two in sync.
README_CATEGORY_LABEL = {
    "breaking": "Breaking",
    "api_break": "API Break",
    "risk": "Risk",
    "addition": "Addition",
    "quality": "Quality",
    "no_change": "No Change",
    "bundle": "Bundle",
}

VERDICT_META = {
    "BREAKING": {
        "icon": "🔴",
        "slug": "breaking",
        "label": "BREAKING",
        "blurb": "ABI breaks: existing consumers will fail at runtime.",
    },
    "API_BREAK": {
        "icon": "🟠",
        "slug": "api-break",
        "label": "API_BREAK",
        "blurb": "Source-level / API-only breaks; recompilation fails or behavior shifts.",
    },
    "COMPATIBLE_WITH_RISK": {
        "icon": "🟡",
        "slug": "compatible-risk",
        "label": "COMPATIBLE_WITH_RISK",
        "blurb": "Backward-compatible at the symbol level but with behavioral risk.",
    },
    "COMPATIBLE": {
        "icon": "🟢",
        "slug": "compatible",
        "label": "COMPATIBLE",
        "blurb": "Backward-compatible changes (additions or quality-only).",
    },
    "NO_CHANGE": {
        "icon": "✅",
        "slug": "no-change",
        "label": "NO_CHANGE",
        "blurb": "Identical ABI/API — baseline control cases.",
    },
}

CATEGORY_META = {
    "breaking": {
        "label": "Breaking",
        "blurb": "Listed in `BREAKING_KINDS` — runtime ABI break.",
    },
    "api_break": {
        "label": "API Break",
        "blurb": "Listed in `API_BREAK_KINDS` — source/API-level break.",
    },
    "risk": {
        "label": "Risk",
        "blurb": "Listed in `RISK_KINDS` — symbol-compatible but behaviorally risky.",
    },
    "addition": {
        "label": "Addition (Compatible)",
        "blurb": "Listed in `ADDITION_KINDS` — backward-compatible additions.",
    },
    "quality": {
        "label": "Quality (Compatible)",
        "blurb": "Listed in `QUALITY_KINDS` — metadata/quality issues, not ABI breaks.",
    },
    "no_change": {
        "label": "No Change",
        "blurb": "Identical ABI/API — sanity-check baselines.",
    },
}

VERDICT_ORDER = [
    "BREAKING",
    "API_BREAK",
    "COMPATIBLE_WITH_RISK",
    "COMPATIBLE",
    "NO_CHANGE",
]
CATEGORY_ORDER = ["breaking", "api_break", "risk", "addition", "quality", "no_change"]

# Normalize platform ids from ground_truth.json to their canonical user-facing
# spelling. ground_truth.json uses lowercase ids so it can match Python platform
# checks; docs should show the canonical brand name.
PLATFORM_DISPLAY = {
    "linux": "Linux",
    "macos": "macOS",
    "windows": "Windows",
}

# Taxonomy display metadata (docs/contribute/plans/examples-catalog-split.md).
ENTITY_LABEL = {
    "rule": "Rule",
    "scenario": "Scenario",
}
SCENARIO_KIND_LABEL = {
    "case-study": "Ecosystem case study",
    "project-topology": "Multi-library project topology",
    "capability": "Capability / evidence demonstration",
}
ECOSYSTEM_LABEL = {
    "generic": "Generic (language/platform-level, no specific project)",
    "onetbb": "oneTBB",
    "sycl": "SYCL",
    "onemkl": "oneMKL",
    "linux-kernel": "Linux kernel",
}
ECOSYSTEM_ORDER = ["generic", "onetbb", "sycl", "onemkl", "linux-kernel"]
RELATION_TYPE_LABEL = {
    "duplicate": "Duplicate",
    "variant": "Variant",
}

WARNING = (
    "<!-- DO NOT EDIT — generated by scripts/gen_examples_docs.py. "
    "Source: examples/<case>/README.md + examples/ground_truth.json. -->\n"
)

# Strip a leading "caseNN" / "Case NN" / "caseNNb" token (and its trailing
# separator) from a title for use in compact index tables. Anchored so it only
# removes the case-number prefix — titles that legitimately contain a colon
# (e.g. "... (per-binary: NO_CHANGE)" or "experimental:: removed ...") keep the
# rest of the text intact.
_CASE_PREFIX_RE = re.compile(r"^\s*case\s*\d+[a-z]?\s*(?:[-—:]\s*)?", re.IGNORECASE)


def _short_title(title: str) -> str:
    """Title with any leading caseNN prefix removed (for index table rows)."""
    stripped = _CASE_PREFIX_RE.sub("", title, count=1).strip()
    return stripped or title


def _slug_title(slug: str) -> str:
    """A rule_slug (e.g. "exported-function-removed") as a reader-facing
    sentence-case title ("Exported function removed")."""
    words = slug.replace("-", " ")
    return words[:1].upper() + words[1:]


@dataclass
class Case:
    name: str
    title: str
    verdict: str
    category: str
    platforms: list[str]
    abi_break: bool
    api_break: bool
    bad_practice: bool
    expected_kinds: list[str]
    body: str  # README content with H1 stripped
    # Fact-vs-policy and kind-gap provenance (ADR-038-adjacent additions):
    # surfaced here so this metadata is visible in the generated docs without
    # hand-editing every case's README (see docs completeness review finding).
    underlying_fact: str | None = None
    policy_note: str | None = None
    detectability: str | None = None
    known_detector_gap: str | None = None
    known_kind_gap: str | None = None
    known_kind_gap_note: str | None = None
    # Taxonomy (docs/contribute/plans/examples-catalog-split.md, Phase 1/2):
    # surfaced on the case page so a reader can see "is this an atomic rule
    # or a composed scenario" and "is this a duplicate/variant of another
    # case" without leaving the docs site -- previously only visible in the
    # raw ground_truth.json taxonomy block (an external review's core
    # finding: "internally the repository understands the cases are
    # different... externally users still see a flat catalog").
    entity: str = "rule"
    scenario_kind: str | None = None
    operation: str = "compare"
    ecosystem: str = "generic"
    rule_slug: str | None = None
    variant_of: str | None = None
    relation_type: str | None = None
    relation_axis: str | None = None
    related_rules: list[str] = field(default_factory=list)


def _read_case(name: str, meta: dict, taxonomy: dict) -> Case:
    readme = example_catalog.case_dir(name) / "README.md"
    if not readme.exists():
        raise FileNotFoundError(f"missing per-case README: {readme}")
    text = readme.read_text(encoding="utf-8")
    m = re.match(r"\s*#\s+(.+?)\n", text)
    if not m:
        raise ValueError(f"{readme}: first line must be H1 (# Title)")
    title = m.group(1).strip()
    body = text[m.end() :].lstrip("\n")
    body = _rewrite_links(body)
    return Case(
        name=name,
        title=title,
        verdict=meta["expected"],
        category=meta["category"],
        platforms=list(meta.get("platforms", [])),
        abi_break=bool(meta.get("abi_break", False)),
        api_break=bool(meta.get("api_break", False)),
        bad_practice=bool(meta.get("bad_practice", False)),
        expected_kinds=list(meta.get("expected_kinds", [])),
        body=body,
        underlying_fact=meta.get("underlying_fact"),
        policy_note=meta.get("policy_note"),
        detectability=meta.get("detectability"),
        known_detector_gap=meta.get("known_detector_gap"),
        known_kind_gap=meta.get("known_kind_gap"),
        known_kind_gap_note=meta.get("known_kind_gap_note"),
        entity=taxonomy.get("entity", "rule"),
        scenario_kind=taxonomy.get("scenario_kind"),
        operation=taxonomy.get("operation", "compare"),
        ecosystem=taxonomy.get("ecosystem", "generic"),
        rule_slug=taxonomy.get("rule_slug"),
        variant_of=taxonomy.get("variant_of"),
        relation_type=taxonomy.get("relation_type"),
        relation_axis=taxonomy.get("relation_axis"),
        related_rules=list(taxonomy.get("related_rules") or []),
    )


def _rewrite_links(body: str) -> str:
    # Rewrite links from examples/<case>/README.md for generated docs. MkDocs
    # strict mode validates Markdown links against files under docs/, so source
    # files outside docs/ are rendered as code literals instead of links.
    def repl(m: re.Match) -> str:
        text, target = m.group(1), m.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return m.group(0)
        # A case README lives two levels below the repo root
        # (examples/<case>/README.md), so a link into docs/ from there is
        # "../../docs/..." — but a source file one level up (e.g. from
        # examples/README.md itself) could write "../docs/...". Match either
        # depth of leading "../" before "docs/".
        docs_target = re.match(r"^(?:\.\./)+docs/(.*)$", target)
        if docs_target:
            # docs_target.group(1) is docs/-relative (e.g. "reference/change-
            # kinds.md"), independent of where this generated page itself
            # lives. Compute the link relative to the *generated* page's
            # actual location (docs/reference/examples/), not a hard-coded
            # single "../" -- that assumption broke when examples/ moved one
            # level deeper, under reference/.
            url = posixpath.relpath(
                docs_target.group(1), start=DOCS_EXAMPLES_DIR_FROM_DOCS_ROOT
            )
            return f"[{text}]({url})"
        # Bare filenames like v1.c, app.cpp and ../ source-tree paths live
        # outside docs/; keep the reference visible without creating a checked
        # MkDocs link.
        if target.startswith("../") or ("/" not in target and "." in target):
            return f"`{text.strip('`')}`"
        return f"[{text}]({target})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, body)


def _classification_label(case: Case) -> str:
    if case.entity == "scenario":
        skind = SCENARIO_KIND_LABEL.get(case.scenario_kind, case.scenario_kind or "—")
        label = f"Scenario — {skind}"
    else:
        label = "Rule"
    if case.operation == "audit":
        label += " · audit"
    return label


def _rule_family_row(case: Case) -> str:
    """A rule-entity case's rule_slug, plus its duplicate/variant relation to
    a canonical case when it has one — the taxonomy this PR's own review
    finding asked for: "internally the repository understands the cases
    are different... externally users still see a flat catalog"."""
    if not case.rule_slug:
        return ""
    slug_link = f"[`{case.rule_slug}`](by-rule/{case.rule_slug}.md)"
    if not case.relation_type:
        return f"| **Rule family** | {slug_link} |\n"
    rel = RELATION_TYPE_LABEL.get(case.relation_type, case.relation_type)
    axis = f" ({case.relation_axis})" if case.relation_axis else ""
    canonical_link = (
        f"[{case.variant_of}]({case.variant_of}.md)" if case.variant_of else "—"
    )
    return f"| **Rule family** | {slug_link} — {rel}{axis} of {canonical_link} |\n"


def _related_rules_row(case: Case) -> str:
    if not case.related_rules:
        return ""
    links = ", ".join(f"[`{s}`](by-rule/{s}.md)" for s in case.related_rules)
    return f"| **Related rules** | {links} |\n"


def _meta_table(case: Case) -> str:
    vinfo = VERDICT_META[case.verdict]
    cinfo = CATEGORY_META[case.category]
    flags = []
    if case.abi_break:
        flags.append("ABI break")
    if case.api_break:
        flags.append("API break")
    if case.bad_practice:
        flags.append("Bad practice")
    flag_str = ", ".join(flags) if flags else "—"
    platforms = (
        ", ".join(PLATFORM_DISPLAY.get(p, p) for p in case.platforms)
        if case.platforms
        else "—"
    )
    kinds = (
        ", ".join(f"`{k}`" for k in case.expected_kinds) if case.expected_kinds else "—"
    )
    rows = (
        "| Field | Value |\n"
        "|-------|-------|\n"
        f"| **Verdict** | {vinfo['icon']} **{vinfo['label']}** |\n"
        f"| **Category** | {cinfo['label']} |\n"
        f"| **Classification** | {_classification_label(case)} |\n"
        f"| **Platforms** | {platforms} |\n"
        f"| **Flags** | {flag_str} |\n"
        f"| **Detected `ChangeKind`s** | {kinds} |\n"
        f"| **Source files** | `examples/{case.name}/` |\n"
    )
    if case.ecosystem != "generic":
        eco_link = f"[{ECOSYSTEM_LABEL.get(case.ecosystem, case.ecosystem)}](by-ecosystem/{case.ecosystem}.md)"
        rows += f"| **Ecosystem** | {eco_link} |\n"
    rows += _rule_family_row(case)
    rows += _related_rules_row(case)
    # Fact vs. policy: only present when ground_truth.json's `expected` is a
    # policy escalation of a weaker underlying compatibility fact (case30,
    # case95, case109-style) — see policy_note in ground_truth.json.
    if case.underlying_fact and case.underlying_fact != case.verdict:
        rows += f"| **Underlying fact** | {case.underlying_fact} (policy-escalated to {case.verdict}) |\n"
    # Detectability: only present for a case where no L0-L5 evidence tier
    # currently reaches the canonical verdict (case111-style known gap).
    if case.detectability == "none":
        rows += "| **Detectability** | None — no evidence tier currently proves this verdict (known detector gap) |\n"
    if case.known_detector_gap:
        rows += f"| **Known detector gap** | `{case.known_detector_gap}` |\n"
    # Kind gap: the verdict/severity is correct, but the specific calibrated
    # ChangeKind above is not what the tool currently emits (case06-style).
    if case.known_kind_gap:
        rows += f"| **Known kind gap** | `{case.known_kind_gap}` — verdict is correct; see note below |\n"
    return rows


def _source_links(case: Case) -> str:
    case_dir = example_catalog.case_dir(case.name)
    files = sorted(
        p.name for p in case_dir.iterdir() if p.is_file() and p.name != "README.md"
    )
    if not files:
        return ""
    lines = [f"- `{f}`" for f in files]
    return "## Source files\n\n" + "\n".join(lines) + "\n"


def _provenance_notes(case: Case) -> str:
    """Render policy_note/known_kind_gap_note prose when ground_truth.json sets
    them, so the fact-vs-policy or kind-gap distinction is visible in the
    generated docs rather than only in the raw JSON."""
    parts = []
    if case.policy_note:
        parts.append(f"**Policy note:** {case.policy_note}\n")
    if case.known_kind_gap_note:
        parts.append(f"**Known kind gap:** {case.known_kind_gap_note}\n")
    if not parts:
        return ""
    return "## Ground-truth provenance\n\n" + "\n".join(parts) + "\n"


def _render_case_page(case: Case) -> str:
    body = case.body.replace("__CASE__", case.name)
    see_also = [
        "[Examples overview](index.md)",
        f"[All {VERDICT_META[case.verdict]['label']} cases]"
        f"(by-verdict/{VERDICT_META[case.verdict]['slug']}.md)",
        f"[Category: {CATEGORY_META[case.category]['label']}](by-category/{case.category}.md)",
    ]
    if case.rule_slug:
        see_also.append(
            f"[Rule: {_slug_title(case.rule_slug)}](by-rule/{case.rule_slug}.md)"
        )
    if case.ecosystem != "generic":
        see_also.append(
            f"[Ecosystem: {ECOSYSTEM_LABEL.get(case.ecosystem, case.ecosystem)}]"
            f"(by-ecosystem/{case.ecosystem}.md)"
        )
    parts = [
        WARNING,
        f"# {case.title}\n\n",
        _meta_table(case),
        "\n",
        body.rstrip() + "\n\n",
        "---\n\n",
        _provenance_notes(case),
        _source_links(case),
        "\n",
        f"_See also: {' · '.join(see_also)}._\n",
    ]
    return "".join(parts)


def _verdict_counts(cases: list[Case]) -> dict[str, int]:
    out: dict[str, int] = defaultdict(int)
    for c in cases:
        out[c.verdict] += 1
    return out


def _case_sort_key(name: str) -> tuple[int, str]:
    """Order cases by their numeric index (case2 < case10 < case109), with the
    optional letter suffix (case26 < case26b) as the tiebreak. Lexical sorting
    would otherwise interleave case10 between case1 and case2."""
    m = re.match(r"case(\d+)([a-z]*)", name)
    if not m:
        return (10**9, name)
    return (int(m.group(1)), m.group(2))


def _case_row(case: Case) -> str:
    vinfo = VERDICT_META[case.verdict]
    return (
        f"| [{case.name}]({case.name}.md) "
        f"| {_short_title(case.title)} "
        f"| {vinfo['icon']} {vinfo['label']} "
        f"| {CATEGORY_META[case.category]['label']} |"
    )


def _render_index(cases: list[Case]) -> str:
    counts = _verdict_counts(cases)
    lines = [
        WARNING,
        "# Examples & Case Encyclopedia\n\n",
        f"This catalog covers **{len(cases)} cases** demonstrating real-world "
        "ABI/API change scenarios for C/C++ shared libraries. Most cases are a "
        "minimal compilable v1/v2 pair plus a consumer (`app.c`/`app.cpp`) that "
        "demonstrates the actual runtime effect; some build-mode cases ship only "
        "the v1/v2 sources plus a per-side `compile_commands.json`.\n\n",
        "Use this catalog to:\n\n",
        "- Learn **what kinds of changes break ABI** vs. which are safe.\n"
        "- See the **runtime failure mode** for each break (crash, wrong output, silent corruption…).\n"
        "- Look up the **mitigation pattern** for a specific change.\n"
        "- Cross-reference detected [`ChangeKind`s](../change-kinds.md) with concrete reproductions.\n\n",
        "> **Ground truth.** Expected verdicts and detected change kinds live in "
        "`examples/ground_truth.json` and are the "
        "single source of truth — these pages are generated from that file plus per-case "
        "`README.md` files under `examples/`.\n\n",
        "## Verdict distribution\n\n",
        "| Verdict | Count | What it means |\n",
        "|---------|-------|---------------|\n",
    ]
    for v in VERDICT_ORDER:
        info = VERDICT_META[v]
        lines.append(
            f"| {info['icon']} [{info['label']}](by-verdict/{info['slug']}.md) "
            f"| {counts.get(v, 0)} | {info['blurb']} |\n"
        )
    lines.append("\n## How to read a case page\n\n")
    lines.append(
        "Each case page starts with a metadata table (verdict, category, "
        "platforms, detected change kinds) followed by:\n\n"
        "- **What changes / what breaks** — the source diff between v1 and v2.\n"
        "- **Why abicheck (or abidiff/ABICC) catches it** — detection mechanism.\n"
        "- **Real Failure Demo** — exact shell commands that reproduce the runtime effect.\n"
        "- **How to fix** — the mitigation pattern, where the README documents one.\n"
        "- **Real-world example** — historical occurrences in widely-used libraries.\n"
        "- **References** — links to relevant standards, manuals, and abicheck source.\n\n"
        "Source files (`v1.*`, `v2.*`, `app.*`, `CMakeLists.txt`) are listed at the bottom of every page.\n\n"
    )
    lines.append("## Browse by category\n\n")
    by_cat: dict[str, list[Case]] = defaultdict(list)
    for c in cases:
        by_cat[c.category].append(c)
    lines.append("| Category | Cases | What it covers |\n")
    lines.append("|----------|-------|----------------|\n")
    for cat in CATEGORY_ORDER:
        info = CATEGORY_META[cat]
        n = len(by_cat.get(cat, []))
        lines.append(
            f"| [{info['label']}](by-category/{cat}.md) | {n} | {info['blurb']} |\n"
        )
    lines.append("\n## Browse by rule\n\n")
    lines.append(
        "Several cases demonstrate the same atomic compatibility rule under "
        "a different condition (variant) or restate it with no distinguishing "
        "condition (duplicate); a scenario composes several rules at once. "
        "See [Rule families](by-rule/index.md) for the complete grouping, and "
        "[Rule coverage](../../contribute/catalog-coverage.md) for the "
        "aggregate rule/variant/duplicate counts.\n\n"
    )
    lines.append("\n## Browse by ecosystem\n\n")
    by_eco: dict[str, list[Case]] = defaultdict(list)
    for c in cases:
        by_eco[c.ecosystem].append(c)
    lines.append("| Ecosystem | Cases |\n")
    lines.append("|-----------|-------|\n")
    for eco in ECOSYSTEM_ORDER:
        n = len(by_eco.get(eco, []))
        lines.append(f"| [{ECOSYSTEM_LABEL[eco]}](by-ecosystem/{eco}.md) | {n} |\n")
    lines.append("\n## All cases\n\n")
    lines.append(
        "> **Gaps in the numbering are expected.** Some case numbers "
        "(e.g. 84, 90–93) are **multi-library bundle cases** that are not part "
        "of this single-library catalog; they are documented in the repository "
        "under `examples/` and indexed in `examples/README.md`. The list below "
        "is sorted by case number.\n\n"
    )
    lines.append("| Case | Title | Verdict | Category |\n")
    lines.append("|------|-------|---------|----------|\n")
    for c in sorted(cases, key=lambda c: _case_sort_key(c.name)):
        lines.append(_case_row(c) + "\n")
    return "".join(lines)


def _render_group_index(
    title: str,
    blurb: str,
    cases: list[Case],
    *,
    backlink: str = "../index.md",
) -> str:
    lines = [
        WARNING,
        f"# {title}\n\n",
        blurb + "\n\n",
        f"_{len(cases)} case(s)._ [← back to all examples]({backlink})\n\n",
    ]
    if not cases:
        lines.append("_No cases in this group._\n")
        return "".join(lines)
    lines.append("| Case | Title | Verdict | Category |\n")
    lines.append("|------|-------|---------|----------|\n")
    for c in sorted(cases, key=lambda c: _case_sort_key(c.name)):
        vinfo = VERDICT_META[c.verdict]
        lines.append(
            f"| [{c.name}](../{c.name}.md) "
            f"| {_short_title(c.title)} "
            f"| {vinfo['icon']} {vinfo['label']} "
            f"| {CATEGORY_META[c.category]['label']} |\n"
        )
    return "".join(lines)


# ---------------------------------------------------------------------------
# "By Rule" navigation (taxonomy Phase 1/2): one page per canonical rule_slug
# grouping its own canonical case, its confirmed duplicates and variants
# (relation_type/relation_axis), and every scenario that composes it via
# related_rules -- the "canonical rule page groups its complete family" view
# the examples-catalog-split review asked for, generated from the taxonomy
# rather than owning any fixture's filesystem location.
# ---------------------------------------------------------------------------


@dataclass
class RuleFamily:
    slug: str
    canonical: Case | None
    duplicates: list[Case]
    variants: list[Case]  # (case, axis) pairs kept as Case; axis on case.relation_axis
    scenarios: list[Case]
    # Multi-library bundle scenarios (ADR-023) that compose this rule too --
    # kept separate from `scenarios` because bundle cases use a different
    # ground-truth shape (no single `expected` verdict) and never get a
    # generated case page of their own (`_load_cases()` excludes them), so
    # there's no `../<name>.md` to link to. (name, short_title) pairs, not
    # `Case` objects -- a Codex review found the original cut left these
    # relationships (e.g. case90/92/93 -> exported-function-removed) visible
    # in ground_truth.json and the coverage report but silently absent here.
    bundle_scenarios: list[tuple[str, str]]


def _bundle_scenario_related_rules() -> dict[str, list[tuple[str, str]]]:
    """rule_slug -> [(bundle_case_name, short_title), ...] for every
    multi-library bundle case's own `related_rules` -- read directly from
    the taxonomy block, since `_load_cases()` deliberately excludes bundle
    cases (see its own docstring) before any Case-based grouping runs."""
    data = json.loads(GROUND_TRUTH.read_text(encoding="utf-8"))
    verdicts: dict[str, dict] = data["verdicts"]
    taxonomy: dict[str, dict] = data.get("taxonomy") or {}
    out: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for name, meta in verdicts.items():
        if not (meta.get("category") == "bundle" or meta.get("bundle") is True):
            continue
        entry = taxonomy.get(name) or {}
        for slug in entry.get("related_rules") or []:
            out[slug].append((name, _case_title(name)))
    return out


def _build_rule_families(cases: list[Case]) -> dict[str, RuleFamily]:
    families: dict[str, RuleFamily] = {}

    def _get(slug: str) -> RuleFamily:
        return families.setdefault(slug, RuleFamily(slug, None, [], [], [], []))

    for c in cases:
        if c.entity != "rule" or not c.rule_slug:
            continue
        fam = _get(c.rule_slug)
        if c.relation_type is None:
            fam.canonical = c
        elif c.relation_type == "duplicate":
            fam.duplicates.append(c)
        elif c.relation_type == "variant":
            fam.variants.append(c)
    for c in cases:
        if c.entity != "scenario":
            continue
        for slug in c.related_rules:
            _get(slug).scenarios.append(c)
    for slug, bundles in _bundle_scenario_related_rules().items():
        _get(slug).bundle_scenarios.extend(bundles)
    return families


def _render_rule_family_page(fam: RuleFamily) -> str:
    lines = [
        WARNING,
        f"# Rule: {_slug_title(fam.slug)}\n\n",
        f"_Canonical rule slug:_ `{fam.slug}`. [← back to all rules](index.md)\n\n",
    ]
    if fam.canonical is not None:
        c = fam.canonical
        vinfo = VERDICT_META[c.verdict]
        lines.append("## Canonical demonstration\n\n")
        lines.append(
            f"- [{c.name}](../{c.name}.md) — {_short_title(c.title)} "
            f"({vinfo['icon']} {vinfo['label']})\n\n"
        )
    else:
        lines.append(
            "## Canonical demonstration\n\n"
            "_No single-library case demonstrates this rule alone yet — "
            "referenced only by the scenario(s) below._\n\n"
        )
    if fam.duplicates:
        lines.append(
            "## Duplicate fixtures\n\n"
            "_Same demonstration restated with no distinguishing condition — "
            "not additional robustness coverage._\n\n"
        )
        for c in sorted(fam.duplicates, key=lambda c: _case_sort_key(c.name)):
            lines.append(f"- [{c.name}](../{c.name}.md) — {_short_title(c.title)}\n")
        lines.append("\n")
    if fam.variants:
        lines.append(
            "## Variants\n\n"
            "_The same rule demonstrated under a different condition._\n\n"
        )
        for c in sorted(fam.variants, key=lambda c: _case_sort_key(c.name)):
            axis = f" ({c.relation_axis})" if c.relation_axis else ""
            lines.append(
                f"- [{c.name}](../{c.name}.md) — {_short_title(c.title)}{axis}\n"
            )
        lines.append("\n")
    if fam.scenarios:
        lines.append("## Used by scenarios\n\n")
        for c in sorted(fam.scenarios, key=lambda c: _case_sort_key(c.name)):
            lines.append(f"- [{c.name}](../{c.name}.md) — {_short_title(c.title)}\n")
        lines.append("\n")
    if fam.bundle_scenarios:
        lines.append(
            "## Used by multi-library bundle scenarios\n\n"
            "_ADR-023 bundle cases aren't part of this single-library "
            "catalog (see `examples/README.md`), so these aren't linked "
            "pages here — see the case's own README under `examples/`._\n\n"
        )
        for name, title in sorted(fam.bundle_scenarios):
            lines.append(f"- `{name}` — {title}\n")
        lines.append("\n")
    return "".join(lines)


def _render_by_rule_index(families: dict[str, RuleFamily]) -> str:
    lines = [
        WARNING,
        "# Rule families\n\n",
        "Every atomic, ecosystem-neutral compatibility rule the catalog "
        "demonstrates or references, deduplicated across duplicate/variant "
        "restatements and composed scenarios. See "
        "[Rule coverage](../../../contribute/catalog-coverage.md) for the "
        "aggregate counts this table is drawn from. "
        "[← back to all examples](../index.md)\n\n",
        "| Rule | Canonical case | Duplicate(s) | Variant(s) | Scenario(s) | Bundle scenario(s) |\n",
        "|---|---|---|---|---|---|\n",
    ]
    for slug in sorted(families):
        fam = families[slug]
        canonical_cell = (
            f"[{fam.canonical.name}](../{fam.canonical.name}.md)"
            if fam.canonical
            else "—"
        )
        dup_cell = (
            ", ".join(f"[{c.name}](../{c.name}.md)" for c in fam.duplicates) or "—"
        )
        var_cell = ", ".join(f"[{c.name}](../{c.name}.md)" for c in fam.variants) or "—"
        scenario_cell = (
            ", ".join(f"[{c.name}](../{c.name}.md)" for c in fam.scenarios) or "—"
        )
        bundle_cell = (
            ", ".join(f"`{name}`" for name, _title in sorted(fam.bundle_scenarios))
            or "—"
        )
        lines.append(
            f"| [`{slug}`]({slug}.md) | {canonical_cell} | {dup_cell} | "
            f"{var_cell} | {scenario_cell} | {bundle_cell} |\n"
        )
    return "".join(lines)


# ---------------------------------------------------------------------------
# examples/README.md catalog (the GitHub-facing index, not the docs site).
#
# Three regions are generated between sentinel comments so the headline count,
# verdict distribution, and 126-row case index can't drift from ground_truth.
# Bundle cases (skipped by the docs-site generator) ARE included here, since the
# README indexes the whole catalog.
# ---------------------------------------------------------------------------


@dataclass
class ReadmeEntry:
    num: str  # case number as it appears in the dir name, e.g. "01", "26b", "110"
    name: str
    title: str
    category: str
    verdict: str  # ground_truth "expected", or "BUNDLE" for multi-library cases
    bad_practice: bool


def _case_title(name: str) -> str:
    """Short H1 title of a per-case README (caseNN prefix stripped)."""
    text = (example_catalog.case_dir(name) / "README.md").read_text(encoding="utf-8")
    m = re.match(r"\s*#\s+(.+?)\n", text)
    if not m:
        raise ValueError(f"examples/{name}/README.md: first line must be an H1")
    return _short_title(m.group(1).strip())


def _load_readme_entries() -> list[ReadmeEntry]:
    data = json.loads(GROUND_TRUTH.read_text(encoding="utf-8"))
    entries: list[ReadmeEntry] = []
    for name, meta in data["verdicts"].items():
        m = re.match(r"case(\d+[a-z]?)", name)
        if not m:
            raise ValueError(f"unexpected case name {name!r}")
        category = meta.get("category")
        verdict = "BUNDLE" if category == "bundle" else meta["expected"]
        entries.append(
            ReadmeEntry(
                num=m.group(1),
                name=name,
                title=_case_title(name),
                category=category,
                verdict=verdict,
                bad_practice=bool(meta.get("bad_practice", False)),
            )
        )
    entries.sort(key=lambda e: (int(re.match(r"(\d+)", e.num).group(1)), e.name))
    return entries


def _render_readme_headline(entries: list[ReadmeEntry]) -> str:
    n_total = len(entries)
    n_bundle = sum(1 for e in entries if e.category == "bundle")
    n_single = n_total - n_bundle
    return (
        f"This directory contains **{n_total} cases** "
        f"({n_single} single-library + {n_bundle} multi-library bundle cases, "
        "the latter tracked under "
        "[ADR-023](../docs/contribute/adr/023-bundle-aware-multi-binary-analysis.md)) "
        "demonstrating real-world ABI/API break scenarios. Most cases are a "
        "minimal, compilable C/C++ example with:"
    )


def _render_readme_distribution(entries: list[ReadmeEntry]) -> str:
    single = [e for e in entries if e.category != "bundle"]
    n_bundle = len(entries) - len(single)
    by_verdict = Counter(e.verdict for e in single)
    by_category = Counter(e.category for e in single)
    rows = [
        ("BREAKING", by_verdict.get("BREAKING", 0), "`BREAKING_KINDS`", "🔴"),
        ("API_BREAK", by_verdict.get("API_BREAK", 0), "`API_BREAK_KINDS`", "🟠"),
        (
            "COMPATIBLE_WITH_RISK",
            by_verdict.get("COMPATIBLE_WITH_RISK", 0),
            "`RISK_KINDS`",
            "🟡",
        ),
        (
            "COMPATIBLE (addition)",
            by_category.get("addition", 0),
            "`ADDITION_KINDS`",
            "🟢",
        ),
        (
            "COMPATIBLE (quality)",
            by_category.get("quality", 0),
            "`QUALITY_KINDS`",
            "🟡",
        ),
        ("NO_CHANGE", by_verdict.get("NO_CHANGE", 0), "—", "✅"),
        (
            "Bundle (multi-binary)",
            n_bundle,
            "see [ADR-023](../docs/contribute/adr/023-bundle-aware-multi-binary-analysis.md)",
            "🔵",
        ),
    ]
    lines = [
        "| Verdict | Count | `checker_policy.py` set | Icon |",
        "|---------|-------|-------------------------|------|",
    ]
    lines += [
        f"| {label} | {count} | {kset} | {icon} |" for label, count, kset, icon in rows
    ]
    return "\n".join(lines)


def _render_readme_index(entries: list[ReadmeEntry]) -> str:
    lines = [
        "| # | Case | Category | abicheck verdict |",
        "|---|------|----------|-----------------|",
    ]
    for e in entries:
        icon = VERDICT_META[e.verdict]["icon"] if e.verdict in VERDICT_META else "🔵"
        cell = f"{icon} {e.verdict}"
        if e.bad_practice:
            cell += " (bad practice)"
        lines.append(
            f"| [{e.num}]({e.name}/README.md) | {e.title} "
            f"| {README_CATEGORY_LABEL[e.category]} | {cell} |"
        )
    return "\n".join(lines)


def _splice_generated(text: str, marker: str, inner: str) -> str:
    """Replace the text between BEGIN/END GENERATED sentinels for ``marker``."""
    begin = re.search(rf"<!-- BEGIN GENERATED: {re.escape(marker)}[^\n]*-->\n", text)
    end = re.search(rf"\n<!-- END GENERATED: {re.escape(marker)} -->", text)
    if not begin or not end or begin.end() > end.start():
        raise ValueError(
            f"examples/README.md: missing/!ordered sentinels for {marker!r}"
        )
    return text[: begin.end()] + inner + text[end.start() :]


def _render_examples_readme(text: str, entries: list[ReadmeEntry]) -> str:
    text = _splice_generated(text, "catalog-headline", _render_readme_headline(entries))
    text = _splice_generated(
        text, "verdict-distribution", _render_readme_distribution(entries)
    )
    text = _splice_generated(text, "case-index", _render_readme_index(entries))
    return text


def _load_cases() -> list[Case]:
    data = json.loads(GROUND_TRUTH.read_text(encoding="utf-8"))
    taxonomy_block: dict[str, dict] = data.get("taxonomy") or {}
    cases = []
    for name, meta in data["verdicts"].items():
        # Bundle cases (ADR-023) are multi-library and use a different
        # ground-truth shape (expected=null, per-library verdicts under
        # library_assertions, bundle-level verdict under
        # canonical aggregate expected verdict). They have their own README files
        # but don't map onto the per-case verdict-page generator; skip
        # them here. The bundle index belongs in a follow-up doc page.
        if meta.get("category") == "bundle" or meta.get("bundle") is True:
            continue
        if meta["expected"] not in VERDICT_META:
            raise ValueError(f"{name}: unknown verdict {meta['expected']!r}")
        if meta["category"] not in CATEGORY_META:
            raise ValueError(f"{name}: unknown category {meta['category']!r}")
        cases.append(_read_case(name, meta, taxonomy_block.get(name, {})))
    return cases


def _write(path: Path, content: str) -> None:
    # Write in binary with LF newlines so the on-disk tree is byte-stable across
    # platforms — required for the --check drift gate to work on Windows.
    path.write_bytes(content.encode("utf-8"))


def _normalize(data: bytes) -> bytes:
    # Strip BOM and normalize CRLF/CR → LF so the comparator survives a Windows
    # checkout where core.autocrlf might have rewritten committed files.
    if data.startswith(b"\xef\xbb\xbf"):
        data = data[3:]
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def _files_match(a: Path, b: Path) -> bool:
    return _normalize(a.read_bytes()) == _normalize(b.read_bytes())


def _write_tree(out_dir: Path, cases: list[Case]) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    (out_dir / "by-verdict").mkdir()
    (out_dir / "by-category").mkdir()
    (out_dir / "by-rule").mkdir()
    (out_dir / "by-ecosystem").mkdir()

    _write(out_dir / "index.md", _render_index(cases))

    by_verdict: dict[str, list[Case]] = defaultdict(list)
    by_category: dict[str, list[Case]] = defaultdict(list)
    by_ecosystem: dict[str, list[Case]] = defaultdict(list)
    for c in cases:
        by_verdict[c.verdict].append(c)
        by_category[c.category].append(c)
        by_ecosystem[c.ecosystem].append(c)

    for v in VERDICT_ORDER:
        info = VERDICT_META[v]
        _write(
            out_dir / "by-verdict" / f"{info['slug']}.md",
            _render_group_index(
                title=f"{info['icon']} {info['label']} cases",
                blurb=info["blurb"],
                cases=by_verdict.get(v, []),
            ),
        )

    for cat in CATEGORY_ORDER:
        info = CATEGORY_META[cat]
        _write(
            out_dir / "by-category" / f"{cat}.md",
            _render_group_index(
                title=f"{info['label']} cases",
                blurb=info["blurb"],
                cases=by_category.get(cat, []),
            ),
        )

    for eco in ECOSYSTEM_ORDER:
        info_label = ECOSYSTEM_LABEL[eco]
        _write(
            out_dir / "by-ecosystem" / f"{eco}.md",
            _render_group_index(
                title=f"{info_label} cases",
                blurb=f"Cases modeling the {info_label} ecosystem.",
                cases=by_ecosystem.get(eco, []),
            ),
        )

    rule_families = _build_rule_families(cases)
    _write(out_dir / "by-rule" / "index.md", _render_by_rule_index(rule_families))
    for slug, fam in rule_families.items():
        _write(out_dir / "by-rule" / f"{slug}.md", _render_rule_family_page(fam))

    for c in cases:
        _write(out_dir / f"{c.name}.md", _render_case_page(c))


def _trees_match(a: Path, b: Path) -> bool:
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.funny_files:
        return False
    for f in cmp.common_files:
        if not _files_match(a / f, b / f):
            return False
    for sub in cmp.common_dirs:
        if not _trees_match(a / sub, b / sub):
            return False
    return True


def _print_diff(expected: Path, actual: Path) -> None:
    cmp = filecmp.dircmp(expected, actual)
    if cmp.left_only:
        print(f"  missing in {actual}: {cmp.left_only}", file=sys.stderr)
    if cmp.right_only:
        print(f"  stale in {actual}: {cmp.right_only}", file=sys.stderr)
    diffs = [f for f in cmp.common_files if not _files_match(expected / f, actual / f)]
    if diffs:
        print(f"  changed: {diffs}", file=sys.stderr)
    for sub in cmp.common_dirs:
        _print_diff(expected / sub, actual / sub)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if the on-disk tree differs from what would be generated.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    cases = _load_cases()
    readme_entries = _load_readme_entries()
    readme_current = EXAMPLES_README.read_text(encoding="utf-8")
    readme_rendered = _render_examples_readme(readme_current, readme_entries)

    if args.check:
        ok = True
        with tempfile.TemporaryDirectory() as tmp:
            tmp_out = Path(tmp) / "examples"
            _write_tree(tmp_out, cases)
            if not DOCS_EXAMPLES_DIR.exists() or not _trees_match(
                tmp_out, DOCS_EXAMPLES_DIR
            ):
                print(
                    "docs/reference/examples/ is out of date. Run: python scripts/gen_examples_docs.py",
                    file=sys.stderr,
                )
                if DOCS_EXAMPLES_DIR.exists():
                    _print_diff(tmp_out, DOCS_EXAMPLES_DIR)
                ok = False
        if _normalize(readme_rendered.encode("utf-8")) != _normalize(
            readme_current.encode("utf-8")
        ):
            print(
                "examples/README.md generated regions are out of date. "
                "Run: python scripts/gen_examples_docs.py",
                file=sys.stderr,
            )
            ok = False
        if not ok:
            return 1
        print(
            f"docs/reference/examples/ and examples/README.md are up to date ({len(cases)} cases)."
        )
        return 0

    _write_tree(DOCS_EXAMPLES_DIR, cases)
    _write(EXAMPLES_README, readme_rendered)
    print(
        f"Generated {len(cases)} case pages in {DOCS_EXAMPLES_DIR.relative_to(ROOT)}/ "
        f"and refreshed examples/README.md ({len(readme_entries)} catalog rows)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
