#!/usr/bin/env python3
"""Render docs/contribute/abi-api-failure-taxonomy.md from its manifest.

Phase 1 of `docs/contribute/plans/abi-api-knowledge-and-corpus.md`. The
hand-authored source of truth is `docs/_meta/abi-failure-taxonomy.json`: a
domain-keyed enumeration of the known ways a compiled or source-level
compatibility contract can break, deliberately independent of abicheck's own
`ChangeKind` registry, of its evidence tiers, and of the `catalog/` corpus.
This script is the rendering half only -- it decides nothing about the
taxonomy's content, so a leaf is added by editing the manifest and running
this generator, never by editing the page.

It also validates the manifest before rendering, which is what stops the ids
Phase 2/3 will key everything off from silently drifting: every branch and
leaf id must be lowercase kebab-case, every leaf id must be prefixed by its
own branch, ids must be unique across the whole file, every required field
must be non-empty, and every `platforms`/`languages`/`surface` value must come
from the manifest's own declared vocabularies. A validation failure is an
error, not a warning -- the page is not written.

Usage:

    python scripts/gen_abi_failure_taxonomy_doc.py            # write the page
    python scripts/gen_abi_failure_taxonomy_doc.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "docs" / "_meta" / "abi-failure-taxonomy.json"
OUT_PATH = ROOT / "docs" / "contribute" / "abi-api-failure-taxonomy.md"

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/gen_abi_failure_taxonomy_doc.py from "
    "docs/_meta/abi-failure-taxonomy.json -- do not edit by hand. Run "
    "`python scripts/gen_abi_failure_taxonomy_doc.py` to regenerate. -->"
)

_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

_REQUIRED_LEAF_FIELDS = ("id", "title", "description", "platforms", "languages", "surface")


class ManifestError(Exception):
    """The taxonomy manifest is not internally consistent."""


def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def validate(manifest: dict[str, Any]) -> None:
    """Raise ``ManifestError`` on the first structural problem found."""

    vocab = manifest.get("vocabularies") or {}
    platforms = set(vocab.get("platforms") or ())
    languages = set(vocab.get("languages") or ())
    surfaces = set(vocab.get("surface") or ())
    if not (platforms and languages and surfaces):
        raise ManifestError("vocabularies.platforms/languages/surface must all be non-empty")

    branches = manifest.get("branches") or []
    if not branches:
        raise ManifestError("no branches declared")

    seen_ids: set[str] = set()
    for branch in branches:
        bid = branch.get("id", "")
        if not _SLUG_RE.match(bid):
            raise ManifestError(f"branch id {bid!r} is not lowercase kebab-case")
        if bid in seen_ids:
            raise ManifestError(f"duplicate id {bid!r}")
        seen_ids.add(bid)
        for field in ("title", "summary"):
            if not (branch.get(field) or "").strip():
                raise ManifestError(f"branch {bid!r}: empty {field}")
        leaves = branch.get("leaves") or []
        if not leaves:
            raise ManifestError(f"branch {bid!r}: no leaves")
        for leaf in leaves:
            for field in _REQUIRED_LEAF_FIELDS:
                if not leaf.get(field):
                    raise ManifestError(f"leaf {leaf.get('id')!r}: empty {field}")
            lid = leaf["id"]
            if lid in seen_ids:
                raise ManifestError(f"duplicate id {lid!r}")
            seen_ids.add(lid)
            prefix, _, tail = lid.partition(".")
            if prefix != bid or not _SLUG_RE.match(tail):
                raise ManifestError(
                    f"leaf id {lid!r} must be '<branch id>.<lowercase-kebab-slug>'"
                )
            unknown_platforms = set(leaf["platforms"]) - platforms
            if unknown_platforms:
                raise ManifestError(f"leaf {lid!r}: unknown platform(s) {sorted(unknown_platforms)}")
            unknown_languages = set(leaf["languages"]) - languages
            if unknown_languages:
                raise ManifestError(f"leaf {lid!r}: unknown language(s) {sorted(unknown_languages)}")
            if leaf["surface"] not in surfaces:
                raise ManifestError(f"leaf {lid!r}: unknown surface {leaf['surface']!r}")
            for field in ("description", "title"):
                if "|" in leaf[field]:
                    raise ManifestError(f"leaf {lid!r}: '|' in {field} would break the rendered table")


_SURFACE_LABEL = {
    "binary": "Binary",
    "source": "Source",
    "both": "Binary + source",
}


def _cell(values: list[str]) -> str:
    return ", ".join(values)


def _slugify(text: str) -> str:
    """Reproduce Python-Markdown's default heading slug.

    The branch index links to each branch's own ``##`` heading, and mkdocs is
    built with ``--strict``, so the anchor has to match what the ``toc``
    extension will actually emit -- a naive lowercase-and-hyphenate would get
    ``4. C++ object model`` wrong.
    """

    value = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[-\s]+", "-", value)


def render(manifest: dict[str, Any]) -> str:
    branches = manifest["branches"]
    n_leaves = sum(len(b["leaves"]) for b in branches)

    out: list[str] = [
        GENERATED_MARKER,
        "",
        "# ABI/API failure taxonomy",
        "",
        "This page enumerates the known ways a compiled or source-level compatibility contract can break, organised the way the domain is organised rather than the way any one tool models it. It is Phase 1 of [ABI/API knowledge and corpus](plans/abi-api-knowledge-and-corpus.md), whose later phases map abicheck's detectors, the `catalog/` calibration corpus, and the educational pages under `docs/learn/` onto the ids below and then classify each mechanism's coverage.",
        "",
        f"It holds **{n_leaves} leaf mechanisms** across **{len(branches)} top-level branches**.",
        "",
        "The hand-authored source of truth is `docs/_meta/abi-failure-taxonomy.json`. Edit that file and run `python scripts/gen_abi_failure_taxonomy_doc.py` to regenerate this page; the generator validates the manifest's ids and vocabularies before writing, so a malformed entry fails rather than rendering.",
        "",
        "## What this is, and what it deliberately is not",
        "",
        "The taxonomy is keyed by the domain: by the mechanism a maintainer's edit or build setting actually triggers, the way a reader with no tooling installed would organise the knowledge. It is **not** keyed by change kind, by evidence tier, or by the shape of the existing corpus. That independence is the whole point — a taxonomy defined in a tool's own image can only ever report itself as fully covered, so it could never locate a gap on either side.",
        "",
        "Three further limits are worth stating plainly:",
        "",
        "- **It is a judgment call.** There is no canonical, machine-checkable list of all ABI/API failure mechanisms to diff this against. Treat it as a reviewable enumeration that later phases will revise as they find gaps, not as a completeness claim it cannot support.",
        "- **It says nothing about detectability.** A leaf being present here is not a claim that abicheck detects it, that any evidence tier could, or that it is in scope at all. Applicability to abicheck's stated scope, accepted limitations, and product gaps are each a separate, ordered judgment made in Phase 3.",
        "- **It says nothing about severity.** Whether a mechanism is breaking, risky, or benign depends on the contract the artifact is judged against — which consumers exist, what the project promised, and what the platform guarantees. Several leaves below are safe under one contract and fatal under another, and the description says so rather than assigning a verdict.",
        "",
        "## How to read a row",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| **ID** | The stable id, `<branch>.<leaf>`. Later phases key their mappings off these strings, so an id is never reused for a different mechanism: a mechanism that is split gets new ids for the parts, and a retired one stays retired. |",
        "| **Mechanism** | A short name for the change a maintainer would recognise having made. |",
        "| **Description** | What changes, and why a consumer notices. |",
        "| **Platforms** | The binary formats the mechanism applies to. `any` means it is format-independent, which is typical of the source-level branches. |",
        "| **Languages** | The language or ecosystem contract the mechanism belongs to. |",
        "| **Breaks** | Whether the mechanism can break an already-built consumer (`Binary`), a consumer recompiling from source (`Source`), or both. This is the *possible* reach of the mechanism, not a verdict for a particular occurrence. |",
        "",
        "## Branches",
        "",
        "| # | Branch | ID | Leaves |",
        "|---|---|---|---|",
    ]

    for n, branch in enumerate(branches, start=1):
        anchor = _slugify(f"{n}. {branch['title']}")
        out.append(
            f"| {n} | [{branch['title']}](#{anchor}) | `{branch['id']}` | {len(branch['leaves'])} |"
        )

    for n, branch in enumerate(branches, start=1):
        out += [
            "",
            f"## {n}. {branch['title']}",
            "",
            f"`{branch['id']}` — {branch['summary']}",
            "",
            "| ID | Mechanism | Description | Platforms | Languages | Breaks |",
            "|---|---|---|---|---|---|",
        ]
        for leaf in branch["leaves"]:
            description = leaf["description"]
            if leaf.get("notes"):
                description = f"{description} *{leaf['notes']}*"
            out.append(
                "| `{id}` | {title} | {description} | {platforms} | {languages} | {surface} |".format(
                    id=leaf["id"],
                    title=leaf["title"],
                    description=description,
                    platforms=_cell(leaf["platforms"]),
                    languages=_cell(leaf["languages"]),
                    surface=_SURFACE_LABEL[leaf["surface"]],
                )
            )

    out += [
        "",
        "## Boundaries between branches",
        "",
        "Some mechanisms could plausibly sit in more than one branch. The taxonomy resolves those consistently rather than duplicating a leaf, and the rule is worth stating so a later phase does not re-litigate it per case:",
        "",
        "- **Per-symbol facts belong to `symbol-identity`; library-wide facts belong to `dynamic-linker-contract`.** Which version node a single symbol presents is symbol identity; whether the library versions its symbols at all, and which nodes exist, is the linker contract.",
        "- **A library's own break belongs to its branch; a dependency's break reaching consumers through it belongs to `dependency-abi`.** The same mechanism (a SONAME bump, a raised version floor) therefore appears once for the artifact under analysis and once for what it links against.",
        "- **A change to a declaration belongs to its own branch; a change to the boundary belongs to `export-public-surface-contract`.** Removing a function is symbol identity; a function being declared as supported while not being exported at all is a surface-contract mechanism.",
        "- **Toolchain and target facts stay in `toolchain-platform-abi` even when their effect is a layout or calling change.** The distinguishing question is whether the source declaration changed: if nothing in the interface was edited and the artifact still differs, the mechanism is a toolchain one.",
        "- **`header-only-compatibility` is about libraries with no compiled artifact at all**, not about any header-defined entity. An inline function in a compiled library is `inline-template-source-abi`.",
        "",
        "## Relationship to the rest of the repository",
        "",
        "- [`docs/learn/`](../learn/abi-api-handling.md) explains these mechanisms for a reader, tool-independently. Phase 2 records which page explains which leaf.",
        "- `catalog/` demonstrates mechanisms as executable fixtures with pinned verdicts. Phase 2 records which case demonstrates which leaf; Phase 4 adds paired positive/negative controls where a leaf has none.",
        "- The `ChangeKind` registry and [detector spec](../reference/detector-spec.md) state what abicheck observes and at which minimum evidence. Phase 2 records the mapping; Phase 3 turns the three mappings into one coverage status per leaf.",
        "- [`vision.md`](vision.md) states which platforms, languages, and ecosystems are in scope. That scope, not this taxonomy, decides whether a leaf is applicable at all.",
        "",
    ]

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if regeneration would change the committed page",
    )
    args = parser.parse_args(argv)

    manifest = load_manifest()
    try:
        validate(manifest)
    except ManifestError as exc:
        print(f"{MANIFEST_PATH.relative_to(ROOT)}: {exc}", file=sys.stderr)
        return 1

    new_content = render(manifest)

    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else None
        if current != new_content:
            print(
                f"{OUT_PATH.relative_to(ROOT)} is stale -- run "
                "`python scripts/gen_abi_failure_taxonomy_doc.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT_PATH.relative_to(ROOT)} is up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(new_content, encoding="utf-8")
    print(
        f"Wrote {OUT_PATH.relative_to(ROOT)} "
        f"({sum(len(b['leaves']) for b in manifest['branches'])} leaves)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
