#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_action_reference.py — exhaustive GitHub Action inputs/outputs reference,
generated from `action.yml` instead of hand-copied.

`action.yml`'s `description:`/`required:`/`default:` fields are already the
fact owner for every input and output; `docs/user-guide/github-action.md`
previously restated them by hand across several prose subsections, an
unmarked second copy that drifts the moment an input is added, renamed, or
gets a new default. This generator makes `docs/reference/github-action-
inputs.md` the single generated, exhaustive view — `github-action.md` stays
the narrative/task-owner page (setup, recipes, mode/input compatibility) and
links here for the full per-field table instead of re-deriving it.

Usage:
    python scripts/gen_action_reference.py            # write the file
    python scripts/gen_action_reference.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_DIR = Path(__file__).resolve().parent.parent
ACTION_YML = REPO_DIR / "action.yml"
OUT_PATH = REPO_DIR / "docs" / "reference" / "github-action-inputs.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_action_reference.py — do not edit by hand. "
    "Run `python scripts/gen_action_reference.py` to regenerate. -->"
)


def _clean(text: object) -> str:
    """Collapse a YAML folded/literal scalar's internal newlines into single
    spaces and escape pipe characters so it's safe as one Markdown table
    cell."""
    if text is None:
        return ""
    return " ".join(str(text).split()).replace("|", "\\|")


def build_rows(action: dict) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    inputs = action.get("inputs") or {}
    outputs = action.get("outputs") or {}
    input_rows = [
        {
            "name": name,
            "required": "yes" if spec.get("required") else "no",
            "default": _clean(spec.get("default")) or "—",
            "description": _clean(spec.get("description")),
        }
        for name, spec in inputs.items()
    ]
    output_rows = [
        {"name": name, "description": _clean(spec.get("description"))}
        for name, spec in outputs.items()
    ]
    return input_rows, output_rows


def render(action: dict) -> str:
    input_rows, output_rows = build_rows(action)
    lines = [
        GENERATED_NOTE,
        "",
        "# GitHub Action Inputs and Outputs Reference",
        "",
        "Every `with:` input and `outputs.*` value for the "
        "[abicheck GitHub Action](../user-guide/github-action.md), generated "
        "directly from `action.yml` — see that page for setup, mode/input "
        "compatibility, and usage recipes; this page is the exhaustive field "
        "list only.",
        "",
        f"## Inputs ({len(input_rows)})",
        "",
        "| Input | Required | Default | Description |",
        "|---|:--:|---|---|",
    ]
    for row in input_rows:
        lines.append(
            f"| `{row['name']}` | {row['required']} | {row['default']} | "
            f"{row['description']} |"
        )
    lines += [
        "",
        f"## Outputs ({len(output_rows)})",
        "",
        "| Output | Description |",
        "|---|---|",
    ]
    for row in output_rows:
        lines.append(f"| `{row['name']}` | {row['description']} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    action = yaml.safe_load(ACTION_YML.read_text(encoding="utf-8"))
    content = render(action)

    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != content:
            print(f"{OUT_PATH.relative_to(REPO_DIR)} is stale — regenerate with:")
            print("  python scripts/gen_action_reference.py")
            return 1
        print(f"{OUT_PATH.relative_to(REPO_DIR)} is in sync")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
