#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_agent_skills.py — publish `skills-src/` as self-contained Agent Skills.

ADR-058 / plan G36 P0.3. `skills-src/` is the one hand-authored copy: each
skill's `SKILL.md` plus its own `references/`, and one `shared/` tree of
Layer-B domain fragments every skill cites by link. This generator resolves
what each skill actually cites (transitively — a fragment may cite another
fragment), **copies** it into that skill's own `references/shared/`, and
rewrites every link so the installed skill resolves entirely inside its own
directory.

Copies, never symlinks: an installed skill is read from the perspective of one
directory, and a marketplace zip, a `skills.sh` subset install, or a Windows
checkout each break a live cross-skill link differently (ADR-058, "Source-of-
truth and publication model").

Three output trees, same content:

* ``.agents/skills/``  — the canonical portable target (Copilot, Codex, Cursor
  read it directly).
* ``.claude/skills/``  — Claude Code does not scan ``.agents/skills``.
* ``.gemini/skills/``  — nor does Gemini CLI.

Links pointing at this repository's own ``docs/`` pages are rewritten to the
published documentation site, whose host comes from ``mkdocs.yml``'s
``site_url`` and whose URL shape comes from ``mkdocs.yml``'s
``use_directory_urls`` (mkdocs's own default, ``true``, when the key is
absent) — never a hardcoded literal, so the generator cannot silently emit
broken links if either is ever changed.

Usage:
    python scripts/gen_agent_skills.py            # write the trees
    python scripts/gen_agent_skills.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from collections.abc import Callable
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_DIR / "skills-src"
SHARED_DIR = SRC_DIR / "shared"
DOCS_DIR = REPO_DIR / "docs"
MKDOCS_YML = REPO_DIR / "mkdocs.yml"

#: Every committed publication tree. `.agents/skills` is authoritative; the
#: other two exist because Claude Code and Gemini CLI do not scan it.
OUTPUT_ROOTS: tuple[Path, ...] = (
    REPO_DIR / ".agents" / "skills",
    REPO_DIR / ".claude" / "skills",
    REPO_DIR / ".gemini" / "skills",
)

#: Where a cited `shared/` fragment lands inside a generated skill, relative
#: to the skill's own root.
SHARED_SUBDIR = "references/shared"

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/gen_agent_skills.py from skills-src/ — "
    "do not edit by hand. Run `python scripts/gen_agent_skills.py` to "
    "regenerate. -->"
)

#: The substring `scripts/check_ai_readiness.py`'s generated-file-ownership
#: check looks for in every generated Markdown file under the output trees.
GENERATED_MARKER_SUBSTRING = "generated by scripts/gen_agent_skills.py"

#: Inline Markdown links `[text](target)` — the one link syntax skill sources
#: may use, so the rewrite below is exhaustive rather than best-effort.
_MD_LINK_RE = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)(\s+\"[^\"]*\")?\)")

#: The two CommonMark container markers a line may carry before its leaf
#: block: a block quote, and a list item. Applied by `_split_container_prefix`
#: below, which every line-anchored *guard* in this module goes through.
#:
#: One shared notion of "container prefix" because the guards are all blind to
#: containers in the same way, and fixing them one prefix at a time has now
#: been wrong three rounds running: a block-quoted fence, a list-indented
#: fence, a quote nested in a list item, a fence opened on the list-marker
#: line itself, and a block-quoted reference definition are one defect wearing
#: five prefixes. Enumerating prefixes fails for the same reason enumerating
#: link syntaxes did (`_MD_LINK_LIKE_RE`): containers compose, so any list of
#: them is only as complete as the last review.
_BLOCKQUOTE_MARKER_RE = re.compile(r">[ \t]?")
_LIST_MARKER_RE = re.compile(r"(?:[-*+]|\d{1,9}[.)])[ \t]+")


def _split_container_prefix(line: str) -> tuple[str, str]:
    """Split `line` into its container prefix and the leaf content after it.

    A scan rather than a pattern, deliberately. Expressing "indentation, then
    a quote or list marker, repeated" as a regex needs `[ \\t]*` both inside
    and after the repetition, and the two compete for the same characters — so
    on a long line that ultimately does not match, the engine explores every
    way of splitting them. The first attempt here did exactly that and hung on
    a 2000-marker line. Python 3.10 is supported, so atomic groups are not
    available to forbid the backtracking; a linear scan sidesteps it entirely
    and is easier to check by eye besides.
    """
    index = 0
    while True:
        cursor = index
        while cursor < len(line) and line[cursor] in " \t":
            cursor += 1
        marker = _BLOCKQUOTE_MARKER_RE.match(line, cursor) or _LIST_MARKER_RE.match(
            line, cursor
        )
        if marker is None:
            # No further marker: the whitespace just skipped is ordinary
            # indentation, and belongs to the prefix rather than the content.
            return line[:cursor], line[cursor:]
        index = marker.end()


#: Reference-style link definitions (`[label]: target`), which this rewrite
#: does not handle. Detected so generation *fails* on one rather than
#: publishing it untouched: `[guide][docs]` with a `[docs]: ../../docs/…`
#: definition is invisible to `_MD_LINK_RE`, so it would survive into every
#: installed tree still pointing at a repo path that does not exist there.
#: Rejecting is deliberate over rewriting — one syntax is the contract, and a
#: silently-supported second one is how the rewrite stops being exhaustive.
#:
#: Matched against a line's *content* (after `_split_container_prefix`), so it
#: is container-aware without needing to accept any prefix itself: a reference
#: definition is rejected wherever it appears, in a quote or a list item as
#: readily as at the left margin. A quoted `> [guide]: ../…` still binds a
#: later `> [guide]`, and carries no `](` for the inline-link guard to catch,
#: so missing it shipped a repo-relative destination silently.
_MD_REF_DEF_RE = re.compile(r"\[([^\]^][^\]]*)\]:\s*\S+")

#: Markdown images (`![alt](target)`), excluded from `_MD_LINK_RE` by its
#: negative lookbehind and rejected here for the same reason as a reference
#: definition: the destination is never rewritten, and this generator copies
#: only Markdown — so a published skill would carry a repo-relative path to an
#: asset its own directory does not contain. Self-containment is the property
#: that makes a single skill directory installable on its own.
_MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)")

#: Every `](` in a body, rewritable or not. Used to *invert* the guard below:
#: rather than enumerating the link syntaxes this generator cannot rewrite,
#: it asserts that every link-shaped construct was matched by `_MD_LINK_RE`
#: or `_MD_IMAGE_RE`.
#:
#: Enumeration was tried and failed four times. Reference definitions, images,
#: angle-bracket destinations, and `'single'`/`(paren)` title delimiters are
#: each valid Markdown that `_MD_LINK_RE` skips, and each shipped an
#: unrewritten repo-relative target until a guard was added for it
#: specifically. A denylist of syntaxes is only ever as complete as the last
#: review; the property actually wanted is "nothing outbound escaped the
#: rewrite", and that is checkable directly.
_MD_LINK_LIKE_RE = re.compile(r"\]\(")

#: Raw-HTML link/asset attributes. Markdown permits inline HTML, and an
#: `<a href="../../docs/foo.md">` carries a destination with no `](` in it at
#: all — so it is invisible both to `_MD_LINK_RE` and to the inverted guard
#: above, which only reasons about Markdown link syntax. Rejected for the same
#: single reason as every other variant: the rewrite cannot see it, so it
#: would ship a repo-relative target into an installed skill.
#: Case-insensitive because HTML tag and attribute names are: `<A HREF=...>`
#: is the same element as `<a href=...>`, and matching only the lowercase
#: spelling let it through.
_HTML_LINK_ATTR_RE = re.compile(
    r"<[a-zA-Z][^>]*\s(?:href|src)\s*=", re.DOTALL | re.IGNORECASE
)

_FRONT_MATTER_RE = re.compile(r"\A---\r?\n.*?\r?\n---\r?\n", re.DOTALL)


#: Fenced code blocks, then inline code spans. Applied in that order so a
#: backtick *inside* a fence is never mistaken for an inline span.
#:
#: A closing fence uses the same character as its opener, runs *at least* as
#: long, and carries nothing but trailing whitespace. Both halves of that were
#: wrong in turn: accepting arbitrary text after the delimiter let a line like
#: ```` ```oops ```` inside a block read as a closer, and a plain backreference
#: demanded an exactly-equal run so a block closed with a longer delimiter
#: never matched at all. Either way the mask ended early or never formed, and
#: the example's link syntax was rewritten or rejected as prose.
#:
#: Two alternatives rather than one, because the delimiter character must be
#: consistent — `~~~` may not close ```` ``` ````. The backtick variant also
#: bars backticks from its info string, as CommonMark does.
#: End of document closes an unterminated fence (CommonMark §4.5), so the
#: closer alternates with `\Z` — otherwise a block running to EOF never
#: matched and its examples were processed as prose.
#:
#: Content is `(?:.*?\n)??` — optional, and lazy so the *empty* block is tried
#: first. Writing it as `.*?` followed by a closer that began with its own
#: `\n` made an empty block unmatchable: the opener already consumed the only
#: newline, so `` ```\n``` `` found no closer, fell through to `\Z`, and
#: masked the entire rest of the document — silently exempting every link
#: after it from both validation and rewriting, which is worse than the
#: mis-masking this pattern's earlier bugs caused.
_FENCE_RE = re.compile(
    r"^ {0,3}(?P<tick>`{3,})[^\n`]*\n"
    r"(?:(?:.*?\n)?? {0,3}(?P=tick)`*[ \t]*$|.*?\Z)"
    r"|^ {0,3}(?P<tilde>~{3,})[^\n]*\n"
    r"(?:(?:.*?\n)?? {0,3}(?P=tilde)~*[ \t]*$|.*?\Z)",
    re.M | re.S,
)
_INLINE_CODE_RE = re.compile(r"(?<!`)(`+)(?!`)(.+?)(?<!`)\1(?!`)", re.DOTALL)

#: A backslash-escaped character this pipeline's own patterns treat as
#: structural. CommonMark makes each of these a *literal*, so it neither opens
#: a code span nor delimits a link — but `_INLINE_CODE_RE` and `_MD_LINK_RE`
#: read them structurally anyway. An escaped backtick pair around a real link
#: masks it, and the link then ships repo-relative into every installed tree;
#: an escaped bracket makes literal prose look like a link and get rewritten.
#:
#: Rejected rather than handled, and the tempting fix is the wrong one:
#: masking escapes *before* inline spans inverts CommonMark's precedence
#: (code spans are parsed first, so `` `a\` `` is a span containing `a\`) and
#: would consume that span's closing delimiter — masking the wrong region and
#: leaving a genuine link unrewritten. Getting it right needs a real inline
#: parser with backslash-parity tracking, which is well past what a publisher
#: should carry. Other escapes (`\*`, `\_`, `\#`, …) pass through untouched:
#: no pattern here reads them structurally, so they cannot mis-mask anything.
_STRUCTURAL_ESCAPE_RE = re.compile(r"\\[`\[\]()]")

#: Any fence delimiter and whatever precedes it on its line. `_FENCE_RE`
#: anchors on the line start and accepts at most three spaces, so a fence
#: carrying a `_CONTAINER_PREFIX` — a block quote, a list item's content
#: indent, the list-marker line itself, a tab, or any interleaving — is never
#: masked and its examples are rewritten as prose.
#:
#: Unlike the reference-definition guard above, the prefix is *inspected*
#: rather than simply widened: an unindented fence, and one indented up to
#: three spaces, are exactly what `_FENCE_RE` already reads, so those must
#: keep passing. The property asserted is "the prefix is one the mask can
#: read", not a list of the ways it can fail.
#:
#: Containers are rejected, not supported. Handling them properly means real
#: block-level parsing — quotes nest, hold lists, and continue lazily — and a
#: *partial* container parser is worse than none: it can mask the wrong span
#: and leave a genuine link unrewritten, which fails silently.
_FENCE_DELIMITER_RE = re.compile(r"`{3,}|~{3,}")

#: Placeholder body — `\x00` cannot occur in a Markdown source, so a masked
#: region is invisible to every link pattern and cannot be produced by one.
_MASK = "\x00m{index}\x00"

_LIST_ITEM_RE = re.compile(r"^ {0,3}(?:[-*+]|\d{1,9}[.)])\s")


def _indented_code_spans(text: str) -> list[tuple[int, int]]:
    """Line ranges of indented code blocks, at top level and inside lists.

    An indent means *two* things in Markdown — an indented code block, and a
    continuation of the list item above — and which one it is depends on the
    enclosing item's content column, not on a fixed number of spaces. Four
    spaces under `- ` is a continuation; six is code. Tracking only whether a
    list was open forced a choice between masking continuations (which leaves
    a real link unrewritten, silently) and masking nothing inside a list
    (which rewrites a genuine code example's link text, also silently). Both
    were wrong, so the item's column is tracked instead and the floor is
    `column + 4` — the same rule CommonMark states, and the reason `2. ` and
    `- ` legitimately differ by one.

    An indented code block also cannot interrupt a paragraph (CommonMark
    §4.4), which the blank-line requirement already encodes.
    """
    lines = text.split("\n")
    spans: list[tuple[int, int]] = []
    #: Content column of the innermost open list item, or `None` at top level.
    item_column: int | None = None
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
            continue
        marker = _LIST_ITEM_RE.match(line)
        if marker is not None:
            # The whole matched prefix, not its leading whitespace: the item's
            # content begins after the marker and its trailing space, so `- `
            # opens at column 2 and `10. ` at column 4.
            item_column = _column_width(marker.group())
            index += 1
            continue
        if not line.startswith((" ", "\t")):
            item_column = None  # a flush-left line closes any open list
            index += 1
            continue
        floor = 4 if item_column is None else item_column + 4
        # Document start is a boundary too: with front matter already split
        # off, a reference file can legitimately open on an indented block.
        blank_before = index == 0 or not lines[index - 1].strip()
        if _indent_width(line) >= floor and blank_before:
            start = index
            while index < len(lines) and (
                not lines[index].strip() or _indent_width(lines[index]) >= floor
            ):
                index += 1
            while index - 1 > start and not lines[index - 1].strip():
                index -= 1  # trailing blanks belong to the document, not the block
            spans.append((start, index))
            continue
        index += 1
    return spans


def _column_width(text: str) -> int:
    """Columns `text` occupies, counting a tab as CommonMark's four."""
    return sum(4 if char == "\t" else 1 for char in text)


def _indent_width(line: str) -> int:
    """Columns of `line`'s leading whitespace."""
    return _column_width(line[: len(line) - len(line.lstrip(" \t"))])


def _masker(replacements: dict[str, str]) -> Callable[[re.Match[str]], str]:
    """A `re.sub` replacement that banks each match under a fresh placeholder.

    The placeholder keeps the region's newline count so every line number
    reported downstream still refers to the real source line.
    """

    def mask(match: re.Match[str]) -> str:
        original = match.group(0)
        token = _MASK.format(index=len(replacements))
        placeholder = token + "\n" * original.count("\n")
        replacements[placeholder] = original
        return placeholder

    return mask


def _mask_block_code(text: str, replacements: dict[str, str]) -> str:
    """Mask indented code blocks, then fenced ones. Block level only.

    Split out of `mask_code_regions` because the container-indented-fence
    guard needs exactly this intermediate state: both block-level passes done
    (which is what makes a *surviving* indented fence meaningful) but inline
    code spans not yet paired — that pass incidentally masks the backtick form
    of the very construct the guard looks for.
    """
    # Indented blocks first, by line range: they are defined by position, and
    # masking them up front keeps the regex pass below from seeing content the
    # renderer shows literally.
    lines = text.split("\n")
    for start, end in reversed(_indented_code_spans(text)):
        original = "\n".join(lines[start:end])
        token = _MASK.format(index=len(replacements))
        placeholder = token + "\n" * original.count("\n")
        replacements[placeholder] = original
        lines[start:end] = placeholder.split("\n")
    return _FENCE_RE.sub(_masker(replacements), "\n".join(lines))


def _reference_definition_labels(text: str) -> list[str]:
    """Labels of every reference-style link definition in `text`.

    Per line, and through `_split_container_prefix`, so a definition inside a
    block quote or a list item is found as readily as one at the left margin.
    Anchored at the start of the line's content rather than searched, which is
    what the old `^ {0,3}` did before containers were accounted for — a
    `[label]:` in the middle of a sentence is prose, not a definition.
    """
    labels: list[str] = []
    for line in text.split("\n"):
        _, content = _split_container_prefix(line)
        match = _MD_REF_DEF_RE.match(content)
        if match is not None:
            labels.append(match.group(1))
    return labels


def _contained_fence_line(text: str) -> tuple[int, str] | None:
    """1-based line and container prefix of a fence the mask cannot see.

    Checked against the `_mask_block_code` midpoint — after indented and
    top-level fenced blocks are masked, before inline spans are paired — and
    both halves of that placement matter.

    *After* the block-level passes, because a four-space indent is ambiguous
    in Markdown: at top level it opens an indented code block, where the fence
    characters are literal content, while under a list item it is the item's
    own content indent and the fence is real. `_indented_code_spans` already
    resolves that ambiguity, so asking what survives it reuses that answer
    instead of growing a second, independently-drifting notion of list state.
    Fence characters printed inside a top-level fenced block are content too,
    and `_FENCE_RE` has already masked those.

    *Before* inline pairing, because that pass incidentally masks the backtick
    form of the very construct being looked for — leaving only the tilde form
    visible, and making the guard's coverage depend on an accident.
    """
    residue = _mask_block_code(text, {})
    for index, line in enumerate(residue.split("\n")):
        prefix, content = _split_container_prefix(line)
        if _FENCE_DELIMITER_RE.match(content) is None:
            continue
        # A bare fence, or one indented up to three spaces, is exactly what
        # `_FENCE_RE` already reads — those must keep passing.
        if prefix.strip(" ") or len(prefix) > 3:
            return index + 1, prefix
    return None


def mask_code_regions(text: str) -> tuple[str, dict[str, str]]:
    """Replace code blocks and spans with opaque placeholders.

    Link syntax inside a code example is *content*, not a link: the renderer
    shows it literally, so rewriting its destination corrupts the example, and
    validating it rejects a source for demonstrating what a bad link looks
    like. Both guards and the rewrite therefore run over masked text.

    Each placeholder carries the masked region's newline count so error
    messages keep reporting real source line numbers.
    """
    replacements: dict[str, str] = {}
    masked = _mask_block_code(text, replacements)
    return _INLINE_CODE_RE.sub(_masker(replacements), masked), replacements


def unmask_code_regions(text: str, replacements: dict[str, str]) -> str:
    for placeholder, original in replacements.items():
        text = text.replace(placeholder, original)
    return text


class SkillGenerationError(RuntimeError):
    """A skill source tree that cannot be published as-is."""


def _reject_unrewritable_links(source_path: Path, body: str) -> None:
    """Fail unless every link-shaped construct is one the rewrite can handle.

    The inverse of a denylist: instead of naming the syntaxes that escape
    `_MD_LINK_RE`, this checks that no `](` falls outside a span it (or
    `_MD_IMAGE_RE`) actually matched. Anything left over is a link this
    generator would copy verbatim into a self-contained skill directory,
    where a repo-relative target does not resolve.
    """
    for match in _MD_LINK_RE.finditer(body):
        target = match.group(2)
        if target.startswith("<") or target.endswith(">"):
            # Matched, but only because this destination happens to carry no
            # whitespace: the angle brackets are captured as part of the path,
            # so the rewrite resolves a target that does not exist and leaves
            # it alone. Malformed-but-matching is as broken as unmatched.
            raise SkillGenerationError(
                f"{source_path}: angle-bracket link destination `{target}` — "
                "write the path plainly. The brackets are captured as part of "
                "the target, so the rewrite cannot resolve it and publishes "
                "it verbatim."
            )

    html = _HTML_LINK_ATTR_RE.search(body)
    if html is not None:
        line = body.count("\n", 0, html.start()) + 1
        raise SkillGenerationError(
            f"{source_path}: line ~{line}: raw-HTML link or asset attribute "
            f"(`{body[html.start() : html.start() + 50].splitlines()[0]}`). "
            "Skill sources link in Markdown; the rewrite does not read HTML, "
            "so an `href`/`src` here would be published verbatim."
        )

    covered = [
        match.span()
        for pattern in (_MD_LINK_RE, _MD_IMAGE_RE)
        for match in pattern.finditer(body)
    ]
    escaped = [
        marker.start()
        for marker in _MD_LINK_LIKE_RE.finditer(body)
        if not any(start <= marker.start() < end for start, end in covered)
    ]
    if not escaped:
        return
    line = body.count("\n", 0, escaped[0]) + 1
    excerpt = body[escaped[0] : escaped[0] + 60].splitlines()[0]
    raise SkillGenerationError(
        f"{source_path}: line ~{line}: link syntax the rewrite cannot handle "
        f"(`...{excerpt}`). Skill sources use plain inline "
        '`[text](target)` links, optionally with a `"double-quoted"` title. '
        "An angle-bracket destination, a `'single'`/`(paren)` title, or any "
        "other variant is skipped by the rewrite and would be published "
        "verbatim, leaving a repo-relative target in an installed skill."
    )


# ---------------------------------------------------------------------------
# mkdocs-derived published-URL mapping
# ---------------------------------------------------------------------------


def _read_mkdocs_scalar(key: str) -> str | None:
    """Read one top-level scalar from mkdocs.yml without importing PyYAML.

    This script must stay pure-stdlib for the same reason
    `check_ai_readiness.py` does — it runs in gates that may execute before
    `pip install -e .`. Only two top-level scalars are needed and both are
    plain, unquoted or simply-quoted values.
    """
    if not MKDOCS_YML.is_file():
        return None
    pattern = re.compile(rf"^{re.escape(key)}\s*:\s*(.+?)\s*$", re.MULTILINE)
    for match in pattern.finditer(MKDOCS_YML.read_text(encoding="utf-8")):
        # Top-level only: a nested key is indented, and MULTILINE ^ would
        # otherwise match it mid-file.
        line_start = match.start()
        if line_start != 0 and not match.group(0).startswith(key):
            continue
        value = match.group(1).strip().strip("'\"")
        return value or None
    return None


def published_docs_url(docs_relative: str, anchor: str = "") -> str:
    """The published URL for a repo `docs/`-relative Markdown path.

    Host and path prefix come from `site_url`; the extension-to-URL mapping
    follows `use_directory_urls` (mkdocs's own default is `true`, applied only
    when the key is genuinely absent — not frozen as a second fact owner).
    Anchors pass through unchanged; mkdocs does not rewrite them.

    A missing or unreadable `site_url` is a hard error, not a fallback: an
    empty host silently yields a root-relative `/learn/verdicts/`, which
    resolves to nothing at all from an installed skill and contradicts this
    module's whole no-dangling-references guarantee. Failing here is what
    makes that guarantee real rather than best-effort.
    """
    raw_site_url = _read_mkdocs_scalar("site_url")
    if not raw_site_url or "://" not in raw_site_url:
        raise SkillGenerationError(
            f"{MKDOCS_YML.name}: no usable `site_url` (read {raw_site_url!r}) — "
            "it is the fact owner for the published docs host every generated "
            "skill's outbound links are rewritten against; without it the "
            "output would carry root-relative links that resolve nowhere from "
            "an installed skill"
        )
    site_url = raw_site_url.rstrip("/")
    raw_dir_urls = _read_mkdocs_scalar("use_directory_urls")
    directory_urls = True if raw_dir_urls is None else raw_dir_urls.lower() == "true"

    stem = (
        docs_relative[: -len(".md")] if docs_relative.endswith(".md") else docs_relative
    )
    if directory_urls:
        if stem == "index" or stem.endswith("/index"):
            stem = stem[: -len("index")].rstrip("/")
        path = f"{stem}/" if stem else ""
    else:
        path = f"{stem}.html"
    return f"{site_url}/{path}{anchor}"


# ---------------------------------------------------------------------------
# Source discovery
# ---------------------------------------------------------------------------


def discover_skills(src_dir: Path | None = None) -> list[Path]:
    """Every `skills-src/<name>/` directory holding a `SKILL.md`."""
    src_dir = SRC_DIR if src_dir is None else src_dir
    if not src_dir.is_dir():
        return []
    return sorted(
        child
        for child in src_dir.iterdir()
        if child.is_dir() and child.name != "shared" and (child / "SKILL.md").is_file()
    )


def _markdown_files(skill_dir: Path) -> list[Path]:
    files = [skill_dir / "SKILL.md"]
    references = skill_dir / "references"
    if references.is_dir():
        files.extend(sorted(p for p in references.rglob("*.md")))
    return files


def _link_targets(path: Path) -> list[str]:
    # Masked, so a fragment shown inside a code example is not counted as a
    # citation — that would copy it into the skill and, if it were the only
    # mention, make an orphan check pass on a fragment nothing really cites.
    masked, _ = mask_code_regions(path.read_text(encoding="utf-8"))
    return [m.group(2) for m in _MD_LINK_RE.finditer(masked)]


def _shared_fragment_for(path: Path, target: str, shared_dir: Path) -> str | None:
    """The `shared/` fragment basename `target` names, seen from `path`."""
    if "://" in target or target.startswith(("#", "mailto:", "/")):
        return None
    bare = target.split("#", 1)[0]
    if not bare.endswith(".md"):
        return None
    resolved = (path.parent / bare).resolve()
    try:
        relative = resolved.relative_to(shared_dir.resolve())
    except ValueError:
        return None
    if len(relative.parts) != 1:
        return None
    return relative.parts[0]


def resolve_shared_fragments(
    skill_dir: Path, shared_dir: Path | None = None
) -> list[str]:
    """Fragment basenames this skill cites, resolved to a fixed point.

    Scans `SKILL.md` **and** every file under the skill's own `references/`
    (a skill-specific reference may be the only thing citing a fragment), then
    keeps following citations *from copied fragments* until nothing new is
    found — a fragment may cite another fragment.
    """
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    found: set[str] = set()
    queue: list[Path] = list(_markdown_files(skill_dir))
    while queue:
        current = queue.pop()
        for target in _link_targets(current):
            name = _shared_fragment_for(current, target, shared_dir)
            if name is None:
                continue
            fragment = shared_dir / name
            if not fragment.is_file():
                raise SkillGenerationError(
                    f"{current.relative_to(REPO_DIR).as_posix()}: references "
                    f"shared fragment {name!r}, which does not exist under "
                    f"{shared_dir.relative_to(REPO_DIR).as_posix()}/"
                )
            if name not in found:
                found.add(name)
                queue.append(fragment)
    return sorted(found)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _strip_front_matter(text: str) -> str:
    return _FRONT_MATTER_RE.sub("", text, count=1)


def _split_front_matter(text: str) -> tuple[str, str]:
    match = _FRONT_MATTER_RE.match(text)
    if match is None:
        return "", text
    return match.group(0), text[match.end() :]


def _rewrite_target(
    source_path: Path,
    out_rel: str,
    target: str,
    shared_names: set[str],
    shared_dir: Path,
    docs_dir: Path,
    containment_root: Path,
) -> str:
    """Rewrite one link target for its position in the generated tree.

    `out_rel` is the generated file's path relative to the skill root, which
    is what a `shared/` fragment link must be made relative to.
    `containment_root` is the source directory this file's own relative links
    may not escape — the skill's own directory for a `SKILL.md`/`references/`
    file, and `shared/` for a fragment (whose only legitimate relative links
    are sibling fragments, already handled above).
    """
    if target.startswith("/"):
        # Root-relative: resolved against whatever host or filesystem root
        # renders the installed skill, which is neither the skill's own
        # directory nor abicheck's docs site. There is no correct rewrite —
        # the intended base is unknowable — so reject rather than publish a
        # link whose meaning depends on where it is read.
        raise SkillGenerationError(
            f"{source_path.relative_to(REPO_DIR).as_posix()}: root-relative "
            f"link {target!r} — write a path relative to this file, or a full "
            "URL. A leading slash resolves against the reader's root, not the "
            "installed skill."
        )

    if "://" in target or target.startswith(("#", "mailto:")):
        return target

    bare, _, anchor = target.partition("#")
    anchor = f"#{anchor}" if anchor else ""
    if not bare:
        return target

    fragment = _shared_fragment_for(source_path, target, shared_dir)
    if fragment is not None:
        if fragment not in shared_names:  # pragma: no cover - resolver is exhaustive
            raise SkillGenerationError(
                f"{source_path.relative_to(REPO_DIR).as_posix()}: cites "
                f"fragment {fragment!r} that was not resolved for this skill"
            )
        destination = Path(SHARED_SUBDIR) / fragment
        return _relative_link(Path(out_rel), destination) + anchor

    resolved = (source_path.parent / bare).resolve()
    try:
        docs_relative = resolved.relative_to(docs_dir.resolve()).as_posix()
    except ValueError:
        docs_relative = None
    if docs_relative is not None:
        if not resolved.is_file():
            raise SkillGenerationError(
                f"{source_path.relative_to(REPO_DIR).as_posix()}: links to "
                f"docs page {bare!r}, which does not exist"
            )
        return published_docs_url(docs_relative, anchor)

    # A link that stays inside the skill's own tree (SKILL.md ->
    # references/foo.md) needs no rewriting; anything else escapes the
    # installed directory and is a hard error rather than a silent copy.
    try:
        resolved.relative_to(containment_root.resolve())
    except ValueError:
        raise SkillGenerationError(
            f"{source_path.relative_to(REPO_DIR).as_posix()}: link {target!r} "
            "escapes the skill's own directory and is neither a shared "
            "fragment nor a docs/ page"
        ) from None

    # Contained is necessary but not sufficient: `render_skill` publishes
    # `SKILL.md` and `references/**/*.md` and nothing else, so a link to a
    # contained path the generator does not copy (`references/data.json`, a
    # `notes.md` beside `SKILL.md`) is preserved verbatim and then dangles in
    # every installed tree. The link must name a file that actually ships.
    rel = resolved.relative_to(containment_root.resolve())
    ships = (
        resolved.is_file()
        and resolved.suffix == ".md"
        and (
            # A `shared/` fragment's siblings are published flat beside it.
            containment_root.resolve() == shared_dir.resolve()
            or rel.as_posix() == "SKILL.md"
            or rel.parts[:1] == ("references",)
        )
    )
    if not ships:
        raise SkillGenerationError(
            f"{source_path.relative_to(REPO_DIR).as_posix()}: link {target!r} "
            "points inside the skill but at something this generator does not "
            "publish. Only `SKILL.md` and `references/**/*.md` are copied, so "
            "any other target would dangle in the installed skill."
        )
    return target


def _relative_link(from_rel: Path, to_rel: Path) -> str:
    """POSIX relative link from one skill-relative file to another."""
    from_parts = from_rel.parent.parts
    to_parts = to_rel.parts
    common = 0
    while (
        common < len(from_parts)
        and common < len(to_parts) - 1
        and from_parts[common] == to_parts[common]
    ):
        common += 1
    ups = [".."] * (len(from_parts) - common)
    return "/".join([*ups, *to_parts[common:]])


def _render(
    source_path: Path,
    out_rel: str,
    shared_names: set[str],
    *,
    keep_front_matter: bool,
    containment_root: Path,
    shared_dir: Path | None = None,
    docs_dir: Path | None = None,
) -> str:
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    docs_dir = DOCS_DIR if docs_dir is None else docs_dir
    text = source_path.read_text(encoding="utf-8")
    front_matter, body = _split_front_matter(text)

    # One guard for every container — block quote, list indent, tab, and any
    # nesting of them. Enumerating containers separately left their
    # combinations uncovered; see `_CONTAINED_FENCE_RE`.
    contained = _contained_fence_line(body)
    if contained is not None:
        line, prefix = contained
        raise SkillGenerationError(
            f"{source_path}: line ~{line}: fenced code block behind the "
            f"container prefix {prefix!r}. The mask anchors on the line start "
            "and reads at most three leading spaces, so the block would be "
            "processed as prose and its example links rewritten. Move the "
            "example out of its container, to the left margin."
        )

    # Checked at the `_mask_block_code` midpoint, exactly like the container
    # guard. An earlier version scanned the raw body on the theory that
    # masking is what an escape corrupts — but that is only true of *inline*
    # pairing. The block-level passes match fence delimiters at line starts
    # and never pair backticks, so an escape cannot mislead them, and running
    # first means a `\[` inside a legitimate regex or C-string example is
    # already hidden. Scanning raw rejected those valid examples outright.
    escaped_body = _mask_block_code(body, {})
    escape = _STRUCTURAL_ESCAPE_RE.search(escaped_body)
    if escape is not None:
        line = escaped_body.count("\n", 0, escape.start()) + 1
        raise SkillGenerationError(
            f"{source_path}: line ~{line}: backslash-escaped {escape.group()!r}. "
            "CommonMark makes it a literal, but the code-span and link "
            "patterns here still read it structurally — an escaped backtick "
            "pair masks a real link (which then ships repo-relative), and an "
            "escaped bracket makes prose look like a link. Use a code span, "
            "or reword to avoid the escape."
        )

    # Code examples are literal content: their link syntax must be neither
    # rewritten nor validated. Everything below operates on masked text.
    body, code_regions = mask_code_regions(body)

    ref_defs = _reference_definition_labels(body)
    if ref_defs:
        raise SkillGenerationError(
            f"{source_path}: reference-style link definition(s) "
            f"{sorted(ref_defs)} — skill sources must use inline "
            "`[text](target)` links only. The link rewrite does not see a "
            "reference definition, so it would be published verbatim and "
            "point outside the installed skill."
        )

    images = [m.group(2) for m in _MD_IMAGE_RE.finditer(body)]
    if images:
        raise SkillGenerationError(
            f"{source_path}: Markdown image(s) {sorted(images)} — this "
            "generator publishes Markdown only and never rewrites an image "
            "destination, so the installed skill would reference an asset it "
            "does not contain. Describe the diagram in text, or link the "
            "published docs page that hosts it."
        )

    _reject_unrewritable_links(source_path, body)

    def replace(match: re.Match[str]) -> str:
        label, target, title = match.group(1), match.group(2), match.group(3) or ""
        new_target = _rewrite_target(
            source_path,
            out_rel,
            target,
            shared_names,
            shared_dir,
            docs_dir,
            containment_root,
        )
        return f"[{label}]({new_target}{title})"

    body = unmask_code_regions(_MD_LINK_RE.sub(replace, body), code_regions)
    head = front_matter if keep_front_matter else ""
    return f"{head}{GENERATED_MARKER}\n\n{body.lstrip(chr(10))}"


def render_skill(skill_dir: Path, shared_dir: Path | None = None) -> dict[str, str]:
    """The complete generated content of one skill, keyed by skill-relative path.

    `shared_dir` defaults to the module-global `SHARED_DIR`, but a caller
    rendering a different source tree must pass that tree's own `shared/` —
    resolving fragments against one tree while discovering skills in another
    would mix two unrelated sources into one output.
    """
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    fragments = resolve_shared_fragments(skill_dir, shared_dir)
    shared_names = set(fragments)
    out: dict[str, str] = {}

    out["SKILL.md"] = _render(
        skill_dir / "SKILL.md",
        "SKILL.md",
        shared_names,
        keep_front_matter=True,
        containment_root=skill_dir,
        shared_dir=shared_dir,
    )

    references = skill_dir / "references"
    if references.is_dir():
        for path in sorted(references.rglob("*.md")):
            rel = f"references/{path.relative_to(references).as_posix()}"
            out[rel] = _render(
                path,
                rel,
                shared_names,
                keep_front_matter=False,
                containment_root=skill_dir,
                shared_dir=shared_dir,
            )

    for name in fragments:
        rel = f"{SHARED_SUBDIR}/{name}"
        if rel in out:
            # A skill-specific `references/shared/<name>.md` was rendered
            # above and the skill also cites the global fragment of that
            # name. Assigning here would silently replace the skill's own
            # file with the global one — generation and `--check` would both
            # pass while every published tree served content the skill's own
            # links did not mean.
            raise SkillGenerationError(
                f"{skill_dir.name}: {rel!r} is produced twice — once from "
                f"this skill's own `references/shared/{name}` and once from "
                f"the global `shared/{name}` it cites. Rename the "
                "skill-specific file; `references/shared/` is reserved for "
                "copied global fragments."
            )
        out[rel] = _render(
            shared_dir / name,
            rel,
            shared_names,
            keep_front_matter=False,
            containment_root=shared_dir,
            shared_dir=shared_dir,
        )
    return out


def render_all(src_dir: Path | None = None) -> dict[str, str]:
    """Every generated file, keyed by `<skill-name>/<skill-relative path>`.

    Also enforces the no-orphan rule: a `shared/` fragment no skill cites,
    directly or transitively, is dead content and fails generation.
    """
    src_dir = SRC_DIR if src_dir is None else src_dir
    # The shared tree always belongs to the source tree being rendered, never
    # to whatever the module globals happen to point at — otherwise a caller
    # rendering an alternate `src_dir` silently resolves fragments against,
    # and orphan-checks, this repository's own `skills-src/shared/`.
    shared_dir = src_dir / "shared"
    skills = discover_skills(src_dir)
    if not skills:
        raise SkillGenerationError(f"no skills found under {src_dir}")

    rendered: dict[str, str] = {}
    cited: set[str] = set()
    for skill_dir in skills:
        cited.update(resolve_shared_fragments(skill_dir, shared_dir))
        for rel, content in render_skill(skill_dir, shared_dir).items():
            rendered[f"{skill_dir.name}/{rel}"] = content

    available = (
        {p.name for p in shared_dir.glob("*.md")} if shared_dir.is_dir() else set()
    )
    orphans = sorted(available - cited)
    if orphans:
        raise SkillGenerationError(
            "shared fragment(s) never cited by any skill (directly or "
            f"transitively): {', '.join(orphans)} — cite them or delete them"
        )
    return rendered


# ---------------------------------------------------------------------------
# Write / check
# ---------------------------------------------------------------------------


def _rendered_skill_names(rendered: dict[str, str]) -> set[str]:
    """The `<skill-name>` directories this render produced."""
    return {rel.split("/", 1)[0] for rel in rendered}


def _is_generated_skill_dir(path: Path) -> bool:
    """True if `path` is a skill directory *this* generator produced.

    Ownership is read off the emitted content itself — the `SKILL.md`'s own
    generated-file marker — rather than inferred from the current render.
    That distinction is what makes a removed or renamed skill detectable: its
    name is gone from the render, so a render-derived ownership set would stop
    considering the stale directory owned and leave it published forever while
    `--check` still passed. A hand-authored skill sharing the output root
    carries no marker and is never touched.
    """
    skill_md = path / "SKILL.md"
    if not skill_md.is_file():
        return False
    return GENERATED_MARKER_SUBSTRING in skill_md.read_text(encoding="utf-8").lower()


def _owned_skill_names(rendered: dict[str, str], root: Path) -> set[str]:
    """Every skill directory the generator owns under `root`.

    The union of what this render emits and what a previous render left
    behind (identified by its marker), so a stale directory stays in scope
    for both removal and drift reporting.

    Scoping still matters in the other direction: an output root can
    legitimately hold skills this generator did not produce (`.claude/skills/`
    is also where a repository's own hand-authored Claude Code skills live),
    and wiping the whole root would silently delete them.
    """
    owned = _rendered_skill_names(rendered)
    if root.is_dir():
        owned |= {
            child.name
            for child in root.iterdir()
            if child.is_dir() and _is_generated_skill_dir(child)
        }
    return owned


def _existing_tree(root: Path, owned: set[str]) -> dict[str, str]:
    if not root.is_dir():
        return {}
    return {
        p.relative_to(root).as_posix(): p.read_text(encoding="utf-8")
        for name in sorted(owned)
        for p in sorted((root / name).rglob("*"))
        if p.is_file()
    }


def write_trees(
    rendered: dict[str, str], roots: tuple[Path, ...] | None = None
) -> None:
    roots = OUTPUT_ROOTS if roots is None else roots
    for root in roots:
        # Includes previously-generated directories no longer in the render,
        # so a renamed or deleted skill is actually removed from the published
        # trees rather than left behind.
        for name in _owned_skill_names(rendered, root):
            if (root / name).exists():
                shutil.rmtree(root / name)
        for rel, content in rendered.items():
            path = root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


def check_trees(
    rendered: dict[str, str], roots: tuple[Path, ...] | None = None
) -> list[str]:
    roots = OUTPUT_ROOTS if roots is None else roots
    problems: list[str] = []
    for root in roots:
        try:
            rel_root = root.relative_to(REPO_DIR).as_posix()
        except ValueError:  # a test-supplied root outside the repo
            rel_root = root.as_posix()
        existing = _existing_tree(root, _owned_skill_names(rendered, root))
        for rel in sorted(set(rendered) | set(existing)):
            if rel not in existing:
                problems.append(f"{rel_root}/{rel}: missing")
            elif rel not in rendered:
                problems.append(f"{rel_root}/{rel}: stale (no longer generated)")
            elif existing[rel] != rendered[rel]:
                problems.append(f"{rel_root}/{rel}: out of date")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed trees match skills-src/ instead of writing",
    )
    args = parser.parse_args(argv)

    try:
        rendered = render_all()
    except SkillGenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.check:
        problems = check_trees(rendered)
        if problems:
            print("Generated agent-skill trees are out of sync:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print(
                "\nRun `python scripts/gen_agent_skills.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(
            f"agent skills in sync ({len(rendered)} files × {len(OUTPUT_ROOTS)} trees)"
        )
        return 0

    write_trees(rendered)
    print(
        f"wrote {len(rendered)} files to "
        + ", ".join(r.relative_to(REPO_DIR).as_posix() for r in OUTPUT_ROOTS)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
