#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_backend_capability_matrix.py — the L2 header-backend capability matrix
(G31 Phase D), generated from `scripts/backend_capabilities.py` rather than
hand-typed.

Splices the per-fact tables of
`docs/reference/header-backend-capabilities.md` between
`<!-- BEGIN GENERATED: backend-capability-matrix -->` /
`<!-- END GENERATED: backend-capability-matrix -->` sentinels — the same
splice-into-hand-authored-file pattern `gen_platform_matrix.py` uses for
`docs/reference/platforms.md`. The surrounding narrative (graph edges, why
CastXML cannot supply them, how to extend clang parsing, known gaps) stays
hand-authored.

Usage:
    python scripts/gen_backend_capability_matrix.py            # write the file
    python scripts/gen_backend_capability_matrix.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_DIR / "scripts"))
sys.path.insert(0, str(REPO_DIR))

from backend_capabilities import (  # type: ignore[import-not-found]  # noqa: E402
    COVERED_MODEL_CLASSES,
    FACT_ROWS,
    Capability,
    FactRow,
    hybrid_capability,
    rows_for,
)

OUT_PATH = REPO_DIR / "docs" / "reference" / "header-backend-capabilities.md"
_MARKER = "backend-capability-matrix"

GENERATED_NOTE = (
    "<!-- The tables in this section are GENERATED by "
    "scripts/gen_backend_capability_matrix.py — do not edit by hand. Run "
    "`python scripts/gen_backend_capability_matrix.py` to regenerate. The "
    "data (and the reasoning behind each row) lives in "
    "scripts/backend_capabilities.py. -->"
)

_CELL: dict[Capability, str] = {
    Capability.FULL: "✅ Yes",
    Capability.PARTIAL: "⚠️ Partial",
    Capability.COMPANION: "🔧 Companion tool",
    Capability.NONE: "❌ No",
    Capability.OTHER_LAYER: "— n/a",
}

_LEGEND = """| Cell | Meaning |
|------|---------|
| ✅ Yes | The backend's own parse populates this fact. |
| ⚠️ Partial | Populated, but narrower or less precise than the sibling backend's value — the note says how. |
| 🔧 Companion tool | Populated only when the optional LibTooling layout companion (`ABICHECK_CLANG_LAYOUT_TOOL`, G28 Phase 4) is configured; the plain `clang -ast-dump=json` parse computes no record layout. |
| ❌ No | Never populated by this backend; the field keeps its model default. |
| — n/a | No header-AST backend populates it — another layer owns the fact (DWARF, the ELF symbol table, the provenance pass), or nothing does. |"""


def _hybrid_note(row: FactRow) -> str:
    """The one thing a reader cannot derive from the other three columns."""
    if not row.populated_by_any_backend or row.hybrid_backfilled:
        return ""
    if row.clang is Capability.NONE or row.castxml is not Capability.NONE:
        return ""
    return (
        " *(hybrid keeps castxml's answer: the merge does not backfill this "
        "fact, so only a clang-only declaration carries it.)*"
    )


def _escape_table_cell(text: str) -> str:
    """Escape a literal ``|`` before interpolating free-form ``text`` (a
    ``FactRow.note``) into a Markdown table cell — GFM parses a raw ``|``
    as a column delimiter even inside inline-code backticks, so a note
    quoting a union type (e.g. `` `Fact[bool | None]` ``, real since
    ADR-063 Phase 5's `is_final_fact` row) would otherwise gain an extra
    cell and shift every later column in that row.
    """
    return text.replace("|", "\\|")


def _render_owner(owner: str) -> str:
    """One declaration dataclass's fact table."""
    lines = [
        f"### `{owner}`",
        "",
        "| Fact | CastXML | direct-clang | hybrid | Notes |",
        "|------|---------|--------------|--------|-------|",
    ]
    for row in rows_for(owner):
        note = _escape_table_cell((row.note + _hybrid_note(row)).strip()) or "—"
        lines.append(
            f"| `{row.field}` | {_CELL[row.castxml]} | {_CELL[row.clang]} "
            f"| {_CELL[hybrid_capability(row)]} | {note} |"
        )
    return "\n".join(lines)


def _render_summary() -> str:
    """The headline counts and the cell legend, above the per-owner tables."""
    header_facts = [r for r in FACT_ROWS if r.populated_by_any_backend]
    divergent = [r for r in header_facts if r.castxml is not r.clang]
    # "Only X populates it" means X's OWN PARSE does. A companion-tool row is
    # deliberately excluded from both counts: `RecordType.data_size_bits` is
    # NONE/COMPANION, and counting it as direct-clang-only would contradict
    # its own note, which says neither backend's parse computes it
    # (CodeRabbit review).
    own_parse = (Capability.FULL, Capability.PARTIAL)
    castxml_only = [
        r for r in header_facts if r.castxml in own_parse and r.clang not in own_parse
    ]
    clang_only = [
        r for r in header_facts if r.clang in own_parse and r.castxml not in own_parse
    ]
    return "\n".join(
        [
            f"Across the {len(FACT_ROWS)} fields of the "
            f"{len(COVERED_MODEL_CLASSES)} declaration types the two header-AST "
            f"backends build, {len(header_facts)} are facts a header parse can "
            f"carry at all. Of those, **{len(divergent)} differ between the two "
            f"backends**: {len(castxml_only)} only CastXML's own parse "
            f"populates, {len(clang_only)} only direct-clang's does, and the "
            "rest a difference of precision rather than presence. (A 🔧 row "
            "counts for neither — the plain parse computes it on neither "
            "backend.)",
            "",
            _LEGEND,
        ]
    )


def render() -> str:
    """The whole spliced-in section: summary, legend, then one table per owner."""
    sections = [_render_summary()] + [
        _render_owner(owner) for owner in COVERED_MODEL_CLASSES
    ]
    return GENERATED_NOTE + "\n\n" + "\n\n".join(sections) + "\n"


def _splice(text: str, inner: str) -> str:
    """Replace the sentinel-delimited region, leaving the narrative untouched."""
    begin = re.search(rf"<!-- BEGIN GENERATED: {_MARKER} -->\n", text)
    end = re.search(rf"\n<!-- END GENERATED: {_MARKER} -->", text)
    if not begin or not end or begin.end() > end.start():
        raise ValueError(
            f"{OUT_PATH.relative_to(REPO_DIR)}: missing/misordered sentinels "
            f"for {_MARKER!r}"
        )
    return text[: begin.end()] + inner + text[end.start() :]


def main(argv: list[str] | None = None) -> int:
    """Write the generated section, or (``--check``) fail if it has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    current = OUT_PATH.read_text(encoding="utf-8")
    rendered = _splice(current, render())

    if args.check:
        if rendered != current:
            print(
                f"{OUT_PATH.relative_to(REPO_DIR)}'s generated "
                f"{_MARKER} section is stale — regenerate with:",
                file=sys.stderr,
            )
            print("  python scripts/gen_backend_capability_matrix.py", file=sys.stderr)
            return 1
        print(
            f"{OUT_PATH.relative_to(REPO_DIR)}'s {_MARKER} section is in sync "
            f"({len(FACT_ROWS)} facts)"
        )
        return 0

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(
        f"wrote {OUT_PATH.relative_to(REPO_DIR)}'s {_MARKER} section "
        f"({len(FACT_ROWS)} facts)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
