#!/usr/bin/env python3
"""Generate docs/contribute/catalog-coverage.md -- Phase 6 of the
examples/catalog split (docs/contribute/plans/examples-catalog-split.md).

Phases 1-2 gave every case in `examples/ground_truth.json["taxonomy"]` an
`entity` (rule/scenario), a `rule_slug`/`variant_of`/`relation_type`/
`relation_axis` set, a `scenario_kind`, and an `ecosystem`. Before this
generator, every consumer that reported on catalog size
(examples/README.md's headline, the various coverage gates) still collapsed
all 197 cases into one flat count -- which is exactly the "three
demonstrations of one rule count as three ABI concepts" problem the plan's
"stop reporting all cases as semantically equal" section names. This script
reports the same 197 cases along five *independent* dimensions instead:

    rule coverage       -- how many distinct, ecosystem-neutral compatibility
                            rules the catalog demonstrates (by `rule_slug`,
                            deduplicated -- a rule and its variant(s)/
                            duplicate(s) count once)
    variant coverage     -- how many of those rules have a demonstrated
                            *variant* beyond their canonical case (a genuine
                            robustness demonstration under a different
                            condition -- language, evidence, public-surface,
                            ... -- see `relation_axis`), reported separately
                            from a plain *duplicate* (the same demonstration
                            restated with no distinguishing condition, per
                            `relation_type`): counting a duplicate as a
                            variant would inflate the catalog's demonstrated-
                            robustness claim (canonical, variant, and
                            duplicate cases reported separately -- a 2-case
                            family has exactly 1 variant or 1 duplicate, not
                            "more than one")
    scenario coverage    -- scenario-entity cases broken down by
                            `scenario_kind` (case-study / project-topology /
                            capability)
    ecosystem coverage   -- every case (rule or scenario) broken down by
                            `ecosystem`
    workflow coverage    -- user-facing task-oriented workflow examples;
                            derived from `examples/workflows/`'s real
                            subdirectory count (see the plan doc's Phase 5
                            row for the target set and progress against it)
                            rather than a static placeholder, so this
                            dimension can't go stale against Phase 5

This is a report, not a gate: it doesn't change what any existing check
counts, and it doesn't touch `examples/README.md`'s own headline/verdict
tables (`gen_examples_docs.py` owns those). `--check` fails (exit 1) if
regeneration would change the committed page, mirroring every other
`gen_*.py` generator in this repo.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "docs" / "contribute" / "catalog-coverage.md"

# Phase 3 resolver (scripts/CLAUDE.md). This script's own directory is
# already on sys.path when run directly, but not when imported as
# `scripts.gen_catalog_coverage_report` -- guard mirrors
# fact_detector_misuse.py's identical sibling-import guard for the
# identical reason.
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
import catalog_rule_registry  # noqa: E402
import example_catalog  # noqa: E402

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_catalog_coverage_report.py -- do not edit "
    "by hand. Run `python scripts/gen_catalog_coverage_report.py` to "
    "regenerate. -->"
)

# Phase 5's target workflow set (docs/contribute/plans/examples-catalog-split.md's
# own Phase 5 row) -- the single source both the target count and the target
# list below are derived from, so they can't independently drift from each
# other. Update this tuple (and the plan doc's Phase 5 row) together if the
# target set itself ever changes.
PHASE5_TARGET_WORKFLOWS: tuple[str, ...] = (
    "compare one library",
    "audit a release",
    "multi-library project",
    "evidence depth",
    "build/source evidence",
    "Python API",
    "suppressions",
    "GitHub Actions",
)


def _rule_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    """Rule/variant/duplicate coverage, derived from the canonical registry.

    The families, their canonical/variant/duplicate membership, and each
    rule's demonstrated-vs-referenced-only status all come from
    `catalog_rule_registry.build_families()` rather than being re-derived
    here: this page's headline is the one number the registry exists to keep
    honest, so re-deriving it from the raw taxonomy would be a second copy
    of exactly the join the registry owns.
    """
    rules = {k: v for k, v in taxonomy.items() if v["entity"] == "rule"}
    families = catalog_rule_registry.build_families(taxonomy)

    demonstrated = {
        slug: fam
        for slug, fam in families.items()
        if fam.status == catalog_rule_registry.STATUS_DEMONSTRATED
    }
    referenced_only = {
        slug: fam
        for slug, fam in families.items()
        if fam.status == catalog_rule_registry.STATUS_REFERENCED_ONLY
    }

    # A family with 2 cases has exactly 1 variant or 1 duplicate, not "more
    # than one". Variants and duplicates are counted from each case's own
    # `relation_type` (never from which bucket its family fell into), so a
    # mixed family -- one variant case plus one duplicate case sharing a
    # rule_slug, not present in today's data but not ruled out by the schema
    # either -- legitimately appears in both family sets rather than having
    # one of its cases silently miscounted as the other kind.
    variant_families = {s: f for s, f in demonstrated.items() if f.variant_cases}
    duplicate_families = {s: f for s, f in demonstrated.items() if f.duplicate_cases}
    variant_case_count = sum(len(f.variant_cases) for f in demonstrated.values())
    duplicate_case_count = sum(len(f.duplicate_cases) for f in demonstrated.values())
    singleton_count = sum(
        1
        for f in demonstrated.values()
        if not f.variant_cases and not f.duplicate_cases
    )

    lines = [
        "## Rule coverage",
        "",
        "Every rule named below is defined in `examples/catalog_rules.yaml`, "
        "the canonical rule registry (a repository file, not a published "
        "page). A slug used by a case but missing from "
        "that file (or defined there but used by no case) fails "
        "`scripts/gen_catalog_taxonomy.py` and "
        "`tests/test_catalog_taxonomy.py` -- which is what stops a typo, a "
        "synonym, or an accidental rename from silently becoming one more "
        "\"distinct compatibility rule\" in the headline below.",
        "",
        f"- **{len(families)} distinct compatibility rules** in total "
        f"-- **{len(demonstrated)}** demonstrated by at least one rule-entity "
        f"case (across **{len(rules)} rule-entity cases**), plus "
        f"**{len(referenced_only)}** named only in a scenario's own "
        "`related_rules` (a generic mechanism no single-library case "
        "demonstrates alone yet). The two are **not** equivalent coverage: "
        "a referenced-only rule has a definition and a scenario that "
        "composes it, but no case that isolates it.",
        f"- **{len(variant_families)} of the demonstrated rules** have "
        "a *variant* beyond their canonical case -- a genuine "
        "robustness demonstration under a different condition "
        f"({variant_case_count} variant cases total -- see the per-family "
        "breakdown below); these are robustness demonstrations of an "
        "already-counted rule, not additional rules.",
        f"- **{len(duplicate_families)} of the demonstrated rules** "
        "also have a *duplicate* -- the same demonstration restated "
        f"with no distinguishing condition ({duplicate_case_count} "
        "duplicate cases total); these don't add robustness coverage and "
        "are candidates for eventual removal, not a variant to keep. (A "
        "family can appear in both this count and the variant count above "
        "if it has one of each.)",
        f"- **{singleton_count} demonstrated rules** have exactly one case "
        "so far, with no variant or duplicate yet.",
        "",
        "| Rule | Canonical case | Variant case(s) | Duplicate case(s) |",
        "|---|---|---|---|",
    ]
    for slug in sorted(s for s, f in demonstrated.items() if len(f.rule_cases) > 1):
        fam = demonstrated[slug]
        variants = ", ".join(f"`{c}`" for c, _ in sorted(fam.variant_cases))
        duplicates = ", ".join(f"`{c}`" for c in sorted(fam.duplicate_cases))
        lines.append(
            f"| `{slug}` | `{fam.canonical_case}` | {variants} | {duplicates} |"
        )

    lines += [
        "",
        "### Referenced-only rules",
        "",
        f"{len(referenced_only)} rules the catalog names but does not yet "
        "isolate in a case of its own. Each is a real compatibility "
        "mechanism a scenario composes; adding a rule-entity case whose "
        "`rule_slug` is one of these promotes it to *demonstrated* "
        "automatically, with no registry edit.",
        "",
        "| Rule | Composed by |",
        "|---|---|",
    ]
    for slug in sorted(referenced_only):
        composed = ", ".join(
            f"`{c}`" for c in sorted(referenced_only[slug].scenario_cases)
        )
        lines.append(f"| `{slug}` | {composed} |")
    lines.append("")
    return "\n".join(lines)


def _scenario_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    scenarios = {k: v for k, v in taxonomy.items() if v["entity"] == "scenario"}
    by_kind: Counter[str] = Counter(
        entry["scenario_kind"]
        for entry in scenarios.values()  # type: ignore[misc]
    )
    lines = [
        "## Scenario coverage",
        "",
        f"**{len(scenarios)} scenario-entity cases** composing one or more "
        "rules into a realistic problem (an ecosystem case study, a "
        "multi-library project topology, or a capability/evidence "
        "demonstration) -- see each case's own `related_rules`.",
        "",
        "| Scenario kind | Cases |",
        "|---|---|",
    ]
    for kind in sorted(by_kind):
        lines.append(f"| `{kind}` | {by_kind[kind]} |")
    lines.append("")
    return "\n".join(lines)


def _ecosystem_coverage(taxonomy: dict[str, dict[str, object]]) -> str:
    by_eco: Counter[str] = Counter(
        entry["ecosystem"]
        for entry in taxonomy.values()  # type: ignore[misc]
    )
    lines = [
        "## Ecosystem coverage",
        "",
        "Every case, rule or scenario, tagged with the real-world ecosystem "
        "it models (`generic` for a language/platform-level mechanism with "
        "no particular project behind it).",
        "",
        "| Ecosystem | Cases |",
        "|---|---|",
    ]
    for eco in sorted(by_eco):
        lines.append(f"| `{eco}` | {by_eco[eco]} |")
    lines.append("")
    return "\n".join(lines)


def _workflow_coverage() -> str:
    workflows_dir = example_catalog.EXAMPLES_DIR / "workflows"
    workflows = (
        sorted(p.name for p in workflows_dir.iterdir() if p.is_dir())
        if workflows_dir.is_dir()
        else []
    )
    header = (
        f"**{len(workflows)} workflow example{'' if len(workflows) == 1 else 's'}** "
        f"so far, out of the {len(PHASE5_TARGET_WORKFLOWS)} task-oriented "
        "workflows Phase 5 of the examples/catalog split "
        "(`docs/contribute/plans/examples-catalog-split.md`) targets: "
        f"{', '.join(PHASE5_TARGET_WORKFLOWS)}."
    )
    rows = [f"| `{name}` |" for name in workflows] or ["| _(none yet)_ |"]
    return "\n".join(
        [
            "## Workflow coverage",
            "",
            header,
            "",
            "| Workflow |",
            "|---|",
            *rows,
            "",
            "Reported here as its real, current count (derived from "
            "`examples/workflows/`'s own subdirectories) rather than a "
            "static placeholder, so this page states all five dimensions "
            "the plan tracks, not just the ones already implemented.",
            "",
        ]
    )


def render() -> str:
    gt = example_catalog.load_ground_truth()
    taxonomy: dict[str, dict[str, object]] = gt["taxonomy"]  # type: ignore[assignment]

    parts = [
        GENERATED_NOTE,
        "",
        "# Catalog coverage by dimension",
        "",
        f"Phase 6 of the [examples/catalog split]"
        f"(plans/examples-catalog-split.md): the calibration "
        f"catalog under `examples/` is {len(taxonomy)} `caseNN_*` fixtures, "
        f"but not {len(taxonomy)} independent ABI/API concepts -- several "
        "are variants of the same rule, or scenarios composing rules "
        "already counted elsewhere. This page reports the catalog along "
        "five independent dimensions instead of one flat case count, so "
        '"three demonstrations of one rule" reads as "1 rule, 3 cases (1 '
        'canonical + 2 variants)" rather than "3 ABI concepts". Regenerate with '
        "`python scripts/gen_catalog_coverage_report.py` after any "
        "`ground_truth.json` change.",
        "",
        _rule_coverage(taxonomy),
        _scenario_coverage(taxonomy),
        _ecosystem_coverage(taxonomy),
        _workflow_coverage(),
    ]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if regeneration would change the committed page",
    )
    args = parser.parse_args()

    new_content = render()

    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.is_file() else None
        if current != new_content:
            print(
                f"{OUT_PATH.relative_to(ROOT)} is stale -- run "
                "`python scripts/gen_catalog_coverage_report.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT_PATH.relative_to(ROOT)} is up to date.")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(new_content, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
