#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_mcp_reference.py — exhaustive MCP tool parameter reference, generated
from `abicheck/mcp_server.py`'s `@mcp.tool()` functions instead of hand-copied.

Each `@mcp.tool()` function's signature (names, types, defaults) and Google-
style docstring `Args:` section are already the fact owner for its parameter
list; `docs/user-guide/mcp-integration.md` previously restated that list by
hand in a Markdown table per tool. This generator makes `docs/reference/
mcp-tools-reference.md` that exhaustive, generated parameter view;
`mcp-integration.md` stays the narrative/task-owner page (install, configure,
response envelopes, agent workflow examples, security model) and links here
per tool instead of re-deriving the parameter table.

Requires the optional `mcp` extra (`pip install "abicheck[mcp]"`) to import
`abicheck.mcp_server` — the same requirement `mcp-integration.md` itself
documents. Not wired into the `ai-readiness` CI job (which installs only
`[dev]`); mirrored by `tests/test_mcp_reference.py`, which runs wherever `mcp`
is installed (the `unit-tests`/`lint-and-types` CI jobs both install it).

Usage:
    python scripts/gen_mcp_reference.py            # write the file
    python scripts/gen_mcp_reference.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_DIR / "docs" / "reference" / "mcp-tools-reference.md"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_mcp_reference.py — do not edit by hand. "
    "Run `python scripts/gen_mcp_reference.py` to regenerate. -->"
)

#: Order matches `docs/user-guide/mcp-integration.md`'s existing tool
#: sections, not source-file declaration order.
TOOL_NAMES = (
    "abi_compare",
    "abi_dump",
    "abi_list_changes",
    "abi_explain_change",
    "abi_audit",
    "abi_estimate",
    "abi_scan",
)

_ARG_LINE_RE = re.compile(r"^(\w+):\s*(.*)$")


def _parse_args_section(doc: str | None) -> dict[str, str]:
    """Parse a Google-style docstring's ``Args:`` section into
    ``{param_name: description}``, folding a wrapped multi-line description
    (indented further than the ``name:`` line) into one string."""
    if not doc:
        return {}
    lines = inspect.cleandoc(doc).splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "Args:")
    except StopIteration:
        return {}
    params: dict[str, str] = {}
    current: str | None = None
    for line in lines[start + 1 :]:
        stripped = line.strip()
        if not stripped:
            continue
        # A new "Returns:"/"Raises:" section (or any bare top-level heading)
        # ends the Args block -- these docstrings only ever have Args:, but
        # guard anyway rather than assuming.
        if not line.startswith((" ", "\t")):
            break
        indent = len(line) - len(line.lstrip())
        m = _ARG_LINE_RE.match(stripped) if indent <= 4 else None
        if m:
            current = m.group(1)
            params[current] = m.group(2)
        elif current is not None:
            params[current] = f"{params[current]} {stripped}".strip()
    return params


def _type_str(annotation: object) -> str:
    if annotation is inspect.Parameter.empty:
        return ""
    text = str(annotation)
    return text.replace("'", "")


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def _tool_section(name: str, fn: object) -> list[str]:
    sig = inspect.signature(fn)  # type: ignore[arg-type]
    doc = inspect.getdoc(fn)
    summary = (doc or "").split("\n\n", 1)[0].strip().replace("\n", " ")
    arg_docs = _parse_args_section(doc)

    lines = [
        f"## `{name}`",
        "",
        summary,
        "",
        "| Parameter | Type | Required | Default | Description |",
        "|---|---|:--:|---|---|",
    ]
    for param_name, param in sig.parameters.items():
        has_default = param.default is not inspect.Parameter.empty
        required = "no" if has_default else "yes"
        default_str = f"`{_escape(str(param.default))}`" if has_default else "—"
        lines.append(
            f"| `{param_name}` | `{_escape(_type_str(param.annotation))}` | {required} | "
            f"{default_str} | {_escape(arg_docs.get(param_name, ''))} |"
        )
    lines.append("")
    return lines


def render() -> str:
    # Make the command work from a clean checkout (no install / no PYTHONPATH):
    # sys.path[0] is scripts/, not the repo root, so the abicheck import below
    # fails there without this.
    if str(REPO_DIR) not in sys.path:
        sys.path.insert(0, str(REPO_DIR))
    from abicheck import mcp_server

    lines = [
        GENERATED_NOTE,
        "",
        "# MCP Tools Reference",
        "",
        "Every parameter of every `abicheck-mcp` tool, generated directly from "
        "`abicheck/mcp_server.py`'s function signatures and docstrings. See "
        "[MCP Server (Agent Integration)](../user-guide/mcp-integration.md) "
        "for install/configure steps, response envelope shapes, agent "
        "workflow examples, and the security model — this page is the "
        "exhaustive parameter list only.",
        "",
    ]
    for name in TOOL_NAMES:
        lines += _tool_section(name, getattr(mcp_server, name))
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file is in sync instead of writing it",
    )
    args = parser.parse_args(argv)

    content = render()

    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != content:
            print(f"{OUT_PATH.relative_to(REPO_DIR)} is stale — regenerate with:")
            print("  python scripts/gen_mcp_reference.py")
            return 1
        print(f"{OUT_PATH.relative_to(REPO_DIR)} is in sync")
        return 0

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
