#!/usr/bin/env python3
# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""gen_agent_skills.py — publish `skills-src/` as self-contained Agent Skills.

ADR-058 / plan G36 P0.3. `skills-src/` is the one hand-authored copy: each
skill's `SKILL.md` plus its own `references/`, and one `shared/` tree of
Layer-B domain fragments every skill cites by link. This generator resolves
what each skill actually cites (transitively — a fragment may cite another
fragment), **copies** it into that skill's own `references/shared/`, and
rewrites every link so the installed skill resolves entirely inside its own
directory.

Copies, never symlinks: an installed skill is read from the perspective of one
directory, and a marketplace zip, a `skills.sh` subset install, or a Windows
checkout each break a live cross-skill link differently (ADR-058, "Source-of-
truth and publication model").

Three output trees, same content:

* ``.agents/skills/``  — the canonical portable target (Copilot, Codex, Cursor
  read it directly).
* ``.claude/skills/``  — Claude Code does not scan ``.agents/skills``.
* ``.gemini/skills/``  — nor does Gemini CLI.

Links pointing at this repository's own ``docs/`` pages are rewritten to the
published documentation site, whose host comes from ``mkdocs.yml``'s
``site_url`` and whose URL shape comes from ``mkdocs.yml``'s
``use_directory_urls`` (mkdocs's own default, ``true``, when the key is
absent) — never a hardcoded literal, so the generator cannot silently emit
broken links if either is ever changed.

Usage:
    python scripts/gen_agent_skills.py            # write the trees
    python scripts/gen_agent_skills.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_DIR / "skills-src"
SHARED_DIR = SRC_DIR / "shared"
DOCS_DIR = REPO_DIR / "docs"
MKDOCS_YML = REPO_DIR / "mkdocs.yml"

#: Every committed publication tree. `.agents/skills` is authoritative; the
#: other two exist because Claude Code and Gemini CLI do not scan it.
OUTPUT_ROOTS: tuple[Path, ...] = (
    REPO_DIR / ".agents" / "skills",
    REPO_DIR / ".claude" / "skills",
    REPO_DIR / ".gemini" / "skills",
)

#: Where a cited `shared/` fragment lands inside a generated skill, relative
#: to the skill's own root.
SHARED_SUBDIR = "references/shared"

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/gen_agent_skills.py from skills-src/ — "
    "do not edit by hand. Run `python scripts/gen_agent_skills.py` to "
    "regenerate. -->"
)

#: The substring `scripts/check_ai_readiness.py`'s generated-file-ownership
#: check looks for in every generated Markdown file under the output trees.
GENERATED_MARKER_SUBSTRING = "generated by scripts/gen_agent_skills.py"

#: Inline Markdown links `[text](target)` — the one link syntax skill sources
#: may use, so the rewrite below is exhaustive rather than best-effort.
_MD_LINK_RE = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)(\s+\"[^\"]*\")?\)")

#: Reference-style link definitions (`[label]: target`), which this rewrite
#: does not handle. Detected so generation *fails* on one rather than
#: publishing it untouched: `[guide][docs]` with a `[docs]: ../../docs/…`
#: definition is invisible to `_MD_LINK_RE`, so it would survive into every
#: installed tree still pointing at a repo path that does not exist there.
#: Rejecting is deliberate over rewriting — one syntax is the contract, and a
#: silently-supported second one is how the rewrite stops being exhaustive.
_MD_REF_DEF_RE = re.compile(r"^ {0,3}\[([^\]^][^\]]*)\]:\s*\S+", re.MULTILINE)

#: Markdown images (`![alt](target)`), excluded from `_MD_LINK_RE` by its
#: negative lookbehind and rejected here for the same reason as a reference
#: definition: the destination is never rewritten, and this generator copies
#: only Markdown — so a published skill would carry a repo-relative path to an
#: asset its own directory does not contain. Self-containment is the property
#: that makes a single skill directory installable on its own.
_MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)")

_FRONT_MATTER_RE = re.compile(r"\A---\r?\n.*?\r?\n---\r?\n", re.DOTALL)


class SkillGenerationError(RuntimeError):
    """A skill source tree that cannot be published as-is."""


# ---------------------------------------------------------------------------
# mkdocs-derived published-URL mapping
# ---------------------------------------------------------------------------


def _read_mkdocs_scalar(key: str) -> str | None:
    """Read one top-level scalar from mkdocs.yml without importing PyYAML.

    This script must stay pure-stdlib for the same reason
    `check_ai_readiness.py` does — it runs in gates that may execute before
    `pip install -e .`. Only two top-level scalars are needed and both are
    plain, unquoted or simply-quoted values.
    """
    if not MKDOCS_YML.is_file():
        return None
    pattern = re.compile(rf"^{re.escape(key)}\s*:\s*(.+?)\s*$", re.MULTILINE)
    for match in pattern.finditer(MKDOCS_YML.read_text(encoding="utf-8")):
        # Top-level only: a nested key is indented, and MULTILINE ^ would
        # otherwise match it mid-file.
        line_start = match.start()
        if line_start != 0 and not match.group(0).startswith(key):
            continue
        value = match.group(1).strip().strip("'\"")
        return value or None
    return None


def published_docs_url(docs_relative: str, anchor: str = "") -> str:
    """The published URL for a repo `docs/`-relative Markdown path.

    Host and path prefix come from `site_url`; the extension-to-URL mapping
    follows `use_directory_urls` (mkdocs's own default is `true`, applied only
    when the key is genuinely absent — not frozen as a second fact owner).
    Anchors pass through unchanged; mkdocs does not rewrite them.

    A missing or unreadable `site_url` is a hard error, not a fallback: an
    empty host silently yields a root-relative `/learn/verdicts/`, which
    resolves to nothing at all from an installed skill and contradicts this
    module's whole no-dangling-references guarantee. Failing here is what
    makes that guarantee real rather than best-effort.
    """
    raw_site_url = _read_mkdocs_scalar("site_url")
    if not raw_site_url or "://" not in raw_site_url:
        raise SkillGenerationError(
            f"{MKDOCS_YML.name}: no usable `site_url` (read {raw_site_url!r}) — "
            "it is the fact owner for the published docs host every generated "
            "skill's outbound links are rewritten against; without it the "
            "output would carry root-relative links that resolve nowhere from "
            "an installed skill"
        )
    site_url = raw_site_url.rstrip("/")
    raw_dir_urls = _read_mkdocs_scalar("use_directory_urls")
    directory_urls = True if raw_dir_urls is None else raw_dir_urls.lower() == "true"

    stem = (
        docs_relative[: -len(".md")] if docs_relative.endswith(".md") else docs_relative
    )
    if directory_urls:
        if stem == "index" or stem.endswith("/index"):
            stem = stem[: -len("index")].rstrip("/")
        path = f"{stem}/" if stem else ""
    else:
        path = f"{stem}.html"
    return f"{site_url}/{path}{anchor}"


# ---------------------------------------------------------------------------
# Source discovery
# ---------------------------------------------------------------------------


def discover_skills(src_dir: Path | None = None) -> list[Path]:
    """Every `skills-src/<name>/` directory holding a `SKILL.md`."""
    src_dir = SRC_DIR if src_dir is None else src_dir
    if not src_dir.is_dir():
        return []
    return sorted(
        child
        for child in src_dir.iterdir()
        if child.is_dir() and child.name != "shared" and (child / "SKILL.md").is_file()
    )


def _markdown_files(skill_dir: Path) -> list[Path]:
    files = [skill_dir / "SKILL.md"]
    references = skill_dir / "references"
    if references.is_dir():
        files.extend(sorted(p for p in references.rglob("*.md")))
    return files


def _link_targets(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    return [m.group(2) for m in _MD_LINK_RE.finditer(text)]


def _shared_fragment_for(path: Path, target: str, shared_dir: Path) -> str | None:
    """The `shared/` fragment basename `target` names, seen from `path`."""
    if "://" in target or target.startswith(("#", "mailto:", "/")):
        return None
    bare = target.split("#", 1)[0]
    if not bare.endswith(".md"):
        return None
    resolved = (path.parent / bare).resolve()
    try:
        relative = resolved.relative_to(shared_dir.resolve())
    except ValueError:
        return None
    if len(relative.parts) != 1:
        return None
    return relative.parts[0]


def resolve_shared_fragments(
    skill_dir: Path, shared_dir: Path | None = None
) -> list[str]:
    """Fragment basenames this skill cites, resolved to a fixed point.

    Scans `SKILL.md` **and** every file under the skill's own `references/`
    (a skill-specific reference may be the only thing citing a fragment), then
    keeps following citations *from copied fragments* until nothing new is
    found — a fragment may cite another fragment.
    """
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    found: set[str] = set()
    queue: list[Path] = list(_markdown_files(skill_dir))
    while queue:
        current = queue.pop()
        for target in _link_targets(current):
            name = _shared_fragment_for(current, target, shared_dir)
            if name is None:
                continue
            fragment = shared_dir / name
            if not fragment.is_file():
                raise SkillGenerationError(
                    f"{current.relative_to(REPO_DIR).as_posix()}: references "
                    f"shared fragment {name!r}, which does not exist under "
                    f"{shared_dir.relative_to(REPO_DIR).as_posix()}/"
                )
            if name not in found:
                found.add(name)
                queue.append(fragment)
    return sorted(found)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _strip_front_matter(text: str) -> str:
    return _FRONT_MATTER_RE.sub("", text, count=1)


def _split_front_matter(text: str) -> tuple[str, str]:
    match = _FRONT_MATTER_RE.match(text)
    if match is None:
        return "", text
    return match.group(0), text[match.end() :]


def _rewrite_target(
    source_path: Path,
    out_rel: str,
    target: str,
    shared_names: set[str],
    shared_dir: Path,
    docs_dir: Path,
    containment_root: Path,
) -> str:
    """Rewrite one link target for its position in the generated tree.

    `out_rel` is the generated file's path relative to the skill root, which
    is what a `shared/` fragment link must be made relative to.
    `containment_root` is the source directory this file's own relative links
    may not escape — the skill's own directory for a `SKILL.md`/`references/`
    file, and `shared/` for a fragment (whose only legitimate relative links
    are sibling fragments, already handled above).
    """
    if "://" in target or target.startswith(("#", "mailto:", "/")):
        return target

    bare, _, anchor = target.partition("#")
    anchor = f"#{anchor}" if anchor else ""
    if not bare:
        return target

    fragment = _shared_fragment_for(source_path, target, shared_dir)
    if fragment is not None:
        if fragment not in shared_names:  # pragma: no cover - resolver is exhaustive
            raise SkillGenerationError(
                f"{source_path.relative_to(REPO_DIR).as_posix()}: cites "
                f"fragment {fragment!r} that was not resolved for this skill"
            )
        destination = Path(SHARED_SUBDIR) / fragment
        return _relative_link(Path(out_rel), destination) + anchor

    resolved = (source_path.parent / bare).resolve()
    try:
        docs_relative = resolved.relative_to(docs_dir.resolve()).as_posix()
    except ValueError:
        docs_relative = None
    if docs_relative is not None:
        if not resolved.is_file():
            raise SkillGenerationError(
                f"{source_path.relative_to(REPO_DIR).as_posix()}: links to "
                f"docs page {bare!r}, which does not exist"
            )
        return published_docs_url(docs_relative, anchor)

    # A link that stays inside the skill's own tree (SKILL.md ->
    # references/foo.md) needs no rewriting; anything else escapes the
    # installed directory and is a hard error rather than a silent copy.
    try:
        resolved.relative_to(containment_root.resolve())
    except ValueError:
        raise SkillGenerationError(
            f"{source_path.relative_to(REPO_DIR).as_posix()}: link {target!r} "
            "escapes the skill's own directory and is neither a shared "
            "fragment nor a docs/ page"
        ) from None
    return target


def _relative_link(from_rel: Path, to_rel: Path) -> str:
    """POSIX relative link from one skill-relative file to another."""
    from_parts = from_rel.parent.parts
    to_parts = to_rel.parts
    common = 0
    while (
        common < len(from_parts)
        and common < len(to_parts) - 1
        and from_parts[common] == to_parts[common]
    ):
        common += 1
    ups = [".."] * (len(from_parts) - common)
    return "/".join([*ups, *to_parts[common:]])


def _render(
    source_path: Path,
    out_rel: str,
    shared_names: set[str],
    *,
    keep_front_matter: bool,
    containment_root: Path,
    shared_dir: Path | None = None,
    docs_dir: Path | None = None,
) -> str:
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    docs_dir = DOCS_DIR if docs_dir is None else docs_dir
    text = source_path.read_text(encoding="utf-8")
    front_matter, body = _split_front_matter(text)

    ref_defs = [m.group(1) for m in _MD_REF_DEF_RE.finditer(body)]
    if ref_defs:
        raise SkillGenerationError(
            f"{source_path}: reference-style link definition(s) "
            f"{sorted(ref_defs)} — skill sources must use inline "
            "`[text](target)` links only. The link rewrite does not see a "
            "reference definition, so it would be published verbatim and "
            "point outside the installed skill."
        )

    images = [m.group(2) for m in _MD_IMAGE_RE.finditer(body)]
    if images:
        raise SkillGenerationError(
            f"{source_path}: Markdown image(s) {sorted(images)} — this "
            "generator publishes Markdown only and never rewrites an image "
            "destination, so the installed skill would reference an asset it "
            "does not contain. Describe the diagram in text, or link the "
            "published docs page that hosts it."
        )

    def replace(match: re.Match[str]) -> str:
        label, target, title = match.group(1), match.group(2), match.group(3) or ""
        new_target = _rewrite_target(
            source_path,
            out_rel,
            target,
            shared_names,
            shared_dir,
            docs_dir,
            containment_root,
        )
        return f"[{label}]({new_target}{title})"

    body = _MD_LINK_RE.sub(replace, body)
    head = front_matter if keep_front_matter else ""
    return f"{head}{GENERATED_MARKER}\n\n{body.lstrip(chr(10))}"


def render_skill(skill_dir: Path, shared_dir: Path | None = None) -> dict[str, str]:
    """The complete generated content of one skill, keyed by skill-relative path.

    `shared_dir` defaults to the module-global `SHARED_DIR`, but a caller
    rendering a different source tree must pass that tree's own `shared/` —
    resolving fragments against one tree while discovering skills in another
    would mix two unrelated sources into one output.
    """
    shared_dir = SHARED_DIR if shared_dir is None else shared_dir
    fragments = resolve_shared_fragments(skill_dir, shared_dir)
    shared_names = set(fragments)
    out: dict[str, str] = {}

    out["SKILL.md"] = _render(
        skill_dir / "SKILL.md",
        "SKILL.md",
        shared_names,
        keep_front_matter=True,
        containment_root=skill_dir,
        shared_dir=shared_dir,
    )

    references = skill_dir / "references"
    if references.is_dir():
        for path in sorted(references.rglob("*.md")):
            rel = f"references/{path.relative_to(references).as_posix()}"
            out[rel] = _render(
                path,
                rel,
                shared_names,
                keep_front_matter=False,
                containment_root=skill_dir,
                shared_dir=shared_dir,
            )

    for name in fragments:
        rel = f"{SHARED_SUBDIR}/{name}"
        out[rel] = _render(
            shared_dir / name,
            rel,
            shared_names,
            keep_front_matter=False,
            containment_root=shared_dir,
            shared_dir=shared_dir,
        )
    return out


def render_all(src_dir: Path | None = None) -> dict[str, str]:
    """Every generated file, keyed by `<skill-name>/<skill-relative path>`.

    Also enforces the no-orphan rule: a `shared/` fragment no skill cites,
    directly or transitively, is dead content and fails generation.
    """
    src_dir = SRC_DIR if src_dir is None else src_dir
    # The shared tree always belongs to the source tree being rendered, never
    # to whatever the module globals happen to point at — otherwise a caller
    # rendering an alternate `src_dir` silently resolves fragments against,
    # and orphan-checks, this repository's own `skills-src/shared/`.
    shared_dir = src_dir / "shared"
    skills = discover_skills(src_dir)
    if not skills:
        raise SkillGenerationError(f"no skills found under {src_dir}")

    rendered: dict[str, str] = {}
    cited: set[str] = set()
    for skill_dir in skills:
        cited.update(resolve_shared_fragments(skill_dir, shared_dir))
        for rel, content in render_skill(skill_dir, shared_dir).items():
            rendered[f"{skill_dir.name}/{rel}"] = content

    available = (
        {p.name for p in shared_dir.glob("*.md")} if shared_dir.is_dir() else set()
    )
    orphans = sorted(available - cited)
    if orphans:
        raise SkillGenerationError(
            "shared fragment(s) never cited by any skill (directly or "
            f"transitively): {', '.join(orphans)} — cite them or delete them"
        )
    return rendered


# ---------------------------------------------------------------------------
# Write / check
# ---------------------------------------------------------------------------


def _rendered_skill_names(rendered: dict[str, str]) -> set[str]:
    """The `<skill-name>` directories this render produced."""
    return {rel.split("/", 1)[0] for rel in rendered}


def _is_generated_skill_dir(path: Path) -> bool:
    """True if `path` is a skill directory *this* generator produced.

    Ownership is read off the emitted content itself — the `SKILL.md`'s own
    generated-file marker — rather than inferred from the current render.
    That distinction is what makes a removed or renamed skill detectable: its
    name is gone from the render, so a render-derived ownership set would stop
    considering the stale directory owned and leave it published forever while
    `--check` still passed. A hand-authored skill sharing the output root
    carries no marker and is never touched.
    """
    skill_md = path / "SKILL.md"
    if not skill_md.is_file():
        return False
    return GENERATED_MARKER_SUBSTRING in skill_md.read_text(encoding="utf-8").lower()


def _owned_skill_names(rendered: dict[str, str], root: Path) -> set[str]:
    """Every skill directory the generator owns under `root`.

    The union of what this render emits and what a previous render left
    behind (identified by its marker), so a stale directory stays in scope
    for both removal and drift reporting.

    Scoping still matters in the other direction: an output root can
    legitimately hold skills this generator did not produce (`.claude/skills/`
    is also where a repository's own hand-authored Claude Code skills live),
    and wiping the whole root would silently delete them.
    """
    owned = _rendered_skill_names(rendered)
    if root.is_dir():
        owned |= {
            child.name
            for child in root.iterdir()
            if child.is_dir() and _is_generated_skill_dir(child)
        }
    return owned


def _existing_tree(root: Path, owned: set[str]) -> dict[str, str]:
    if not root.is_dir():
        return {}
    return {
        p.relative_to(root).as_posix(): p.read_text(encoding="utf-8")
        for name in sorted(owned)
        for p in sorted((root / name).rglob("*"))
        if p.is_file()
    }


def write_trees(
    rendered: dict[str, str], roots: tuple[Path, ...] | None = None
) -> None:
    roots = OUTPUT_ROOTS if roots is None else roots
    for root in roots:
        # Includes previously-generated directories no longer in the render,
        # so a renamed or deleted skill is actually removed from the published
        # trees rather than left behind.
        for name in _owned_skill_names(rendered, root):
            if (root / name).exists():
                shutil.rmtree(root / name)
        for rel, content in rendered.items():
            path = root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


def check_trees(
    rendered: dict[str, str], roots: tuple[Path, ...] | None = None
) -> list[str]:
    roots = OUTPUT_ROOTS if roots is None else roots
    problems: list[str] = []
    for root in roots:
        try:
            rel_root = root.relative_to(REPO_DIR).as_posix()
        except ValueError:  # a test-supplied root outside the repo
            rel_root = root.as_posix()
        existing = _existing_tree(root, _owned_skill_names(rendered, root))
        for rel in sorted(set(rendered) | set(existing)):
            if rel not in existing:
                problems.append(f"{rel_root}/{rel}: missing")
            elif rel not in rendered:
                problems.append(f"{rel_root}/{rel}: stale (no longer generated)")
            elif existing[rel] != rendered[rel]:
                problems.append(f"{rel_root}/{rel}: out of date")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed trees match skills-src/ instead of writing",
    )
    args = parser.parse_args(argv)

    try:
        rendered = render_all()
    except SkillGenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.check:
        problems = check_trees(rendered)
        if problems:
            print("Generated agent-skill trees are out of sync:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print(
                "\nRun `python scripts/gen_agent_skills.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(
            f"agent skills in sync ({len(rendered)} files × {len(OUTPUT_ROOTS)} trees)"
        )
        return 0

    write_trees(rendered)
    print(
        f"wrote {len(rendered)} files to "
        + ", ".join(r.relative_to(REPO_DIR).as_posix() for r in OUTPUT_ROOTS)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
