# Copyright 2026 Nikolay Petrov
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Bug classes registered before defect families existed (2026-09-30).

These are exempt from the rule that a family-F1..F5 class must list its
family harness among its seed_tests. The set only shrinks: attach a
legacy class to its harness and delete it from here.
"""

from __future__ import annotations

LEGACY_UNATTACHED: frozenset[str] = frozenset(
    {
        "adapter.duck_typed_view_attribute_drift",
        "api.positional_slot_rebinding",
        "cache.bookkeeping_describes_a_different_set_than_it_retains",
        "cardinality.member_request_drops_scalar_field",
        "ci.inert_concurrency_group_key",
        "ci.instrumentation_without_a_consumer",
        "ci.path_filter_omits_own_build_infrastructure",
        "ci.shared_budget_over_heterogeneous_matrix",
        "ci.unrelated_apt_source_gates_the_job",
        "classification.declaration_existence_as_export_obligation",
        "classification.default_branch_asserts_more_than_inputs",
        "classification.demotion_applied_beyond_its_justification",
        "classification.name_shape_as_contract_membership",
        "classification.one_spelling_of_a_path_treated_as_its_identity",
        "classification.two_agreeing_sources_read_as_unknown",
        "cli.default_format_unreachable_operand",
        "cli_surface.capability_guard_diverged_from_pipeline",
        "cli_surface.copied_option_table_went_stale",
        "cli_surface.derived_table_lost_in_its_own_encoding",
        "cli_surface.destination_collision_checked_only_by_exact_path",
        "cli_surface.name_independent_dispatch_undone_downstream",
        "cli_surface.retired_spelling_in_remediation",
        "comparability.incidental_ordering_treated_as_contract",
        "concurrency.compound_cache_operation_under_fan_out",
        "concurrency.forked_child_unbounded_reap",
        "concurrency.gc_census_beside_live_thread",
        "config.command_specific_discovery",
        "config.env_flag_value_domain",
        "config.front_end_default_divergence",
        "config.inferred_root_bypassed_by_a_second_entry_point",
        "config.input_granted_unrelated_authority",
        "config.option_dropped_at_a_dispatch_branch",
        "config.propagation_completeness",
        "config.rule_language_class_collapsed",
        "config.sided_shared_input_dropped",
        "config.textual_substitution_into_a_structured_document",
        "coverage.discovery_derived_completeness",
        "detector.diff_confirmation_precondition",
        "evidence.backfill_bare_name_match",
        "evidence.container_presence_read_as_evidence_content",
        "evidence.entry_point_skips_extraction_record",
        "evidence.export_fact_join_disagreement",
        "evidence.export_presence_as_declaration_presence",
        "evidence.operand_shape_silently_unresolved",
        "evidence.richer_model_hides_weaker_observation",
        "evidence.silent_degradation_to_clean_verdict",
        "evidence.spelling_matcher_same_offset_underreport",
        "evidence.spelling_used_as_a_semantic_model",
        "evidence.stored_snapshot_rederivation",
        "evidence.surface_membership_asymmetry",
        "extraction.ast_wrapper_chain_traversal",
        "extraction.function_local_declaration_leaks_into_surface",
        "extraction.implicit_declaration_leaks_into_surface",
        "extraction.implicit_language_rule_read_off_one_explicit_key",
        "extraction.language_mode_export_evidence",
        "extraction.macho_export_index_double_strip",
        "extraction.macho_mangled_identity_normalization",
        "gate.per_member_axis_fold",
        "gating.consumer_scope_enrichment",
        "guard.absent_capability_vs_real_failure",
        "guard.differential_test_shares_state_with_itself",
        "guard.platform_convention_without_a_gate",
        "guard.proxy_predicate_overshoots_justification",
        "identity.name_and_referent_compared_as_one",
        "identity.platform_decorated_mangled_name",
        "identity.release_edge_keyed_on_side_summary",
        "identity.second_node_key_scheme",
        "identity.special_member_variant_family",
        "invariant.blanket_assertion_over_widened_population",
        "matching.dedup_key_soundness",
        "perf.a_whole_document_retained_for_a_narrow_projection",
        "perf.admission_commits_the_whole_probed_budget",
        "perf.bounded_cache_budget_omits_what_it_retains",
        "perf.cache_fast_path_bypasses_shared_coordination",
        "perf.derived_cache_must_match_what_recomputing_would_give",
        "perf.enumerable_value_space_allocated_per_occurrence",
        "perf.evidence_released_before_its_consumer_runs",
        "perf.fixed_layout_fast_path_field_decoding",
        "perf.narrowed_computation_must_equal_the_unnarrowed_answer",
        "perf.optimization_wired_to_one_of_several_equivalent_paths",
        "perf.per_symbol_dto_carries_a_per_instance_dict",
        "perf.pure_content_digest_recomputed_per_consumer",
        "perf.retention_decided_by_one_switch_not_by_consumers",
        "perf.reuse_key_normalizes_an_ordered_input",
        "perf.shared_projection_read_as_an_owned_copy",
        "perf.shared_resource_gate_keyed_on_a_per_caller_value",
        "perf.streaming_producer_joined_at_the_encoder",
        "policy.disposition_conservation",
        "policy.public_surface_reachability",
        "registry.kind_completeness",
        "release.cartesian_product_contract",
        "report.finding_entry_builder_parity",
        "report.refusal_reaches_only_the_primary_output",
        "report.scalar_release_projection_drift",
        "report.shared_display_budget_starvation",
        "report.unestablished_result_reads_as_success",
        "report.unobserved_population_counted_as_observed",
        "report.untrusted_value_escapes_its_cell",
        "scoping.aggregate_view_starvation",
        "scoping.declaration_kind_forwarded_unfiltered",
        "serialization.pure_projection_mutates_its_own_input",
        "serialization.str_enum_downcast_via_generic_rewrite",
        "serialization.whole_document_materialised_to_write_it",
        "shell.empty_array_expansion_under_nounset",
        "status.container_existence_taken_for_completed_work",
        "storage.legacy_availability_collapse",
        "storage.out_of_band_snapshot_reader_envelope_drift",
        "storage.safety_limit_used_as_allocation_size",
        "storage.short_decode_mistaken_for_complete_decode",
        "storage.third_party_contract_at_scale",
        "test_double.narrower_than_the_real_signature",
        "test_fixture.host_artifact_assumed_capability",
        "test_harness.destructive_reset_of_a_caller_supplied_path",
        "test_harness.git_inherits_developer_signing_config",
        "test_harness.nested_session_prunes_outer_temp_root",
        "test_infra.autouse_allocator_cannot_recover",
        "test_infra.caller_owned_directory_fabricated",
        "tests.constructed_environment_drops_ambient_mitigation",
        "tests.dead_harness_reads_as_a_passing_control",
        "tests.fixture_fabricates_a_state_the_types_forbid",
        "tests.locale_dependent_repo_text_read",
        "tooling.platform_dependent_path_key",
        "tooling.platform_dependent_record_separator",
        "trust_boundary.shell_workflow_injection",
    }
)
